### ISSUE TITLE
Error on lint using Python 3.5.2 (master branch)

### ISSUE THREAD

**Issue by pyvim** [PyCQA/pylint#1053]
### Steps to reproduce
python3.5 -m pylint main.py

### Current behavior
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/usr/local/lib/python3.5/dist-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1292, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 718, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 829, in _do_check
    for descr in self.expand_files(files_or_modules):
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 861, in expand_files
    self.config.black_list_re)
  File "/usr/local/lib/python3.5/dist-packages/pylint/utils.py", line 900, in expand_modules
    is_namespace = spec.type == modutils.ModuleType.PY_NAMESPACE
AttributeError: 'tuple' object has no attribute 'type'

### pylint --version output
pylint 2.0.0, 
astroid 1.4.8
Python 3.5.2 (default, Jul 17 2016, 00:00:00) 
[GCC 4.8.4]

**Comment by PCManticore** [comment]
You need astroid from the master branch in order to work with pylint from the master branch.
