### ISSUE TITLE
'pkg_resources' has no attribute '_namespace_packages'

### ISSUE THREAD

**Issue by jakirkham** [PyCQA/pylint#1067]
### Steps to reproduce

1. Setup docker.
2. Clone this PR ( https://github.com/conda-forge/staged-recipes/pull/1225 ).
3. Run `./scripts/run_docker_build.sh`.

### Current behavior

Details in [CI log]( https://circleci.com/gh/conda-forge/staged-recipes/7201 ). Relevant snippet shown below.

```
$ pylint --help
Traceback (most recent call last):
  File "/opt/conda/envs/_test/bin/pylint", line 6, in <module>
    sys.exit(pylint.run_pylint())
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/pylint/lint.py", line 1229, in __init__
    linter.load_default_plugins()
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/pylint/lint.py", line 468, in load_default_plugins
    checkers.initialize(self)
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/pylint/checkers/__init__.py", line 111, in initialize
    register_plugins(linter, __path__[0])
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/pylint/utils.py", line 963, in register_plugins
    module = load_module_from_file(join(directory, filename))
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/astroid/modutils.py", line 267, in load_module_from_file
    modpath = modpath_from_file(filepath, extrapath)
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/astroid/modutils.py", line 317, in modpath_from_file
    if _check_init(path, modpath[:-1]):
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/astroid/modutils.py", line 277, in _check_init
    if not _is_namespace('.'.join(modpath)) and not _has_init(path):
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/astroid/modutils.py", line 616, in _is_namespace
    and modname in pkg_resources._namespace_packages)
AttributeError: module 'pkg_resources' has no attribute '_namespace_packages'
TESTS FAILED: pylint-1.6.4-py35_0
```

### Expected behavior

Normal help message sans traceback.

### pylint --version output

Don't think this works either, but am building 1.6.4.

Please ask if you need more info. Happy to help. 😄

**Comment by PCManticore** [comment]
It seems this was fixed by providing setuptools as a dependency here https://github.com/conda-forge/staged-recipes/pull/1225/files? Is there anything we need to do over here?

**Comment by jakirkham** [comment]
Nope, sorry, this should be closed.
