### ISSUE TITLE
pylint3 fails on os.foo()

### ISSUE THREAD

**Issue by quazgar** [PyCQA/pylint#1122]
### Steps to reproduce
1. Create file: `echo "os.foo()" >> os_fail.py`
2. Test with pylint3: `pylint3 os_fail.py`
### Current behavior

```
************* Module os_fail
C:  1, 0: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/usr/bin/pylint3", line 3, in <module>
    run_pylint()
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 736, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 867, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 947, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/usr/lib/python3/dist-packages/pylint/checkers/typecheck.py", line 337, in visit_attribute
    if re.match(pattern, node.attrname):
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 822, in parse
    source = Tokenizer(str)
  File "/usr/lib/python3.5/sre_parse.py", line 225, in __init__
    self.__next()
  File "/usr/lib/python3.5/sre_parse.py", line 239, in __next
    self.string, len(self.string) - 1) from None
sre_constants.error: bad escape (end of pattern) at position 0
```
### Expected behavior

Should just work, not throw an exception.
### pylint --version output

```
$ pylint3 --version
pylint3 1.5.6,
astroid 1.4.8
Python 3.5.2+ (default, Sep 22 2016, 12:18:14)
[GCC 6.2.0 20160914]
```

**Comment by The-Compiler** [comment]
I can't reproduce this, neither with your old pylint version nor on the newest release.

I'd guess this is due to an invalid regex in your config file?

**Comment by quazgar** [comment]
Ok, I found the culprit, my `generated-members` configuration option had this value:

    generated-members=numpy\..*

Pylint (3, not 2) does not seem to understand the escaped `.`, because `numpy.*` works (but of course also matches `numpyfoo` now).

**Comment by PCManticore** [comment]
I cannot reproduce this as well, using the newest release and the code from the master branch. Tried with both Python 2 and Python 3, to no avail.

**Comment by quazgar** [comment]
Could you check again with this command line?

    pylint --generated-members='numpy\..py' os_fail.py
