### ISSUE TITLE
pylint exits with IndexError on python3.5 when a class with async function is defined previously and a function references self

### ISSUE THREAD

**Issue by diefans** [PyCQA/pylint#1126]
### Steps to reproduce

``` bash
VENV=/tmp/test_pylint
python3.5 -m venv $VENV
cat > $VENV/pylint_bug.py << EOF
class MyClass:
    async def method(self):
        pass


# also possible
# def function(self):
def function():
    assert self.attr
EOF

$VENV/bin/pip install pylint==1.6.4
$VENV/bin/pylint -rn $VENV/pylint_bug.py
```
### Current behavior

```
No config file found, using default configuration
************* Module pylint_bug
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing class docstring (missing-docstring)
C:  2,10: Missing method docstring (missing-docstring)
R:  1, 0: Too few public methods (1/2) (too-few-public-methods)
C:  6, 0: Missing function docstring (missing-docstring)
Traceback (most recent call last):
  File "/tmp/test_pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/lint.py", line 1310, in __init__
    linter.check(args)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/lint.py", line 732, in check
    self._do_check(files_or_modules)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/lint.py", line 863, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/lint.py", line 944, in check_astroid_module
    walker.walk(ast_node)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/utils.py", line 941, in walk
    cb(astroid)
  File "/private/tmp/test_pylint/lib/python3.5/site-packages/pylint/checkers/classes.py", line 578, in visit_attribute
    self._accessed[-1][attrname].append(node)
IndexError: list index out of range
```
### Expected behavior

At least no crash/exit of pylint

```
No config file found, using default configuration
************* Module pylint_bug
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing class docstring (missing-docstring)
C:  2,10: Missing method docstring (missing-docstring)
R:  1, 0: Too few public methods (1/2) (too-few-public-methods)
C:  6, 0: Missing function docstring (missing-docstring)
E:  7,11: Undefined variable 'self' (undefined-variable)
```
### pylint --version output

```
No config file found, using default configuration
pylint 1.6.4, 
astroid 1.4.8
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by adongy** [comment]
I can reproduce the same behavior.

**Comment by PCManticore** [comment]
Me too. We will look into it.
