### ISSUE TITLE
Local variable 'display_name' referenced before assignment

### ISSUE THREAD

**Issue by hdekker** [PyCQA/pylint#1163]
### Steps to reproduce
1. Prepare code with 'E1120' issue because of a tuple not assigned correctly in function arguments
2. Run pylint checker
3. Pylint checker finds correct issue, but crashes while adding message in TypeChecker class.

### Current behavior
Generating DYML_app_config_dypf.pylint
pylint on Solaris 10: DYML_app_config_dypf.py to DYML_app_config_dypf.pylint
Traceback (most recent call last):
  File "/vobs/litho/cadbin/pylint", line 4, in <module>
    lint.Run(sys.argv[1:])
  File "/vobs/litho/cadlib/pylint/lint.py", line 850, in __init__
    linter.check(args)
  File "/vobs/litho/cadlib/pylint/lint.py", line 483, in check
    self.check_astng_module(astng, walker, rawcheckers)
  File "/vobs/litho/cadlib/pylint/lint.py", line 555, in check_astng_module
    walker.walk(astng)
  File "/vobs/litho/cadlib/pylint/utils.py", line 536, in walk
    self.walk(child)
  File "/vobs/litho/cadlib/pylint/utils.py", line 536, in walk
    self.walk(child)
  File "/vobs/litho/cadlib/pylint/utils.py", line 536, in walk
    self.walk(child)
  File "/vobs/litho/cadlib/pylint/utils.py", line 536, in walk
    self.walk(child)
  File "/vobs/litho/cadlib/pylint/utils.py", line 536, in walk
    self.walk(child)
  File "/vobs/litho/cadlib/pylint/utils.py", line 533, in walk
    cb(astng)
  File "/vobs/litho/cadlib/pylint/checkers/typecheck.py", line 358, in visit_callfunc
    self.add_message('E1120', node=node, args=display_name)
UnboundLocalError: local variable 'display_name' referenced before assignment
*** Error code 1
clearmake: Error: Build script failed for ".DYML/com/int/bin/DYML_app_config_dypf.pylint"
Aborting...

### Expected behavior
Just add a message with E1120, without raising a Pylint exception

### Bug?
Line 354-358 from pylint/checkers/typecheck.py
                if name is None:
                    display = '<tuple>'
                else:
                    display_name = repr(name)
                self.add_message('E1120', node=node, args=display_name)

First condition sets variable 'display' instead of 'display_name'

### pylint --version output
0.22

**Comment by PCManticore** [comment]
Please upgrade to a more recent Pylint version, 0.22 is antique.
