### ISSUE TITLE
Can't use parentheses in the regex for generated-members

### ISSUE THREAD

**Issue by AdamWill** [PyCQA/pylint#1167]
### Steps to reproduce
1. Run `pylint --generated-members="(SESSION|session).rollback" somefile`

### Current behavior

pylint crashes with this traceback:

    Traceback (most recent call last):
      File "/usr/bin/pylint", line 9, in <module>
        load_entry_point('pylint==1.6.4', 'console_scripts', 'pylint')()
      File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
        Run(sys.argv[1:])
      File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 1310, in __init__
        linter.check(args)
      File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 732, in check
        self._do_check(files_or_modules)
      File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 863, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 944, in check_astroid_module
        walker.walk(ast_node)
      File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
        self.walk(child)
      File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
        self.walk(child)
      File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
        self.walk(child)
      File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
        self.walk(child)
      File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 941, in walk
        cb(astroid)
      File "/usr/lib/python2.7/site-packages/pylint/checkers/typecheck.py", line 331, in visit_attribute
        if re.match(pattern, node.attrname):
      File "/usr/lib64/python2.7/re.py", line 141, in match
        return _compile(pattern, flags).match(string)
      File "/usr/lib64/python2.7/re.py", line 251, in _compile
        raise error, v # invalid expression
    sre_constants.error: unbalanced parenthesis

### Expected behavior

It shouldn't crash, but accept the regex.

### pylint --version output

[adamw@adam pagure (no-member *%)]$ pylint --version
pylint 1.6.4, 
astroid 1.4.5
Python 2.7.12 (default, Sep 29 2016, 12:52:02) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]

I'm working on a project which uses SQLAlchemy's tricksy `scoped_session` factory, that uses `__call__` to pass calls through to the instance it produces. This confuses pylint. I want to use generated-members to allow the methods the project calls on `scoped_session` instances, but they have very generic names (`add`, `close`, `commit` etc) and I don't want to whitelist *any* members with those names. The project always names these `scoped_session` instances as `session` or `SESSION`, so I want to use a regex like `(session|SESSION).add`, for instance, so I don't need to have two entries for each member name. But it seems pylint won't let me.

**Comment by AdamWill** [comment]
Thanks a lot!
