### ISSUE TITLE
Strange AttributeError when running Pylint on a file with "import traceback" and Python 3.6

### ISSUE THREAD

**Issue by mikez302** [PyCQA/pylint#1291]
I have a file named `hello_world.py` with the following contents:

    #!/usr/bin/env python3

    import traceback

    print("Hello world!")

If I run `pylint hello_world.py` from the command line, I get the following result:

    No config file found, using default configuration
    ************* Module hello_world
    C:  1, 0: Missing module docstring (missing-docstring)
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pylint", line 11, in <module>
        sys.exit(run_pylint())
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/__init__.py", line 17, in run_pylint
        Run(sys.argv[1:])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/lint.py", line 1333, in __init__
        linter.check(args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/lint.py", line 755, in check
        self._do_check(files_or_modules)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/lint.py", line 886, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/lint.py", line 967, in check_astroid_module
        walker.walk(ast_node)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/utils.py", line 959, in walk
        self.walk(child)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/utils.py", line 956, in walk
        cb(astroid)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1051, in visit_import
        module = next(node.infer_name_module(parts[0]))
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/context.py", line 49, in cache_generator
        for result in generator:
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/bases.py", line 302, in wrapped
        for res in _func(node, context, **kwargs):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/inference.py", line 123, in infer_import
        yield self.do_import_module(name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/mixins.py", line 129, in do_import_module
        relative_only=level and level >= 1)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 492, in import_module
        return MANAGER.ast_from_module_name(absmodname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/manager.py", line 136, in ast_from_module_name
        return self.ast_from_file(filepath, modname, fallback=False)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/manager.py", line 86, in ast_from_file
        return AstroidBuilder(self).file_build(filepath, modname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/builder.py", line 141, in file_build
        module = self._data_build(data, modname, path)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/builder.py", line 185, in _data_build
        module = builder.visit_module(node, modname, node_file, package)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in visit_module
        newnode.body = [self.visit(child, newnode) for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in <listcomp>
        newnode.body = [self.visit(child, newnode) for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 957, in visit_classdef
        newnode = super(TreeRebuilder3k, self).visit_classdef(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in visit_classdef
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in <listcomp>
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 543, in visit_functiondef
        assign_ctx=assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in _visit_functiondef
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in <listcomp>
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 510, in visit_for
        assign_ctx=assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 503, in _visit_for
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 503, in <listcomp>
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 591, in visit_if
        for child in node.orelse]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 591, in <listcomp>
        for child in node.orelse]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 589, in visit_if
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 589, in <listcomp>
        for child in node.body]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 447, in visit_expr
        newnode.value = self.visit(node.value, newnode, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in visit_call
        for child in node.args]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in <listcomp>
        for child in node.args]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in visit
        visit_method = getattr(self, visit_name)
    AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'

The `import traceback` line has something to do with it. If I delete this line and run `pylint hello_world.py`, I see the report and statistics, as I would expect.

This started happening after I upgraded from Python 3.5.2 to Python 3.6.0. If I run `/Library/Frameworks/Python.framework/Versions/3.6/bin/pylint hello_world.py`, I get the error, but if I run `/Library/Frameworks/Python.framework/Versions/3.5/bin/pylint hello_world.py`, even with the `import traceback` line in the file, I see the output I would expect. I am running Mac OS X 10.11.6.

**Comment by degustaf** [comment]
The most recent release of pylint doesn't support Python 3.6.  The traceback module uses f-strings, which is what is causing this crash.  It looks like this will work with the master branches of pylint and [astroid](https://github.com/PyCQA/astroid).

This issue should be closed.

**Comment by PCManticore** [comment]
Yes, we don't support 3.6 yet, but it is work in progress.
