### ISSUE TITLE
Crash: Uninferable object is not an iterator / _Yes object is not an iterator

### ISSUE THREAD

**Issue by evanj** [PyCQA/pylint#1326]
### Steps to reproduce
Run `pylint pylint_bug.py` (see below for file contents)

### Current behavior

Using the pylint from git commit e0fdd25c214e60bef10fbaa46252f4aaa74de8c2:

```
Traceback (most recent call last):
  File "/Users/evanjones/pylint/venv/bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.0.0', 'console_scripts', 'pylint')()
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/checkers/exceptions.py", line 356, in visit_tryexcept
    self._check_catching_non_exception(handler, exc, part)
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/checkers/exceptions.py", line 285, in _check_catching_non_exception
    inferred = [utils.safe_infer(elt) for elt in exc.elts]
  File "/Users/evanjones/pylint/venv/lib/python2.7/site-packages/pylint-2.0.0-py2.7.egg/pylint/checkers/utils.py", line 767, in safe_infer
    value = next(inferit)
TypeError: Uninferable object is not an iterator
```

### Expected behavior

It should not crash

### pylint --version output

```
pylint 2.0.0, 
astroid 1.5.0
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
```

### Input file

```
import socket

RETRYABLE_EXCEPTIONS = (socket.error,)

def exception_handler():
    try:
        print "hello"
    except RETRYABLE_EXCEPTIONS + tuple():
        print "exception caught"
exception_handler()
```

**Comment by evanj** [comment]
awesome thank you!
