### ISSUE TITLE
AttributeError: 'Unknown' object has no attribute 'name'

### ISSUE THREAD

**Issue by degustaf** [PyCQA/pylint#1365]
### Steps to reproduce
```
$ cat test_compile.py 
class foo(object):
    def foo(self):
        a = +4294967296  # 1 << 32
        self.foo.__code__.co_consts
$ pylint test_compile.py
```

### Current behavior
```
No config file found, using default configuration
************* Module test_compile
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Black listed name "foo" (blacklisted-name)
C:  1, 0: Missing class docstring (missing-docstring)
C:  2, 4: Black listed name "foo" (blacklisted-name)
C:  2, 4: Missing method docstring (missing-docstring)
C:  3, 8: Invalid variable name "a" (invalid-name)
W:  5, 8: Statement seems to have no effect (pointless-statement)
Traceback (most recent call last):
  File "/home/degustaf/.virtualenvs/pylint/bin/pylint", line 11, in <module>
    load_entry_point('pylint==1.7.0', 'console_scripts', 'pylint')()
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/checkers/typecheck.py", line 626, in visit_attribute
    self.config.ignored_modules):
  File "/home/degustaf/.virtualenvs/pylint/local/lib/python2.7/site-packages/pylint/checkers/typecheck.py", line 83, in _is_owner_ignored
    module_name = owner.root().name
AttributeError: 'Unknown' object has no attribute 'name'
```

### Expected behavior
There should be no Traceback.

### pylint --version output
No config file found, using default configuration
pylint 1.7.0, 
astroid 1.5.0
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

**Comment by degustaf** [comment]
Note that this was found while investigating the failures of #1360.

**Comment by PCManticore** [comment]
Thanks, I can reproduce it as well.

**Comment by exhuma** [comment]
I'm still getting this on pylint 1.7.2

Has this not been released yet?

**Comment by PCManticore** [comment]
@exhuma It has been released. I cannot reproduce this any longer with:

```
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
```

If you have some other code that reproduces this problem, please open a new issue.
