### ISSUE TITLE
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:

### ISSUE THREAD

**Issue by degustaf** [PyCQA/pylint#1367]
### Steps to reproduce
```
$ cat testNT.py
from collections import namedtuple
print(namedtuple('NT', ('abc', 'def'), rename=True)._fields)

$ pylint --rcfile=None testNT.py 
```

### Current behavior
```
No config file found, using default configuration
************* Module testNT
C:  1, 0: Invalid module name "testNT" (invalid-name)
C:  1, 0: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 182, in _data_build
    node = _parse(data + '\n')
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 41, in _parse
    return compile(string, "<string>", 'exec', _ast.PyCF_ONLY_AST)
  File "<string>", line 15
    def = property(lambda self: self[1], doc='Alias for field number 1')
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".tox/py36/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 612, in visit_attribute
    infered = list(node.expr.infer())
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/node_classes.py", line 239, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/brain/brain_namedtuple_enum.py", line 134, in infer_named_tuple
    ''' % {'name': name, 'fields': attributes, 'field_defs': field_defs})
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 156, in string_build
    module = self._data_build(data, modname, path)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 186, in _data_build
    source=data, modname=modname, path=path, error=exc))
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/util.py", line 30, in reraise
    six.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 182, in _data_build
    node = _parse(data + '\n')
  File "/home/degustaf/pylint/.tox/py36/lib/python3.6/site-packages/astroid/builder.py", line 41, in _parse
    return compile(string, "<string>", 'exec', _ast.PyCF_ONLY_AST)
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<string>, line 15)
```

### Expected behavior
No Traceback

### pylint --version output
pylint 1.7.0, 
astroid 1.5.0
Python 3.6.0 (default, Jan 22 2017, 14:12:05) 
[GCC 5.4.0 20160609]

This appears to be python 3.6 specific, and should be fixed for the 1.7 release.

**Comment by rogalski** [comment]
It's no Python 3.6 specific issue, it's just that namedtuple brain does not support `rename=True` (yet).

**Comment by degustaf** [comment]
@rogalski You're right.  But, it is a regression.  I am not getting the error when I use pylint from pypi.

pylint 1.6.5, 
astroid 1.4.9
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

**Comment by rogalski** [comment]
Oh, I remember that change... I"ll fix it during a weekend. Thanks for isolating a regression.

Wysłane z iPhone'a

Dnia 09.03.2017 o godz. 21:01 Derek Gustafson <notifications@github.com> napisał(a):
