### ISSUE TITLE
`AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'` after adding functools.lru_cache to project

### ISSUE THREAD

**Issue by carmenbianca** [PyCQA/pylint#1398]
So this is a bit of an odd one... After [a single commit](https://gitlab.com/carmenbianca/schaakmat/commit/1aa3d0330724efe5bce85d5a873c62926fe27f54), Pylint [broke down](https://gitlab.com/carmenbianca/schaakmat/builds/13047226). I don't see anything spectacularly outlandish in that commit, so I'm rather lost at identifying the true cause of this breakdown.

### Steps to reproduce
1. Introduce the following commit: https://gitlab.com/carmenbianca/schaakmat/commit/1aa3d0330724efe5bce85d5a873c62926fe27f54
2. Run Pylint (Python 3.6) on the code

### Current behavior

Pylint breaks down.

    pylint schaakmat tests/*.py
    Traceback (most recent call last):
      File "/builds/carmenbianca/schaakmat/.tox/lint/bin/pylint", line 11, in <module>
        sys.exit(run_pylint())
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/__init__.py", line 17, in run_pylint
        Run(sys.argv[1:])
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 1333, in __init__
        linter.check(args)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 755, in check
        self._do_check(files_or_modules)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 886, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 967, in check_astroid_module
        walker.walk(ast_node)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/utils.py", line 959, in walk
        self.walk(child)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/utils.py", line 956, in walk
        cb(astroid)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/checkers/imports.py", line 392, in visit_importfrom
        importedmodnode = self._get_imported_module(node, basename)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/pylint/checkers/imports.py", line 582, in _get_imported_module
        return importnode.do_import_module(modname)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/mixins.py", line 129, in do_import_module
        relative_only=level and level >= 1)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 492, in import_module
        return MANAGER.ast_from_module_name(absmodname)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/manager.py", line 136, in ast_from_module_name
        return self.ast_from_file(filepath, modname, fallback=False)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/manager.py", line 86, in ast_from_file
        return AstroidBuilder(self).file_build(filepath, modname)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/builder.py", line 141, in file_build
        module = self._data_build(data, modname, path)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/builder.py", line 185, in _data_build
        module = builder.visit_module(node, modname, node_file, package)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in visit_module
        newnode.body = [self.visit(child, newnode) for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in <listcomp>
        newnode.body = [self.visit(child, newnode) for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 957, in visit_classdef
        newnode = super(TreeRebuilder3k, self).visit_classdef(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in visit_classdef
        for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in <listcomp>
        for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 543, in visit_functiondef
        assign_ctx=assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in _visit_functiondef
        for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in <listcomp>
        for child in node.body]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 447, in visit_expr
        newnode.value = self.visit(node.value, newnode, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in visit_call
        for child in node.args]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in <listcomp>
        for child in node.args]
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
        return visit_method(node, parent, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 549, in visit_generatorexp
        newnode.elt = self.visit(node.elt, newnode, assign_ctx)
      File "/builds/carmenbianca/schaakmat/.tox/lint/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in visit
        visit_method = getattr(self, visit_name)
    AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'
    Makefile:50: recipe for target 'lint' failed
    make: *** [lint] Error 1
    ERROR: InvocationError: '/usr/bin/make lint'

### Expected behavior

Pylint doesn't crash

### pylint --version output

This is the output from my openSUSE Tumbleweed machine. The docker runner (python:latest) I linked to should have the same pylint & astroid versions, but a slightly different Python version (still Python 3.6 though). They both display the same bug.

    pylint 1.6.5,
    astroid 1.4.9
    Python 3.6.0 (default, Jan 16 2017, 13:50:53) [GCC]

Noteworthy is that the openSUSE Python 2.7 version of Pylint (python-pylint) does not crash.

Similarly, if I run Pylint in a Python 3.5 virtualenv, everything is fine, too. This only appears to happen in Python 3.6.

I'm sorry if this bug report isn't all too specific. I'd be happy to help if something isn't clear.

**Comment by carmenbianca** [comment]
Okay I did a tiny bit more research. Simply doing `from functools import lru_cache` is enough to cause this.

So steps to reproduce:

1. Create `foo.py` containing `from functools import lru_cache`.
2. Run `pylint foo.py`, using Python 3.6.

**Comment by PCManticore** [comment]
pylint doesn't yet support Python 3.6, only the master version. We're planning to release it in the wild this week.
