### ISSUE TITLE
Cannot install the latest sdist using "python setup.py install" in python 3

### ISSUE THREAD

**Issue by r-darwish** [PyCQA/pylint#1441]
### Steps to reproduce
1. `curl -L https://pypi.python.org/packages/cc/8c/d1da590769213fefedea4b345e90fce80f749c61ab9f9187b3fe19397b4b/pylint-1.7.1.tar.gz#md5=e6f4c22426df7c786551bcacaaa3f217 | tar xz`
2. `cd pylint-1.7.1`
3. `python setup.py install`

### Current behavior
```
Traceback (most recent call last):
  File "setup.py", line 173, in <module>
    install()
  File "setup.py", line 170, in install
    **kwargs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

### Expected behavior
Installation should succeed.

Note that this does not happen when trying to install pylint 1.7.1 from the git repository.

### pylint --version output
1.7.1

**Comment by thisch** [comment]
this also happens with the current git version.

**Comment by iciclespider** [comment]
This is caused by several .pyc files that were compiled with Python 2 being included in the source distribution.

**Comment by rogalski** [comment]
@PCManticore shouldn't all of *.pyc be blacklisted when we create packages for shipping to PyPi?

**Comment by PCManticore** [comment]
I they they already are, not sure how they got there. Also, it doesn't make sense to reproduce with the current git version, since we don't store pyc files there. Most likely it's from a manual install with a different Python vesion than a subsequent install.

**Comment by ewanmellor** [comment]
@PCManticore *.pyc files are not blacklisted if they appear under `pylint/test`.  MANIFEST.in has `graft pylint/test` as the final line, which includes all files including pyc files.

Whoever uploaded pylint-1.7.1 to PyPI presumably ran the tests and then made the distribution on an unclean source directory.

To test:

```
$ git clone https://github.com/PyCQA/pylint
$ cd pylint
$ touch pylint/__init__.pyc
$ touch pylint/test/extensions/__init__.pyc
$ make sdist
$ tar tf dist/pylint-*.tar.gz | grep pyc
pylint-1.8.0/pylint/test/extensions/__init__.pyc
```

**Comment by ayalash** [comment]
Is there any ETA?

**Comment by spatz** [comment]
Can a new sdist please be uploaded without the pyc files to fix this?

**Comment by PCManticore** [comment]
Sorry folks, can you please try now? We have 1.7.2 on pypi, let me know if you still have issues with this distribution.

**Comment by ayalash** [comment]
@PCManticore works, thanks

**Comment by Drake81** [comment]
@PCManticore works fine with Python 3.6 and 3.5, thanks
