### ISSUE TITLE
Crashes when bad encoding goes after docstring

### ISSUE THREAD

**Issue by proggga** [PyCQA/pylint#1442]
### Steps to reproduce
1. use version 2.7
2. in file first line should be docstring, second #coding with bad encoding
3. use pylint on this file

### Current behavior
No config file found, using default configuration
Traceback (most recent call last):
  File "/home/progga/.pyenv/versions/2.7.13/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 912, in check_astroid_module
    tokens = utils.tokenize_module(ast_node)
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 133, in tokenize_module
    return list(tokenize.generate_tokens(readline))
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/tokenize.py", line 311, in generate_tokens
    line = readline()
  File "/home/progga/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 123, in <lambda>
    return lambda: stream.readline().decode(encoding, 'replace')
LookupError: unknown encoding: utd-8

### Expected behavior
syntax-error on line with encoding

### pylint --version output
rsion output
No config file found, using default configuration
pylint 1.7.1, 
astroid 1.5.2
Python 2.7.13 (default, Feb 21 2017, 12:22:18) 
[GCC 6.3.1 20170109]

**Comment by proggga** [comment]
#1443

**Comment by proggga** [comment]
Fix in pull request #1443
