### ISSUE TITLE
pylint crash over json_util import from bson

### ISSUE THREAD

**Issue by pleasantone** [PyCQA/pylint#1458]
If I import a function/object called `json_util` from PyMongo's bson package, pylint craps out.
The internal pylint json_util should be protected from something like this.

This is a regression introduced sometime between 1.6.5 and 1.7.1

### Steps to reproduce

1. pip install pymongo (version 3.4.0)
2. echo "from bson import json_util" >test.py
3. pylint test.py (v1.7.1 or github master as of 2017-04-28) 

Works fine if I change it to simply `import bson` and change my code around.
[ **amended**: I spoke too soon, I re-coded my work and still triggered it with just bson ]

The following snippet will also trigger it:

```
#import sys
import bson
import json

def dump_dictionary(dictionary, stream=sys.stdout):
    """Send the dictionary (possibly a ChainMap) to stdout as a sorted hjson file"""
    json.dump(dictionary, stream, for_json=True, default=bson.json_util.default)
```

### Current behavior

```
Traceback (most recent call last):
  File "/srv/dev/lib/python3.5/site-packages/astroid/decorators.py", line 26, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.JSONOptions l.166 at 0x7fe745987518>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/dev/bin/pylint", line 11, in <module>
    load_entry_point('pylint==1.8.0', 'console_scripts', 'pylint')()
  File "/srv/dev/lib/python3.5/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/srv/dev/lib/python3.5/site-packages/pylint/lint.py", line 1308, in __init__
    linter.check(args)
  File "/srv/dev/lib/python3.5/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/srv/dev/lib/python3.5/site-packages/pylint/lint.py", line 863, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/srv/dev/lib/python3.5/site-packages/pylint/lint.py", line 942, in check_astroid_module
    walker.walk(ast_node)
  File "/srv/dev/lib/python3.5/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/srv/dev/lib/python3.5/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/srv/dev/lib/python3.5/site-packages/pylint/checkers/variables.py", line 1153, in visit_importfrom
    self._check_module_attrs(node, module, name.split('.'))
  File "/srv/dev/lib/python3.5/site-packages/pylint/checkers/variables.py", line 1217, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 345, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 409, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/srv/dev/lib/python3.5/site-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/srv/dev/lib/python3.5/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/srv/dev/lib/python3.5/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/srv/dev/lib/python3.5/site-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File "/srv/dev/lib/python3.5/site-packages/astroid/builder.py", line 238, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File "/srv/dev/lib/python3.5/site-packages/astroid/builder.py", line 81, in _can_assign_attr
    slots = node.slots()
  File "/srv/dev/lib/python3.5/site-packages/astroid/decorators.py", line 28, in cached
    cache[func] = result = func(*args, **kwargs)
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 1745, in slots
    slots = list(grouped_slots())
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 1730, in grouped_slots
    for cls in self.mro()[:-1]:
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 1823, in mro
    return self._compute_mro(context=context)
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 1808, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File "/srv/dev/lib/python3.5/site-packages/astroid/scoped_nodes.py", line 80, in _verify_duplicates_mro
    mros=sequences, cls=cls, context=context)
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (JSONOptions), (CodecOptions, CodecOptions, tuple, object), (CodecOptions) for <ClassDef.JSONOptions l.166 at 0x7fe745987518>.
```

### Expected behavior

Don't crash

### pylint --version output

pylint 1.8.0,
astroid 1.5.2
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118]

pymongo v3.4.0
Debian Stretch (current)

--- works fine with:
pylint 1.6.5,
astroid 1.4.9
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118]

**Comment by PCManticore** [comment]
A simpler reproduction case would be:

```
from collections import namedtuple
base = namedtuple("A", 'b')
class A(base):
   pass
class B(A):
   pass
print(B.__mro__)
```
Pylint assumes that the ``base`` class, which is in fact an ``A`` class, is the same as the second ``A``, even though they are not at a Python level.
