### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

### ISSUE THREAD

**Issue by dmtucker** [PyCQA/pylint#1459]
Tox is failing to run Pylint for Python 2.7.9:
```
py27 installed: appdirs==1.4.3,asn1crypto==0.22.0,astroid==1.5.2,backports.functools-lru-cache==1.3,cffi==1.10.0,conductor==0.5.2,configparser==3.5.0,coverage==4.3.4,cryptography==1.8.1,enum34==1.1.6,future==0.15.2,idna==2.5,ipaddress==1.0.18,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.6.1,packaging==16.8,paramiko==2.1.2,pep8==1.7.0,py==1.4.33,pyasn1==0.2.3,pycparser==2.17,pylint==1.7.1,pyonefs==0.3.0,pyparsing==2.2.0,pytest==3.0.7,pyvmomi==6.5,requests==2.13.0,singledispatch==3.4.0.3,six==1.10.0,wrapt==1.10.10
```
```
Traceback (most recent call last):
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/pylint/lint.py", line 1218, in __init__
    ), option_groups=self.option_groups, pylintrc=self._rcfile)
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/pylint/lint.py", line 434, in __init__
    config_file=pylintrc or config.PYLINTRC)
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/pylint/config.py", line 448, in __init__
    self.reset_parsers(usage, version=version)
  File "/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/pylint/config.py", line 462, in reset_parsers
    self.cfgfile_parser = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'
```

With 3.4.2, it works:
```
py34 installed: appdirs==1.4.3,asn1crypto==0.22.0,astroid==1.5.2,cffi==1.10.0,conductor==0.5.2,coverage==4.3.4,cryptography==1.8.1,future==0.15.2,idna==2.5,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.6.1,packaging==16.8,paramiko==2.1.2,pep8==1.7.0,py==1.4.33,pyasn1==0.2.3,pycparser==2.17,pylint==1.7.1,pyonefs==0.3.0,pyparsing==2.2.0,pytest==3.0.7,pyvmomi==6.5,requests==2.13.0,six==1.10.0,wrapt==1.10.10
```
```
Your code has been rated at 9.95/10 (previous run: 9.95/10, +0.00)
```
I have tried rebuilding my virtualenvs from scratch to no avail.

**Comment by rogalski** [comment]
Let's link do original issue: #1318 

What is the value of `import configparser; configparser.__file__` in both virtualenvs?

**Comment by dmtucker** [comment]
Interesting...

```
py27 runtests: commands[5] | python -c import configparser; print(configparser.__file__)
/media/dtucker/SSD/projects/conductor/.tox/py27/local/lib/python2.7/site-packages/configparser/__init__.pyc
py27 runtests: commands[6] | pip show configparser
Name: configparser
Version: 3.5.0
Summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
Home-page: http://docs.python.org/3/library/configparser.html
Author: Lukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: /media/dtucker/SSD/projects/conductor/.tox/py27/lib/python2.7/site-packages
Requires: 
```
```
py34 runtests: commands[5] | python -c import configparser; print(configparser.__file__)
/usr/lib/python3.4/configparser.py
py34 runtests: commands[6] | pip show configparser
ERROR: InvocationError: '/media/dtucker/SSD/projects/conductor/.tox/py34/bin/pip show configparser'
```

**Comment by rogalski** [comment]
Let's continue discussion in #1318.
