### ISSUE TITLE
pylint crashes for namedtuple

### ISSUE THREAD

**Issue by jllanfranchi** [PyCQA/pylint#1568]
### Steps to reproduce
Create `test.py` file with contents essentially copied from `namedtuple`'s docstring example
``` python
from __future__ import print_function
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])
p = Point(11, y=22)
print(p)
```

### Current behavior
Running the code works, but running pylint on it crashes pylint:
```
$ python test.py
Point(x=11, y=22)

$ pylint test.py
Process ChildLinter-2:
Traceback (most recent call last):
  File "/home/justin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 208, in run
    result = self._run_linter(file_or_module[0])
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 237, in _run_linter
    linter.check(file_or_module)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/checkers/base.py", line 1293, in visit_assignname
    if isinstance(utils.safe_infer(ass_type.value), astroid.ClassDef):
  File "/home/justin/anaconda2/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/pylint/checkers/utils.py", line 772, in safe_infer
    inferit = node.infer(context=context)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 239, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/astroid/brain/brain_stdlib.py", line 297, in infer_named_tuple
    context=context)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/astroid/brain/brain_stdlib.py", line 97, in infer_func_form
    class_node._instance_attrs[attr] = [fake_node]
AttributeError: 'ClassDef' object has no attribute '_instance_attrs'
```

### pylint --version output
```
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

**Comment by PCManticore** [comment]
Please check your installation, we don't have ``brain_stdlib.py`` in astroid for a while now.

**Comment by jllanfranchi** [comment]
Thank you for the help, that fixed the issue. It looks like the actual version of astroid being _used_ by pylint was astroid 1.4.9 (apparently the version installed via Anaconda) while the version installed by pip was astroid 1.5.3--but that one must not have actually been used by pylint, just reported by `pylint --version`.

Uninstalling all versions of pylint and astroid and re-installing fresh using `pip install pylint` fixed the above issue. (It is somewhat curious as to why `pylint --version` returned astroid 1.5.3, but if you don't think that's an issue in and of itself, it's not worth pursuing any further.) Thanks again!
