### ISSUE TITLE
IndexError: list index out of range with inline if in f-strings

### ISSUE THREAD

**Issue by jacquesd** [PyCQA/pylint#1597]
### Steps to reproduce
1.  Consider the following code:
     ```python
     def function(value):
         default = f'value={value if value else "default"}'
         if value is None:
             return 'None'
         elif value != 0:
             return default
     ```
2. Lint the code with pylint
    ```bash
    $ pylint code.py
    ************* Module code
    C:  1, 0: Missing module docstring (missing-docstring)
    C:  1, 0: Missing function docstring (missing-docstring)
    C:  4, 0: Missing function docstring (missing-docstring)
    Traceback (most recent call last):
      File "~/.virtualenvs/pylint_bug/bin/pylint", line 11, in <module>
        sys.exit(run_pylint())
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
        Run(sys.argv[1:])
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
        linter.check(args)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
        self._do_check(files_or_modules)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
        walker.walk(ast_node)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
        self.walk(child)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
        self.walk(child)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
        self.walk(child)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
        cb(astroid)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 302, in visit_if
        self._check_simplifiable_if(node)
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 161, in _check_simplifiable_if
        if self._is_actual_elif(node):
      File "~/.virtualenvs/pylint_bug/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 147, in _is_actual_elif
        if self._elifs[self._if_counter]:
    IndexError: list index out of range
    ```

### Current behavior
Linting fails when visiting the `if-elif` node of the `function`.

### Expected behavior
Linting shoudn't fail.

### Observations
- I am not really sure what exactly happens, but it appears that when checking if the `elif value != 0` is an `if` or `elif`, `self._elifs` doesn't have the inline if from the format string while `self._if_counter` counted the inline if.
- A single f-string containing an inline if is parsed correctly.
- If the f-string must be outside the if-elif to trigger the error.  If it is within the if-elif, it is parsed correctly.
- A simple if-else block is parsed correctly as well (even with the f-string outside), the `elif` block is required to reproduce the error.

### pylint --version output
```bash
pylint 1.7.2,
astroid 1.5.3
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by rogalski** [comment]
Could you check whether it reproduces on master (with a53028d)?

**Comment by jacquesd** [comment]
Awesome, it appears to be working.

### Output
```bash
$ pylint -rn code.py
No config file found, using default configuration
************* Module code
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing function docstring (missing-docstring)

------------------------------------------------------------------
Your code has been rated at 6.67/10 (previous run: 6.67/10, +0.00)

```
### pylint --version output
```bash
No config file found, using default configuration
pylint 1.8.0,
astroid 1.5.3
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
> It's exactly a53028d, I installed pylint with:
> ```bash
> pip install git+git://github.com/PyCQA/pylint.git@a53028da4f370e0ac94f4b11d74bdd2da2f1f610
> ```

Thanks a lot!
