### ISSUE TITLE
PuLP causes pylint to crash

### ISSUE THREAD

**Issue by eldadr** [PyCQA/pylint#1604]
### Steps to reproduce
1. Import pulp (https://pypi.python.org/pypi/PuLP) in your Python source code.
2. Run pylint.

### Current behavior
Pylint crashes.
```
$ pip freeze | grep -i pulp
PuLP==1.6.8
$ echo "import pulp; print('hello world')" > try.py
$ python try.py 
hello world

$ pylint try.py 
No config file found, using default configuration
************* Module try
C:  1, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:  1, 0: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python2.7/dist-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/variables.py", line 1129, in visit_import
    module = next(node.infer_name_module(parts[0]))
  File "/usr/local/lib/python2.7/dist-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python2.7/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python2.7/dist-packages/astroid/inference.py", line 193, in infer_import
    yield self.do_import_module(name)
  File "/usr/local/lib/python2.7/dist-packages/astroid/mixins.py", line 119, in do_import_module
    relative_only=level and level >= 1)
  File "/usr/local/lib/python2.7/dist-packages/astroid/scoped_nodes.py", line 415, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "/usr/local/lib/python2.7/dist-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/usr/local/lib/python2.7/dist-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 169, in _post_build
    self.add_from_names_to_locals(from_node)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 214, in add_from_names_to_locals
    imported = node.do_import_module()
  File "/usr/local/lib/python2.7/dist-packages/astroid/mixins.py", line 119, in do_import_module
    relative_only=level and level >= 1)
  File "/usr/local/lib/python2.7/dist-packages/astroid/scoped_nodes.py", line 409, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/lib/python2.7/dist-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/usr/local/lib/python2.7/dist-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File "/usr/local/lib/python2.7/dist-packages/astroid/builder.py", line 231, in delayed_assattr
    for inferred in node.expr.infer():
  File "/usr/local/lib/python2.7/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python2.7/dist-packages/astroid/bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python2.7/dist-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python2.7/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python2.7/dist-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python2.7/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python2.7/dist-packages/astroid/inference.py", line 409, in _filter_operation_errors
    for result in infer_callable(self, context):
  File "/usr/local/lib/python2.7/dist-packages/astroid/inference.py", line 732, in _infer_augassign
    for result in results:
  File "/usr/local/lib/python2.7/dist-packages/astroid/inference.py", line 625, in _infer_binary_operation
    context, reverse_context)
  File "/usr/local/lib/python2.7/dist-packages/astroid/inference.py", line 600, in _get_aug_flow
    elif helpers.is_subtype(left_type, right_type):
  File "/usr/local/lib/python2.7/dist-packages/astroid/helpers.py", line 145, in is_subtype
    return _type_check(type2, type1)
  File "/usr/local/lib/python2.7/dist-packages/astroid/helpers.py", line 132, in _type_check
    raise exceptions._NonDeducibleTypeHierarchy
astroid.exceptions._NonDeducibleTypeHierarchy
```

### Expected behavior
Pylint should not crash.

### pylint --version output
```
$ pylint --version
No config file found, using default configuration
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
```

**Comment by eldadr** [comment]
I created a small code example in which the bug reproduces without importing the whole PuLP package:

```
import sys

_DICT_TYPE = dict

if sys.platform not in ['cli']:
    # iron python does not like an OrderedDict
    try:
        from odict import OrderedDict
        _DICT_TYPE = OrderedDict
    except ImportError:
        pass
    try:
        #python 2.7 or 3.1
        from collections import OrderedDict
        _DICT_TYPE = OrderedDict
    except ImportError:
        pass

class A(_DICT_TYPE):
    pass

class B(object):
    
    def __init__(self):

        self.x = 1
        self += A()
        self += self.x
        
    def __add__(self, other):
        return self

A()
B()
```

**Comment by PCManticore** [comment]
Thanks @eldadr It seems though this is in fixed in the master branch of pylint and astroid. Can you give it a try and let me know if it works for you as well?

**Comment by eldadr** [comment]
Yes, when I install pylint and astroid from github instead of pip it seems to work. Thanks!

**Comment by nirizr** [comment]
Is it too soon to ask about an estimated date for a release addressing this?
I rather put off a PR instead of moving to git-based sources.

**Comment by PCManticore** [comment]
There is no estimated date for this release.
