### ISSUE TITLE
Crash in astroid

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/pylint#1619]
### Steps to reproduce
pylint crashed on me on a fairly complex non-open-source project. I can try to minimize the test case but haven't had time yet. Is the stack trace below enough to figure out what is wrong?

(For my reference: to reproduce go to commit 4c3630e and run `pylint container/csv_container_list.py`.)

### Current behavior

```
Traceback (most recent call last):
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 794, in visit_call
    call_site = astroid.arguments.CallSite.from_call(node)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/astroid/arguments.py", line 49, in from_call
    return cls(callcontext)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/astroid/arguments.py", line 33, in __init__
    self._unpacked_kwargs = self._unpack_keywords(keywords)
  File "/Users/jzijlstra-mpbt/py/ehphp/pycatalog/.venv/lib/python3.6/site-packages/astroid/arguments.py", line 90, in _unpack_keywords
    dict_key = next(dict_key.infer(context=context))
TypeError: 'Uninferable' object is not an iterator
```

### Expected behavior
Don't crash please.

### pylint --version output

```
t$ pylint --version
pylint 1.7.2, 
astroid 1.5.3
Python 3.6.1 (default, Apr 24 2017, 06:18:27) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by PCManticore** [comment]
@JelleZijlstra Thanks for reporting this issue! Can you let me know if this commit fixes the problem for you?

**Comment by JelleZijlstra** [comment]
Thanks for the quick fix! Your change does fix my crash.

**Comment by JelleZijlstra** [comment]
Although updating to astroid master gave me a new issue where pylint emits `Unused variable '__class__' (unused-variable)` for almost every method.

**Comment by rogalski** [comment]
@JelleZijlstra you need to switch to 210a9ad8f19cd34d245a64bbc32019b1b53e742d or later
