### ISSUE TITLE
Pylint fails with "Duplicates found in MROs"

### ISSUE THREAD

**Issue by nolar** [PyCQA/pylint#1706]
**NB:** There are already similar bugs #1458, #1607, but they are marked as fixed & released. My issue happens with the fixed version already installed, but the bug reappears (probably for a different reason).

----

### Problem

Pylint fails with an exception (i.e. not an E-/W-message, but literally fails) when linting a file.

I've extracted the minified version of the source code needed to reproduce the problem, and renamed some classes: https://github.com/nolar/pylint-bug-example (also attached as an archive: [pylint-bug-example-master.zip](https://github.com/PyCQA/pylint/files/1394123/pylint-bug-example-master.zip)).

Some observations:

* If you uncomment the `self.name = 'x'` line, the problem disappears _(the most hilarious thing)_.
* If you convert `aspects` package into `aspects.py` module, the problem disappears (`objects` package-to-module conversion has no such effect).
* If you rename `objects` package to something else, the problem disappears.
* If you change the hierarchy of classes, the problem disappears.
* Generally, if you change things in this minified source code, the problem disappears.

### Steps to reproduce
1. Create & activate a new clean virtualenv.
2. Install pylint only.
3. Clone the minified code repo or unpack the attached archive.
3. Run `pylint vserver.py`

### Current behavior

```
$ pylint vserver.py 
No config file found, using default configuration
Traceback (most recent call last):
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/decorators.py", line 26, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.FinalClass l.4 at 0x10ce42240>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/pylint/lint.py", line 898, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/builder.py", line 238, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/builder.py", line 81, in _can_assign_attr
    slots = node.slots()
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/decorators.py", line 28, in cached
    cache[func] = result = func(*args, **kwargs)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1745, in slots
    slots = list(grouped_slots())
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1730, in grouped_slots
    for cls in self.mro()[:-1]:
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1823, in mro
    return self._compute_mro(context=context)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1808, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File ".../pylint-bug/.venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 80, in _verify_duplicates_mro
    mros=sequences, cls=cls, context=context)
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (FinalClass), (ClassB, MixinB, , ClassA, MixinA, , Base, object), (ClassB) for <ClassDef.FinalClass l.4 at 0x10ce42240>.
************* Module vserver
F:  1, 0: <class 'astroid.exceptions.DuplicateBasesError'>: Duplicates found in MROs (FinalClass), (ClassB, MixinB, , ClassA, MixinA, , Base, object), (ClassB) for <ClassDef.FinalClass l.4 at 0x10ce42240>. (astroid-error)
```

**Notice the empty base classes in the MRO. When you do `FinalClass.mro()`, it returns a normal list with `intMixin` & `strMixin` in these places.**

### Expected behavior

Pylint works normally and maybe complains about the code issues.

### Versions

```
$ python --version
Python 3.6.1

$ virtualenv --version
15.1.0

$ pip freeze
astroid==1.5.3
isort==4.2.15
lazy-object-proxy==1.3.1
mccabe==0.6.1
pylint==1.7.4
six==1.11.0
wrapt==1.10.11

$ pylint --version
No config file found, using default configuration
pylint 1.7.4, 
astroid 1.5.3
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

**Comment by rogalski** [comment]
Thank your for submitting a bug and for excellent reproduction steps.

**Comment by PCManticore** [comment]
This should work now with master and the future 1.8.
