### ISSUE TITLE
Crash on bad raise (or something like that)

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#1773]
### Steps to reproduce
In a file called `pylint_test.py` put
```
class BlargException(Exception):
    pass


def blarg():
    try:
        if False:
            raise BlargException()
        return 5
    except BlargException:
        raise
```
Then run `pylint pylint_test.py`, and it blows up with a big stack trace.

I don't know exactly what triggers it, but every element there is apparently needed in some way.

For example, changing the `5` to something else (including `None`) still crashes, but a bare `return` with no return value does not.

For another example, changing the bare `raise` to `raise 5` does not crash (and raises the appropriate `raising-bad-type` pylint error).

### Current behavior
```
$ pylint pylint_test.py
No config file found, using default configuration
************* Module pylint_test
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing class docstring (missing-docstring)
C:  4, 0: Missing function docstring (missing-docstring)
W:  6, 8: Using a conditional statement with a constant value (using-constant-test)
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1016, in walk
    cb(astroid)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 357, in leave_functiondef
    self._check_consistent_returns(node)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 560, in _check_consistent_returns
    and _is_node_return_ended(node)):
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 69, in _is_node_return_ended
    return_stmts = [_is_node_return_ended(_child) for _child in node.get_children()]
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 69, in <listcomp>
    return_stmts = [_is_node_return_ended(_child) for _child in node.get_children()]
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 63, in _is_node_return_ended
    return any(_is_node_return_ended(_handler) for _handler in handlers)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 63, in <genexpr>
    return any(_is_node_return_ended(_handler) for _handler in handlers)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 55, in _is_node_return_ended
    exc = utils.safe_infer(node.exc)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/utils.py", line 806, in safe_infer
    inferit = node.infer(context=context)
AttributeError: 'NoneType' object has no attribute 'infer'
```

### Expected behavior
Normal pylint output

### pylint --version output
```
$ pylint --version
No config file found, using default configuration
pylint 1.8.1, 
astroid 1.5.1
Python 3.6.0 (default, Mar 15 2017, 15:29:52) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by Kub-AT** [comment]
+1, Same here: AttributeError: 'NoneType' object has no attribute 'infer'

> Executing django_jenkins.tasks.run_pylint...
Traceback (most recent call last):
  File "./src/start.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_jenkins/management/commands/jenkins.py", line 116, in handle
    coverage.save(tested_locations, options)
  File "/usr/local/lib/python2.7/dist-packages/django_jenkins/tasks/run_pylint.py", line 44, in run
    lint.Run(args, reporter=ParseableTextReporter(output=output), exit=False)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 1016, in walk
    cb(astroid)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 357, in leave_functiondef
    self._check_consistent_returns(node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 560, in _check_consistent_returns
    and _is_node_return_ended(node)):
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 69, in _is_node_return_ended
    return_stmts = [_is_node_return_ended(_child) for _child in node.get_children()]
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/refactoring.py", line 55, in _is_node_return_ended
    exc = utils.safe_infer(node.exc)
  File "/usr/local/lib/python2.7/dist-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/utils.py", line 806, in safe_infer
    inferit = node.infer(context=context)
AttributeError: 'NoneType' object has no attribute 'infer'

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by hippo91** [comment]
Thank you @PCManticore. I missed this check...
