### ISSUE TITLE
AttributeError: 'ImportFrom' object has no attribute 'name'

### ISSUE THREAD

**Issue by jwkvam** [PyCQA/pylint#1774]
### Steps to reproduce
1. Create file:
```
from os import makedirs
def makedirs():
    pass
```
2. Run `pylint newfile.py`

### Current behavior

```
Traceback (most recent call last):
  File "/Users/jacques/miniconda/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/checkers/base.py", line 505, in visit_functiondef
    self._check_redefinition(node.is_method() and 'method' or 'function', node)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/pylint/checkers/base.py", line 717, in _check_redefinition
    if dummy_variables_rgx and dummy_variables_rgx.match(defined_self.name):
AttributeError: 'ImportFrom' object has no attribute 'name'
```

### Expected behavior
No exception

### pylint --version output
```
No config file found, using default configuration
pylint 1.8.1,
astroid 1.6.0
Python 3.6.3 | packaged by conda-forge | (default, Dec  9 2017, 16:20:51)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

### Extra

Seems like https://github.com/PyCQA/pylint/pull/1665 might be the source of this. Maybe the line just needs to be:
```
if dummy_variables_rgx and dummy_variables_rgx.match(defined_self.names[0][0]):
```

**Comment by Kub-AT** [comment]
+1 Same here, problem with ImportForm and name attribute

> File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/utils.py", line 806, in safe_infer
     inferit = node.infer(context=context)
AttributeError: 'NoneType' object has no attribute 'infer'

**Comment by paternal** [comment]
Same thing here. I was going to open the very same issue. My MWE was:

~~~py
from argparse import ArgumentParser
class ArgumentParser:
    pass
~~~

Given the original message of this thread, I think that the bug arises when one redefines an existing function/class.

Good luck! 🙂

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by ransom4real** [comment]
@PCManticore is this currently in the 1.8.1 version?

**Comment by jwkvam** [comment]
@ransom4real it's not in any released versions, you'll need to use 1.8 or master branches I believe. I'm using the 1.8 branch myself.

**Comment by rmathot** [comment]
Do you know when it will be released in a next version? (thanks for the work anyway!)

**Comment by PCManticore** [comment]
When I'll have time. Unfortunately I'm a bit busy at the moment, but hopefully I'll find some time in the weekend for a new release

**Comment by rmathot** [comment]
@PCManticore ok thank you :)
