### ISSUE TITLE
TypeError: 'Uninferable' object is not iterable

### ISSUE THREAD

**Issue by jabdoa2** [PyCQA/pylint#1779]
### Steps to reproduce
Simplified example. Function needs those two lines (which make more sense in the original code):
```
"""Will crash pylint on python 3.6."""
import asyncio


def crash(futures):
    """Crash pylint."""
    yield from asyncio.wait(futures)
    raise asyncio.TimeoutError()

```
### Current behavior
Pylint 1.8.1 will crash on Python 3.6. This works on Python 3.4 and 3.5.
```
# pylint test.py 
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.6/dist-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.6/dist-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/dist-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/dist-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/usr/local/lib/python3.6/dist-packages/pylint/checkers/refactoring.py", line 362, in visit_raise
    self._check_stop_iteration_inside_generator(node)
  File "/usr/local/lib/python3.6/dist-packages/pylint/checkers/refactoring.py", line 374, in _check_stop_iteration_inside_generator
    if exc is not None and self._check_exception_inherit_from_stopiteration(exc):
  File "/usr/local/lib/python3.6/dist-packages/pylint/checkers/refactoring.py", line 381, in _check_exception_inherit_from_stopiteration
    return any(_class.qname() == stopiteration_qname for _class in exc.mro())
TypeError: 'Uninferable' object is not iterable
```
Reproduced on Ubuntu 17.10 and debian experimental. Works in Ubuntu 14.04, 16.04 and debian jessie.

### Expected behavior
No crash

### pylint --version output
```
# pylint --version
No config file found, using default configuration
pylint 1.8.1, 
astroid 1.6.0
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by m-vdb** [comment]
@PCManticore can we expect a release on pypi soon? It also bugs for simple context managers:
```python
@contextmanager
def catch_integrity_error_and_raise(exception_class):
    with transaction.atomic():
        try:
            yield
        except IntegrityError as exc:
            raise exception_class(str(exc))
```
Thanks!

**Comment by m-vdb** [comment]
@PCManticore do you think you could release `1.8.2` on pypi soon?
