### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'infer'

### ISSUE THREAD

**Issue by sscherfke** [PyCQA/pylint#1817]
### Steps to reproduce
1. `vim /tmp/wtf.py`:
    ```python
    def wtf():
        try:
            if len(''):
                raise ValueError('NaN is not NaN!!!')
        except ValueError:
            raise

        return ()  # Return anything but "None"
    ```
2.  `pylint /tmp/wtf.py`

### Current behavior
```
No config file found, using default configuration
************* Module wtf
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing function docstring (missing-docstring)
C:  3,11: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
Traceback (most recent call last):
  File "/localhome/stefan/emsconda//bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/utils.py", line 1016, in walk
    cb(astroid)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 357, in leave_functiondef
    self._check_consistent_returns(node)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 560, in _check_consistent_returns
    and _is_node_return_ended(node)):
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 69, in _is_node_return_ended
    return_stmts = [_is_node_return_ended(_child) for _child in node.get_children()]
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 69, in <listcomp>
    return_stmts = [_is_node_return_ended(_child) for _child in node.get_children()]
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 63, in _is_node_return_ended
    return any(_is_node_return_ended(_handler) for _handler in handlers)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 63, in <genexpr>
    return any(_is_node_return_ended(_handler) for _handler in handlers)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 73, in _is_node_return_ended
    return any(_is_node_return_ended(_child) for _child in node.get_children()
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 74, in <genexpr>
    if not isinstance(_child, astroid.ExceptHandler))
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 55, in _is_node_return_ended
    exc = utils.safe_infer(node.exc)
  File "/localhome/stefan/emsconda//lib/python3.6/site-packages/pylint/checkers/utils.py", line 806, in safe_infer
    inferit = node.infer(context=context)
AttributeError: 'NoneType' object has no attribute 'infer'
```

### Expected behavior
```
No config file found, using default configuration
************* Module wtf
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing function docstring (missing-docstring)
C:  3,11: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)

------------------------------------------------------------------
Your code has been rated at 5.71/10 (previous run: 5.71/10, +0.00)
```

### pylint --version output
```
No config file found, using default configuration
pylint 1.8.1,
astroid 1.6.0
Python 3.6.4 | emsys distribution | (default, Jan  2 2018, 07:23:37)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by hippo91** [comment]
Thanks for this issue.
It is the same as #1773.
Thanks to @PCManticore, this should be solve by commit ``Don't crash when encountering bare raises while checking inconsistent… `` 97427560627562923f88d07c06593d18f096854b.
I'm closing it.

**Comment by sscherfke** [comment]
Cool. Looks like I searched for the wrong keywords. :-)
