### ISSUE TITLE
pylint crashing with `'AssignAttr' object has no attribute 'name'`

### ISSUE THREAD

**Issue by ryantam626** [PyCQA/pylint#1818]
### Steps to reproduce
1. In a Python 3.6 venv
2. git clone https://github.com/ryantam626/pylint-bug
3. cd pylint-bug
4. pylint this_fails.py a_module.py

### Current behavior
pylint crashes with `'AssignAttr' object has no attribute 'name'`.

### Expected behavior
pylint not crashing and emit `function-redefined`.

### pylint --version output
```
No config file found, using default configuration
pylint 1.8.1, 
astroid 1.6.0
Python 3.6.2 (default, Jul 20 2017, 08:43:29) 
[GCC 5.4.1 20170519]
```

**Comment by PCManticore** [comment]
Fixed in master branch: https://github.com/PyCQA/pylint/commit/dbb2f3e65b9a452cf981e1bda318ec019b43bd8c

**Comment by nedbat** [comment]
Any chance of getting this fix in 1.9.x?

**Comment by nedbat** [comment]
Oh, sorry, this fix is already in 1.9.x, I misread the error.  I'm getting `AttributeError: 'AssignAttr' object has no attribute 'qname'`, which is qname, not name.

**Comment by PCManticore** [comment]
Hey @nedbat are you still getting that `AttributeError`? if so, would you mind creating an issue with the reproduction example?

**Comment by nedbat** [comment]
@PCManticore I've reported it against pylint-django: https://github.com/PyCQA/pylint-django/issues/105.  The issue doesn't happen if I don't install pylint-django.

**Comment by DylanYoung** [comment]
I'm getting this error on 1.9.5.  How can I get more info an where exactly pylint is choking, at least the filename?  I can't find a verbosity or debug flag...

**Comment by DylanYoung** [comment]
Here's a minimal failing example:

```
import os
import subprocess

try:
    with open(os.devnull, 'w') as devnull:
        subprocess.check_call(
            ["wkhtmltopdf", "--help"],
            stdout=devnull,
            stderr=devnull,
    )
except OSError, subprocess.CalledProcessError:
    print "Not installed"
```

**Comment by DylanYoung** [comment]
Just realized that you probably need the traceback too:

```
Traceback (most recent call last):
  File "/Users/caseymeijer/envs/iris/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/lint.py", line 1353, in __init__
    linter.check(args)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/lint.py", line 774, in check
    self._do_check(files_or_modules)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/lint.py", line 907, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/lint.py", line 986, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/checkers/python3.py", line 967, in visit_excepthandler
    assign_name.lineno
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/pylint/checkers/python3.py", line 973, in <setcomp>
    if assign_name.name == node.name.name
AttributeError: 'AssignAttr' object has no attribute 'name'
```

**Comment by DylanYoung** [comment]
I'll see if this is reproducible on latest when I get a chance :)

**Comment by PCManticore** [comment]
@DylanYoung This doesn't seem to reproduce with latest pylint 2.X. I presume the bug still exist in 1.9.X, but that release line is no longer maintained.

**Comment by DylanYoung** [comment]
Thanks for checking. Glad it's fixed :)

**Comment by redsk** [comment]
Python 3.7, pylint 2.7.1, astroid 2.5.0:

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1030, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/manager.py", line 100, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/builder.py", line 139, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/builder.py", line 163, in _post_build
    module = self._manager.visit_transforms(module)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/manager.py", line 77, in visit_transforms
    return self._transform.visit(node)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/transforms.py", line 89, in visit
    module.body = [self._visit(child) for child in module.body]
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/transforms.py", line 89, in <listcomp>
    module.body = [self._visit(child) for child in module.body]
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/transforms.py", line 57, in _visit
    return self._transform(node)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/transforms.py", line 40, in _transform
    ret = transform_func(node)
  File "/usr/local/var/pyenv/versions/jaumo375/lib/python3.7/site-packages/astroid/brain/brain_dataclasses.py", line 44, in dataclass_transform
    node.instance_attrs[target.name] = [rhs_node]
AttributeError: 'AssignAttr' object has no attribute 'name'
************* Module colored_json
colored_json.py:1:0: F0002: <class 'AttributeError'>: 'AssignAttr' object has no attribute 'name' (astroid-error)
```

**Comment by hippo91** [comment]
@redsk thanks for the update.
Can you give us a snippet so that we can start debugging?
