### ISSUE TITLE
epylint not able to parse a .pylintrc file in a subdirectory on Windows

### ISSUE THREAD

**Issue by thernstig** [PyCQA/pylint#1940]
### Steps to reproduce
1. Add this to a file called test.py
```python
''' Script to lint all code e.g. python '''
import os
from pylint import epylint

def lint_pylint():
    ''' Lint all python code with pylint '''
    pylintrc = os.path.join("afolder", ".pylintrc")
    epylint.py_run(f'afolder -j 0 --rcfile={pylintrc}')

if __name__ == "__main__":
    lint_pylint()
```
2. Add a .pylintrc in a directory like: afolder/.pylintrc
3. Run test.py

### Current behavior
It cannot handle .pylintrc files on Windows not in the same folder as the command being run. You thus get an error like:
```python
(venv) ~\Desktop\projects\test [master]> python .\test.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Moo\Desktop\projects\test\venv\lib\site-packages\pylint\lint.py", line 1301, in __init__
    linter.read_config_file()
  File "C:\Users\Moo\Desktop\projects\test\venv\lib\site-packages\pylint\config.py", line 646, in read_config_file
    raise IOError("The config file {:s} doesn't exist!".format(config_file))
OSError: The config file afolder.pylintrc doesn't exist!
```

### Expected behavior
For it to work. The problem can be found in how shlex.split is invoked on Windows. The line here https://github.com/PyCQA/pylint/blob/9dd978aaed0daf852d8caed515b9e4e13f2dfcc7/pylint/epylint.py#L142 could be changed to:
```python
options = shlex.split(command_options, posix='win' not in sys.platform)
```

### pylint --version output
```powershell
(venv) ~\Desktop\projects\test [master]> pylint --version
No config file found, using default configuration
pylint 1.8.2,
astroid 1.6.1
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)
```

**Comment by thernstig** [comment]
I will have a merge request incoming any second.
