### ISSUE TITLE
unhandled AttributeError: 'AssignAttr' object has no attribute 'name' 

### ISSUE THREAD

**Issue by gvoysey** [PyCQA/pylint#2055]
### Steps to reproduce
1. touch the following file, `foo.py`:   `attr == 17.4.0`
```
import attr
import bar # a hypothetical package

@attr.s
class Foo:
    temp = bar.MakeAThing()
    temp.prop = 5

    bar_thing = attr.ib(default=temp)

```
2.  run `pylint foo.py`

### Current behavior
Pylint crashes with an unhandled `AttributeError`
```
Traceback (most recent call last):
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/pylint/lint.py", line 942, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/builder.py", line 153, in file_build
    return self._post_build(module, encoding)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/builder.py", line 177, in _post_build
    module = self._manager.visit_transforms(module)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/manager.py", line 62, in visit_transforms
    return self._transform.visit(node)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/transforms.py", line 83, in visit
    module.body = [self._visit(child) for child in module.body]
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/transforms.py", line 83, in <listcomp>
    module.body = [self._visit(child) for child in module.body]
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/transforms.py", line 53, in _visit
    return self._transform(node)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/transforms.py", line 36, in _transform
    ret = transform_func(node)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/astroid/brain/brain_attrs.py", line 50, in attr_attributes_transform
    node.locals[target.name] = [rhs_node]
AttributeError: 'AssignAttr' object has no attribute 'name'
```

### Expected behavior
Pylint shames my poor development practices and praises my good development practices where needed.

### pylint --version output
```
pylint 1.8.4,
astroid 1.6.3
Python 3.6.3 (default, Nov 23 2017, 15:11:19)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by PCManticore** [comment]
Thanks @gvoysey ! This one is fixed in astroid's master as well as in astroid's 1.6 branch. It will be available on the next bug fix release of astroid.
