### ISSUE TITLE
TypeError: 'Uninferable' object is not iterable

### ISSUE THREAD

**Issue by nschloe** [PyCQA/pylint#2059]
When running
```
pylint test/*.py
```
on [this project](https://github.com/nschloe/quadpy) I'm getting
```
TypeError: 'Uninferable' object is not iterable
```

**Comment by PCManticore** [comment]
Hey @nschloe Thanks for creating an issue! I tried reproducing this one by cloning your repo and running pylint over it, but it didn't crash. So I was wondering what Python version you used, what pylint and astroid version you used and if you had additional pylint plugins that you used for linting.

**Comment by nschloe** [comment]
> but it didn't crash

Thanks for trying to reproduce! Perhaps an issue on my side then. I'm running Python 3.6. I have a nonempty `.pylintrc`, but the issue appears regardless of what's in there. (Just tested that.) No additional plugins used. Version:
```
$ pylint --version
Using config file /home/nschloe/rcs/quadpy/.pylintrc
pylint 1.8.4, 
astroid 1.6.3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
```

**Comment by PCManticore** [comment]
This is weird! With the same versions as you and with Python 3.6.5 all I'm getting is:
```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```
Did you run pylint on a different branch or disabled some message in the master branch after `pylint` failed for you?

**Comment by selpoG** [comment]
The same issue occurs in following case.
Let `a.py` be
```python:a.py
import mpmath
dummy = 3 - 2 * mpmath.sqrt(2)
```
and `b.py`
```python:b.py
from a import dummy
```
, then `pylint b.py` fails as follows:
```
No config file found, using default configuration
************* Module b
C:  2, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/checkers/variables.py", line 1269, in visit_importfrom
    self._check_module_attrs(node, module, name.split('.'))
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/pylint/checkers/variables.py", line 1333, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 89, in wrapped
    res = next(generator)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/context.py", line 71, in cache_generator
    for result in generator:
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 112, in yes_if_nothing_inferred
    for node in func(*args, **kwargs):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 89, in wrapped
    res = next(generator)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/inference.py", line 410, in _filter_operation_errors
    for result in infer_callable(self, context):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/inference.py", line 681, in _infer_binop
    for rhs in right.infer(context=rhs_context):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/context.py", line 71, in cache_generator
    for result in generator:
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 112, in yes_if_nothing_inferred
    for node in func(*args, **kwargs):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 89, in wrapped
    res = next(generator)
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/inference.py", line 410, in _filter_operation_errors
    for result in infer_callable(self, context):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/inference.py", line 689, in _infer_binop
    context, _get_binop_flow):
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/inference.py", line 629, in _infer_binary_operation
    results = list(method())
  File "/home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages/astroid/decorators.py", line 112, in yes_if_nothing_inferred
    for node in func(*args, **kwargs):
TypeError: 'Uninferable' object is not iterable
```
My ennvironment:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

$ pylint --version
No config file found, using default configuration
pylint 1.9.1, 
astroid 1.6.4
Python 2.7.14 (default, Apr  8 2018, 23:18:40) 
[GCC 5.4.0 20160609]

$ pip show mpmath
Name: mpmath
Version: 1.0.0
Summary: Python library for arbitrary-precision floating-point arithmetic
Home-page: http://mpmath.org
Author: Fredrik Johansson
Author-email: fredrik.johansson@gmail.com
License: BSD
Location: /home/user_name/tmp/pyenv/versions/2.7.14/lib/python2.7/site-packages
Requires: 
Required-by: sympy
```
