### ISSUE TITLE
AttributeError: 'Raise' object has no attribute 'inst'

### ISSUE THREAD

**Issue by redbass** [PyCQA/pylint#2107]
### Steps to reproduce
1. Create a python file called `test.py` with content:
```
def foo():
    raise Exception()
```
2. run
```
pip install pylint==1.9
pylint --py3k  test.py
```

### Current behavior
```
No config file found, using default configuration
Traceback (most recent call last):
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/Users/myuser/.virtualenvs/tmp-4a92beb992e59df/lib/python3.6/site-packages/pylint/checkers/python3.py", line 921, in visit_raise
    node.inst is not None):
AttributeError: 'Raise' object has no attribute 'inst'
```

### Expected behavior
No error raised

### pylint --version output
```
No config file found, using default configuration
pylint 1.9.0, 
astroid 1.6.4
Python 3.6.4 (default, Mar  1 2018, 18:36:50) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by PCManticore** [comment]
Thanks! It's fixed in the 1.9 branch, we'll release shortly a new patch release.
