### ISSUE TITLE
1.9.0 is seriously broken

### ISSUE THREAD

**Issue by eccles** [PyCQA/pylint#2109]
### Steps to reproduce
1. Upgrade pylint from 1.8.4 to 1.9.0
2. Rerun pylint which previously passed with no error in v1.8.4
3. python3 -m pylint --rcfile=pylintrc ./setup.py lnxproc functests unittests

(from my repo eccles/lnxproc.git

### Current behavior
1. Using config file /usr/src/app/pylintrc
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/usr/local/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/usr/local/lib/python3.6/site-packages/pylint/checkers/python3.py", line 921, in visit_raise
    node.inst is not None):
AttributeError: 'Raise' object has no attribute 'inst'
************* Module setup
W:  6, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc
W:  4, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.resources
W:  5, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
W:100,16: dict.items referenced when not iterating (dict-items-not-iterating)
W:101,16: dict.items referenced when not iterating (dict-items-not-iterating)
W:179,16: dict.keys referenced when not iterating (dict-keys-not-iterating)
W:180,16: dict.keys referenced when not iterating (dict-keys-not-iterating)
************* Module lnxproc.entry
W:  8, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.pidenviron
W:  7, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.cpuinfo
W: 41, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.uptime
W:  9, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.pidschedstat
W: 10, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.pidio
W: 15, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.pidsmaps
W: 21, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.meminfo
W: 54, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.netarp
W: 13, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.netrpcnfsd
W: 21, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.stat
W:123, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.rest
W:  4, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.pidstat
W: 99, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.schedstat
W:114, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module lnxproc.readfile
W:  7, 0: import missing `from __future__ import absolute_import` (no-absolute-import)
make: *** [Makefile:57: _check_local] Error 1
Makefile:61: recipe for target 'check' failed
make: *** [check] Error 2

### Expected behavior
Run without raisng an exception and without raising any warnings/errors except new ones introduced in 1.9.0

### pylint --version output
1.9.0

**Comment by eccles** [comment]
The exception is fixed but the spurious python3 warnings are not - I have logged another issue
