### ISSUE TITLE
Crash on badly formatted pylint comment

### ISSUE THREAD

**Issue by dimaqq** [PyCQA/pylint#2112]
MRE:

```
Score = score  # pylint: disable(invalid-name)
```

Pylint crash:

```
> pylint minimal.py 
No config file found, using default configuration
Traceback (most recent call last):
  File "xxx/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "xxx/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "xxx/lib/python2.7/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "xxx/lib/python2.7/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "xxx/lib/python2.7/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "xxx/lib/python2.7/site-packages/pylint/lint.py", line 978, in check_astroid_module
    checker.process_tokens(tokens)
  File "xxx/lib/python2.7/site-packages/pylint/checkers/format.py", line 803, in process_tokens
    self.new_line(TokenWrapper(tokens), idx-1, idx)
  File "xxx/lib/python2.7/site-packages/pylint/checkers/format.py", line 523, in new_line
    self.check_lines(line, line_num)
  File "xxx/lib/python2.7/site-packages/pylint/checkers/format.py", line 1051, in check_lines
    i = check_line(line, i)
  File "xxx/lib/python2.7/site-packages/pylint/checkers/format.py", line 1018, in check_line
    front_of_equal, back_of_equal = mobj.group(1).split('=', 1)
ValueError: need more than 1 value to unpack
```

Environment:

```
> pip freeze
astroid==1.6.4
backports.functools-lru-cache==1.5
configparser==3.5.0
enum34==1.1.6
futures==3.2.0
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pylint==1.9.1
singledispatch==3.4.0.3
six==1.11.0
wrapt==1.10.11

> python --version
Python 2.7.13
```

**Comment by PCManticore** [comment]
Thanks! Fixed in master and 1.9, we'll release a new patch release for 1.9 shortly.
