### ISSUE TITLE
Fails to work with fabric (fabric3 for Python 3.x) imports

### ISSUE THREAD

**Issue by rudyryk** [PyCQA/pylint#2233]
### Steps to reproduce
1. Install `fabric3` package: `pip install fabric3`
2. Create `sample.py` file to lint:
```python
from fabric.api import run, cd
def run_fetch(match):
    with cd('~/src'):
        run('git pull')
```
3. Run `pylint sample.py`
4. See output with exception:

```
No config file found, using default configuration
************* Module test
C:  1, 0: Missing module docstring (missing-docstring)
C:  2, 0: Missing function docstring (missing-docstring)
Traceback (most recent call last):
  File "/Users/Me/.virtualenvs/sample/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 1161, in visit_with
    for inf_path in inferred_paths:
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 90, in _flatten_container
    for elem in _flatten_container(item):
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 88, in _flatten_container
    for item in iterable:
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/astroid/decorators.py", line 82, in wrapped
    generator = _func(node, context, **kwargs)
  File "/Users/Me/.virtualenvs/sample/lib/python3.6/site-packages/astroid/inference.py", line 214, in infer_import_from
    raise exceptions.InferenceError(node=self, context=context)
astroid.exceptions.InferenceError: Inference failed for <ImportFrom l.1 at 0x111513320>.
```

### Current behavior

Exception is raised.

### Expected behavior

Normal linter errors and warnings are expected.

### pylint --version output

```
No config file found, using default configuration
pylint 1.9.2, 
astroid 1.6.1
Python 3.6.4 (default, Mar 12 2018, 21:41:09) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by rudyryk** [comment]
Sorry, after upgrading ``astroid`` the bug has gone.

New pylint --version output:

```
No config file found, using default configuration
pylint 1.9.2, 
astroid 1.6.5
Python 3.6.4 (default, Mar 12 2018, 21:41:09) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

Probably pylint could warn about deprecated ``astroid``? Just an idea.

**Comment by rudyryk** [comment]
BTW `cd` is still not recognized as context manager but this is another issue.

```
No config file found, using default configuration
************* Module test
C:  1, 0: Missing module docstring (missing-docstring)
C:  2, 0: Missing function docstring (missing-docstring)
E:  3, 4: Context manager 'generator' doesn't implement __enter__ and __exit__. (not-context-manager)
```
