### ISSUE TITLE
pylint stopIteration Runtime Error with Python 3.7

### ISSUE THREAD

**Issue by wolf99** [PyCQA/pylint#2241]
### Steps to reproduce
1. create `hello.py` with code `print('hello')`
2. run `$ python -m pylint hello.py`

### Current behavior

````bash
No config file found, using default configuration
************* Module hello
C:  2, 0: Final newline missing (missing-final-newline)
Traceback (most recent call last):
  File "C:\python\python37\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\python37\lib\site-packages\astroid\decorators.py", line 104, in wrapped
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python\python37\lib\site-packages\pylint\__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "C:\python\python37\lib\site-packages\pylint\__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "C:\python\python37\lib\site-packages\pylint\lint.py", line 1347, in __init__
    linter.check(args)
  File "C:\python\python37\lib\site-packages\pylint\lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "C:\python\python37\lib\site-packages\pylint\lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "C:\python\python37\lib\site-packages\pylint\lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "C:\python\python37\lib\site-packages\pylint\utils.py", line 1011, in walk
    cb(astroid)
  File "C:\python\python37\lib\site-packages\pylint\checkers\base.py", line 1571, in visit_module
    self._check_docstring('module', node)
  File "C:\python\python37\lib\site-packages\pylint\checkers\base.py", line 1633, in _check_docstring
    func = utils.safe_infer(node.body[0].value.func)
  File "C:\python\python37\lib\site-packages\pylint\checkers\utils.py", line 826, in safe_infer
    next(inferit)
RuntimeError: generator raised StopIteration
````

### Expected behavior
Normal lint report

### pylint --version output
````bash
No config file found, using default configuration
pylint 1.9.2,
astroid 1.6.5
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
````

**Comment by PCManticore** [comment]
We don't support 3.7 yet with those versions. you'll have to get the beta release with `pip install --pre -U pylint astroid`.

**Comment by wolf99** [comment]
Thanks for the info @PCManticore 
Could this be documented somewhere - maybe somewhere prominent?

**Comment by wheelhot** [comment]
Hmm, so if I understand, this issue is only for those running Python 3.7? As I have similar issues as well. I tried writing `pip install --pre -U pylint astroid` and my terminal returns this, why? (I'm a newbie so please go easy on me)

```
Omars-MacBook-Pro:ipnd_rps_starter_code-master omartan$ pip install --pre -U pylint astroid
Requirement already up-to-date: pylint in /Users/omartan/Library/Python/2.7/lib/python/site-packages (1.9.2)
Requirement already up-to-date: astroid in /Users/omartan/Library/Python/2.7/lib/python/site-packages (1.6.5)
Requirement not upgraded as not directly required: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pylint) (1.4.1)
Requirement not upgraded as not directly required: isort>=4.2.5 in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from pylint) (4.3.4)
Requirement not upgraded as not directly required: singledispatch; python_version < "3.4" in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from pylint) (3.4.0.3)
Requirement not upgraded as not directly required: mccabe in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from pylint) (0.6.1)
Requirement not upgraded as not directly required: configparser; python_version == "2.7" in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from pylint) (3.5.0)
Requirement not upgraded as not directly required: backports.functools-lru-cache; python_version == "2.7" in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from pylint) (1.5)
Requirement not upgraded as not directly required: wrapt in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from astroid) (1.10.11)
Requirement not upgraded as not directly required: enum34>=1.1.3; python_version < "3.4" in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from astroid) (1.1.6)
Requirement not upgraded as not directly required: lazy-object-proxy in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from astroid) (1.3.1)
Requirement not upgraded as not directly required: futures in /Users/omartan/Library/Python/2.7/lib/python/site-packages (from isort>=4.2.5->pylint) (3.2.0)
```

**Comment by randy-li** [comment]
Thanks!

**Comment by dmlb2000** [comment]
Here's the Travis CI job I'm looking at for this https://travis-ci.org/pacifica/python-jsonpath2/jobs/517374118

Pylint 1.9.4, upgrading to Pylint 2.x fixed issue, though it finally made me drop Python 2.x support testing...

**Comment by joe-klonowski** [comment]
Installing beta release worked for me, would be better if pylint could suggest that fix in the error message instead of making me google it, though.

Thanks!

**Comment by PCManticore** [comment]
@joe-klonowski Feel free to submit a patch, that would be great!
