### ISSUE TITLE
AttributeError in refactoring checker for if followed by slice

### ISSUE THREAD

**Issue by brycepg** [PyCQA/pylint#2252]
Run the following code with `astroid` / `pylint` master:
```python
fooby = ""
if 'foo' in fooby:
    fooby = fooby[1:]
```

Produces the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/pylint/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/home/user/pylint/pylint/__init__.py", line 18, in run_pylint
    Run(sys.argv[1:])
  File "/home/user/pylint/pylint/lint.py", line 1372, in __init__
    linter.check(args)
  File "/home/user/pylint/pylint/lint.py", line 784, in check
    self._do_check(files_or_modules)
  File "/home/user/pylint/pylint/lint.py", line 917, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/user/pylint/pylint/lint.py", line 997, in check_astroid_module
    walker.walk(ast_node)
  File "/home/user/pylint/pylint/utils.py", line 1152, in walk
    self.walk(child)
  File "/home/user/pylint/pylint/utils.py", line 1149, in walk
    cb(astroid)
  File "/home/user/pylint/pylint/checkers/refactoring.py", line 410, in visit_if
    self._check_consider_get(node)
  File "/home/user/pylint/pylint/checkers/refactoring.py", line 392, in _check_consider_get
    and type_and_name_are_equal(node.body[0].value.slice.value, node.test.left)
AttributeError: 'Slice' object has no attribute 'value'
```

line 392 is from 1d4b8c7f17b7b5bdaab26e17a00fd5a434f4b382
@pheanex 

# Version
```
__main__.py 2.0.0.dev1
astroid 2.0.0.dev3
Python 3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

**Comment by pheanex** [comment]
As far as i can see, PCManticore already fixed this?

**Comment by brycepg** [comment]
No that was #2253
