### ISSUE TITLE
RuntimeError occurred when I tried lint python file

### ISSUE THREAD

**Issue by NTMan** [PyCQA/pylint#2272]
### Steps to reproduce
```
C:\git\crm.test\core\www\service\Модули\Активные продажи\activesales>pylint.exe CRMClients.py
Using config file C:\Users\mv.gavrilov\.pylintrc
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 104, in wrapped
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\pylint\lint.py", line 942, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\builder.py", line 153, in file_build
    return self._post_build(module, encoding)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\builder.py", line 173, in _post_build
    self.delayed_assattr(delayed)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\builder.py", line 232, in delayed_assattr
    for inferred in node.expr.infer():
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\context.py", line 71, in cache_generator
    for result in generator:
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\context.py", line 71, in cache_generator
    for result in generator:
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\inference.py", line 166, in infer_call
    for callee in self.func.infer(context):
  File "c:\program files (x86)\python37-32\lib\site-packages\astroid\context.py", line 71, in cache_generator
    for result in generator:
RuntimeError: generator raised StopIteration
************* Module activesales.CRMClients
F:  1, 0: <class 'RuntimeError'>: generator raised StopIteration (astroid-error)
```

### Current behavior
RuntimeError

### Expected behavior
Normal report

### pylint --version output
```
pylint --version
Using config file C:\Users\mv.gavrilov\.pylintrc
pylint.EXE 1.9.2,
astroid 1.6.5
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
```

[.pylintrc.zip](https://github.com/PyCQA/pylint/files/2183063/default.pylintrc.zip)

**Comment by denrasulev** [comment]
Same error.
macOS X 10.13.6
```
pylint --version
No config file found, using default configuration
pylint 1.9.2,
astroid 1.6.5
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
```

**Comment by PCManticore** [comment]
https://github.com/PyCQA/pylint#note
