### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'qname'

### ISSUE THREAD

**Issue by adamtheturtle** [PyCQA/pylint#2330]
### Steps to reproduce
1. Create a file with the following contents:

```python
def example():
    next(iter(set([1])))
    yield 1
```

2. Run pylint on this file

### Current behavior

See the following error:

```
************* Module pylint_example
pylint_example.py:1:0: C0111: Missing module docstring (missing-docstring)
pylint_example.py:1:0: C0111: Missing function docstring (missing-docstring)
Traceback (most recent call last):
  File "/Users/Adam/.virtualenvs/pylint-error/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/lint.py", line 1394, in __init__
    linter.check(args)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/utils.py", line 1159, in walk
    self.walk(child)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/utils.py", line 1159, in walk
    self.walk(child)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/utils.py", line 1159, in walk
    self.walk(child)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/utils.py", line 1156, in walk
    cb(astroid)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/checkers/refactoring.py", line 470, in visit_call
    self._check_raising_stopiteration_in_generator_next_call(node)
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/checkers/refactoring.py", line 502, in _check_raising_stopiteration_in_generator_next_call
    and not _looks_like_infinite_iterator(node.args[0])):
  File "/Users/Adam/.virtualenvs/pylint-error/lib/python3.7/site-packages/pylint/checkers/refactoring.py", line 485, in _looks_like_infinite_iterator
    return inferred.qname() in KNOWN_INFINITE_ITERATORS
AttributeError: 'NoneType' object has no attribute 'qname'
```

### Expected behavior

No error.

### pylint --version output

```
> pylint --version
pylint 2.0.0
astroid 2.0.1
Python 3.7.0 (default, Jun 29 2018, 20:13:13) 
[Clang 9.1.0 (clang-902.0.39.2)]

**Comment by brycepg** [comment]
Hi, this was fixed on master a few days ago: 124b7bc
