### ISSUE TITLE
 python3.7 - Pylint crashes with astroid.exceptions.DuplicateBasesError when using Generic types

### ISSUE THREAD

**Issue by klass-ivan** [PyCQA/pylint#2443]
With python3.7, the pylint crashes on following minified example:
```python
from typing import Generic, TypeVar

IN = TypeVar('IN', contravariant=True)
OUT = TypeVar('OUT', covariant=True)


class Service:
    pass


class ConsumingMixin(Generic[IN]):
    pass


class ProducingMixin(Generic[OUT]):
    pass


class StreamingMixin(Generic[IN, OUT], ConsumingMixin[IN], ProducingMixin[OUT]):
    pass


class Example(StreamingMixin[str, int], Service):
    pass


print(Example.__mro__)
```
### pylint --version output
```
pylint 2.1.1
astroid 2.0.4
Python 3.7.0b3 (default, Mar 30 2018, 04:35:22) 
[GCC 7.3.0]
```

### However, python3.6 environment is working:
```
pylint 2.1.1
astroid 2.0.4
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
```

### Steps to reproduce
1. copy provided snippet into "dupbases.py"
2. run "python dupbases.py" to see there is no actuall error
3. run "pylint dupbases.py" to notice an exception traceback

### Current behavior
```
Traceback (most recent call last):
  File "/home/klass/venvs/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/lint.py", line 1394, in __init__
    linter.check(args)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
    self.walk(child)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
    self.walk(child)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
    self.walk(child)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/utils.py", line 1159, in walk
    cb(astroid)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/pylint/checkers/typecheck.py", line 755, in visit_attribute
    if not [n for n in owner.getattr(node.attrname)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 2309, in getattr
    result = [self.special_attributes.lookup(name)]
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/interpreter/objectmodel.py", line 110, in lookup
    return getattr(self, "py" + name)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/interpreter/objectmodel.py", line 414, in py__mro__
    mro = self._instance.mro()
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 2735, in mro
    return self._compute_mro(context=context)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 2716, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File "/home/klass/venvs/pylint/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 94, in _verify_duplicates_mro
    mros=sequences, cls=cls, context=context)
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (Example), (StreamingMixin, Generic, ConsumingMixin, Generic, ProducingMixin, Generic, object), (Service, object), (StreamingMixin, Service) for <ClassDef.Example l.22 at 0x7f82d9ec49b0>.
```

### Expected behavior
No crash

### Notes:
removing `Generic[IN, OUT], ` from `StreamingMixin` is also working python code, but does not resolve pylint crash

This 3.7 change is possibly related:
https://docs.python.org/3/whatsnew/3.7.html#pep-560-core-support-for-typing-module-and-generic-types

**Comment by PCManticore** [comment]
Thank you, I can reproduce the bug as well.

**Comment by orf** [comment]
On Python 3.7 with the latest aiohttp this error is thrown, meaning we cannot lint anything. Just an FYI

**Comment by SamyCookie** [comment]
similar failure with this code with no import:
```python3
# context
class MetaA(type):
    pass
class A(metaclass=MetaA):
    pass

class MetaB(type):
    pass
class B(metaclass=MetaB):
    pass
```
the following inheritance fails with pylint:
```python3
class C(A, B, metaclass=type('', (type(A), type(B)), {})):
    pass
```
=>
```
internal error with sending report for module ['test.py']
Duplicates found in MROs (), (type, object), (type, object), (type, type) for <ClassDef l.11 at 0x7fbdc3bd4d68>.
```
but surprisingly, with a variable, the almost same code is working:
```python3
MetaC = type('', (type(A), type(B)), {})
class C(A, B, metaclass=MetaC):
    pass
```
version:
```
pylint 2.3.1
astroid 2.2.5
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
```

**Comment by brycepg** [comment]
Thanks @SamyCookie for digging into this futher. I can reproduce this with just astroid now.

```
import astroid

node = astroid.extract_node("""
# context
class MetaA(type):
    pass
class A(metaclass=MetaA):
    pass

class MetaB(type):
    pass
class B(metaclass=MetaB):
    pass

class C(A, B, metaclass=type('', (type(A), type(B)), {})):
    pass
C #@
""").inferred()[0]
metaclass = node.declared_metaclass()
metaclass.mro() # DuplicateBasesError here
```

**Comment by SamyCookie** [comment]
@brycepg https://github.com/PyCQA/astroid/pull/634 already seems to fix this bug, you can check the solution proposed by this PR.
