### ISSUE TITLE
getting "AttributeError: 'NoneType' object has no attribute 'statement'" for small piece of code

### ISSUE THREAD

**Issue by wdv4758h** [PyCQA/pylint#2526]
### Steps to reproduce

I have strip the code to make it easier to reproduce.

1. get this small piece of code

```python
def f(*args):
    from multiprocessing import Process
    args = (42, *args)
    process = Process(target=f, args=args)
```

2. run pylint

```sh
pylint -E test.py 
```

### Current behavior

pylint crash in an exception

```
Traceback (most recent call last):
  File "/home/wdv4758h/py/venv/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/lint.py", line 1595, in __init__
    linter.check(args)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/lint.py", line 925, in check
    self._do_check(files_or_modules)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/lint.py", line 1058, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/lint.py", line 1141, in check_astroid_module
    walker.walk(ast_node)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/utils.py", line 1266, in walk
    cb(astroid)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 1087, in visit_call
    has_no_context_positional_variadic = _no_context_variadic_positional(node)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 533, in _no_context_variadic_positional
    return _no_context_variadic(node, scope.args.vararg, astroid.Starred, variadics)
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 560, in _no_context_variadic
    inferred_statement = inferred.statement()
  File "/home/wdv4758h/py/venv/lib/python3.6/site-packages/astroid/node_classes.py", line 451, in statement
    return self.parent.statement()
AttributeError: 'NoneType' object has no attribute 'statement'
```

### Expected behavior

At least don't have exception

### pylint --version output

```
pylint 2.2.0-dev
astroid 2.0.4
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0]
```

tested with current master `20694325dde16377dd5e295ccdd82dffa68ce7aa` and serveral stable releases

**Comment by PCManticore** [comment]
This is fixed in astroid's master, thanks for creating an issue!

**Comment by wdv4758h** [comment]
wow, that's fast

We just discover this issue with our company codebase today :stuck_out_tongue:
