### ISSUE TITLE
Running pylint 2.1.1 wih python 3.5 on windows always throws an exception

### ISSUE THREAD

**Issue by kljuco** [PyCQA/pylint#2575]
### Steps to reproduce
1. Install python 3.5 on Windows 10
2. run: `pip install pylint`
3. run `pylint -V`

### Current behavior
Throws exception:
```Traceback (most recent call last):
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 718, in dispatch
    impl = dispatch_cache[cls]
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\weakref.py", line 352, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x00000269FF52C958; to 'EnumMeta' at 0x00000269FF5F57B8 (Context)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 721, in dispatch
    impl = registry[cls]
KeyError: <enum 'Context'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python35\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\lint.py", line 1313, in __init__
    linter.load_default_plugins()
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\lint.py", line 504, in load_default_plugins
    checkers.initialize(self)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\checkers\__init__.py", line 122, in initialize
    register_plugins(linter, __path__[0])
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\utils.py", line 1181, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\astroid\modutils.py", line 278, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\astroid\modutils.py", line 239, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\checkers\python3.py", line 154, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\checkers\python3.py", line 585, in Python3Checker
    'sys.version_info < (3, 0)',
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\pylint\checkers\python3.py", line 580, in <listcomp>
    [astroid.extract_node(x).repr_tree() for x in [
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\astroid\node_classes.py", line 877, in repr_tree
    _repr_tree(self, result, set())
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\astroid\node_classes.py", line 866, in _repr_node
    depth)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages\astroid\node_classes.py", line 866, in _repr_node
    depth)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 723, in dispatch
    impl = _find_impl(cls, registry)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 674, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 662, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 616, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 616, in <listcomp>
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 620, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "c:\users\USERNAME\appdata\local\programs\python\python35\lib\functools.py", line 571, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy
```

### Expected behavior
Should not throw exception

### pylint --version output
This throw exception as well but `pip list` shows astroid-2.0.4 and pylint-2.1.1

I've installed and uninstalled couple of times both astroid and pylint as well as python

**Comment by PCManticore** [comment]
Hey @kljuco thanks for reporting an issue! I think this occurred in the past as well, can you check if you have `enum34` installed and if so, what version do you have? This comment from a past issue might help as well: https://github.com/PyCQA/pylint/issues/1388#issuecomment-301050775.

**Comment by PCManticore** [comment]
Closing for now, but feel free to reopen if you can still reproduce after using those instructions from my previous comment.
