### ISSUE TITLE
Pylint 2.1.1 throws StopIteration on Python 3.7.1

### ISSUE THREAD

**Issue by antonenk** [PyCQA/pylint#2579]
### Steps to reproduce
1. docker run -it -v `pwd`:/opt/myproject python:3.7.1-slim-stretch bash -c 'pip install --pre pylint; cd /opt/myproject; pylint lib'

### Current behavior
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 100, in wrapped
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 896, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 231, in delayed_assattr
    for inferred in node.expr.infer():
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.7/site-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 82, in wrapped
    generator = _func(node, context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/astroid/inference.py", line 764, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/usr/local/lib/python3.7/site-packages/astroid/protocols.py", line 303, in _arguments_infer_argname
    is_metaclass = isinstance(cls, nodes.ClassDef) and cls.type == 'metaclass'
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1032, in _class_type
    if _is_metaclass(klass):
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1018, in _is_metaclass
    if _is_metaclass(baseobj, seen):
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1018, in _is_metaclass
    if _is_metaclass(baseobj, seen):
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1001, in _is_metaclass
    for baseobj in base.infer():
RuntimeError: generator raised StopIteration
************* Module ss.mqservice
lib/ss/mqservice.py:1:0: <class 'RuntimeError'>: generator raised StopIteration (astroid-error)
```

### Expected behavior
-----------------------------------
Your code has been rated at 9.99/10

### pylint --version output
pylint 2.1.1
astroid 2.0.4
Python 3.7.1 (default, Oct 29 2018, 17:51:13)
[GCC 6.3.0 20170516]

### Suggested solution
Fix code according to https://www.python.org/dev/peps/pep-0479/
```
diff -ru pylint-2.1.1/checkers/spelling.py pylint/checkers/spelling.py
--- pylint-2.1.1/checkers/spelling.py   2018-10-30 10:03:04.000000000 -0700 
+++ pylint/checkers/spelling.py 2018-11-01 04:08:25.665123062 -0700
@@ -114,7 +114,7 @@
     def next(self):
         while True:
             if not self._text:
-                raise StopIteration()
+                return
             if '/' not in self._text:
                 text = self._text
                 self._offset = 0
@@ -138,9 +138,9 @@
             if not pre_text or not post_text:
                 break
             if not pre_text[-1].isalpha() or not post_text[0].isalpha():
-                raise StopIteration()
+                return
             self._text = pre_text + ' ' + post_text
-        raise StopIteration()
+        return


 class SpellingChecker(BaseTokenChecker):
```

**Comment by PCManticore** [comment]
Given that we don't have a way to reproduce right now, I'm going to close this. Please reopen if you find a small reproduction example.
