### ISSUE TITLE
pylint 2.2.1 generates bad pylintrc for logging-format-style

### ISSUE THREAD

**Issue by jwkvam** [PyCQA/pylint#2614]
### Steps to reproduce
In a new directory run the following
1. `pylint --generate-rcfile > pylintrc`
2. `pylint`

### Current behavior

This gives a traceback:
```python
Traceback (most recent call last):
  File "/Users/jacques/miniconda/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/jacques/miniconda/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/Users/jacques/miniconda/lib/python3.7/site-packages/pylint/lint.py", line 1571, in __init__
    linter.load_config_file()
  File "/Users/jacques/miniconda/lib/python3.7/site-packages/pylint/config.py", line 751, in load_config_file
    for option, value in parser.items(section):
  File "/Users/jacques/miniconda/lib/python3.7/configparser.py", line 857, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/Users/jacques/miniconda/lib/python3.7/configparser.py", line 857, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/Users/jacques/miniconda/lib/python3.7/configparser.py", line 854, in <lambda>
    section, option, d[option], d)
  File "/Users/jacques/miniconda/lib/python3.7/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/Users/jacques/miniconda/lib/python3.7/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
```

### Expected behavior

I can run pylint without crashing. In fact, I cannot run pylint at all in the directory until I delete or modify pylintrc.

### pylint --version output
```
pylint 2.2.1
astroid 2.1.0
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 09:50:42) 
[Clang 9.0.0 (clang-900.0.37)]
```

### Root cause

It seems that `%` is an escape character in `pylintrc`? I believe pylint should generate
```
logging-format-style=%%
```
Instead of
```
logging-format-style=%
```

**Comment by PCManticore** [comment]
Thanks for reporting a bug, working on a fix.
