### ISSUE TITLE
Running pylint on a file causes it to crash

### ISSUE THREAD

**Issue by PK1210** [PyCQA/pylint#2664]
### Steps to reproduce
1. git clone https://github.com/rg3/youtube-dl
2. cd youtube-dl/youtube_dl/extractor
3. pylint common.py

### Current behavior
Pylint starts listing error but crashes at the end.

### Expected behavior
Pylint lists various linting errors in the file

### pylint --version output
pylint 2.1.1
astroid 2.0.4
Python 3.7.0 (default, Jul 23 2018, 20:24:19) 
[Clang 9.0.0 (clang-900.0.39.2)]

### Error log

    Traceback (most recent call last):
      File "/usr/local/bin/pylint", line 11, in <module>
        sys.exit(run_pylint())
      File "/usr/local/lib/python3.7/site-packages/pylint/__init__.py", line 19, in run_pylint
        Run(sys.argv[1:])
      File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1394, in __init__
        linter.check(args)
      File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 801, in check
        self._do_check(files_or_modules)
      File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 938, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1018, in check_astroid_module
        walker.walk(ast_node)
      File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
        self.walk(child)
      File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
        self.walk(child)
      File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1162, in walk
        self.walk(child)
      File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1159, in walk
        cb(astroid)
      File "/usr/local/lib/python3.7/site-packages/pylint/checkers/exceptions.py", line 394, in visit_tryexcept
        self._check_try_except_raise(node)
      File "/usr/local/lib/python3.7/site-packages/pylint/checkers/exceptions.py", line 373, in _check_try_except_raise
        utils.safe_infer(handler.type))):
      File "/usr/local/lib/python3.7/site-packages/pylint/checkers/utils.py", line 1011, in is_subclass_of
        return node_b.name in {base.name for base in node_a.bases}
    AttributeError: 'NoneType' object has no attribute 'name'

**Comment by PCManticore** [comment]
Hey @PK1210 Thanks for reporting an issue! This should already be fixed with pylint 2.2 with this commit: https://github.com/PyCQA/pylint/commit/47c258eee17937bae776594a101eb8fdd36cd71d
