### ISSUE TITLE
DuplicateBasesError raised on kite-shaped inheritance graph with base class created by type()

### ISSUE THREAD

**Issue by pdeblanc** [PyCQA/pylint#2666]
### Steps to reproduce
Create **example.py** (this is the smallest example I could derive -- removing any class causes the error to go away):
```
A = type('A', (object,), {})

class B1(A):
    pass

class B2(A):
    pass

class C(B1, B2):
    pass

class D(C):
    def update(self):
        self.hello = 'hello'
```

Then run `pylint example.py`

### Current behavior
Pylint crashes with the following output:
```
Traceback (most recent call last):
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/decorators.py", line 31, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.D l.12 at 0x10533a710>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pylint/lint.py", line 1115, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/manager.py", line 87, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/builder.py", line 136, in file_build
    return self._post_build(module, encoding)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/builder.py", line 156, in _post_build
    self.delayed_assattr(delayed)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/builder.py", line 230, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/builder.py", line 57, in _can_assign_attr
    slots = node.slots()
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/decorators.py", line 33, in cached
    cache[func] = result = func(*args, **kwargs)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 2703, in slots
    slots = list(grouped_slots())
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 2688, in grouped_slots
    for cls in self.mro()[:-1]:
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 2781, in mro
    return self._compute_mro(context=context)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 2763, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File "/Users/peter/.pyenv/versions/3.6.5/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 99, in _verify_duplicates_mro
    context=context,
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (D), (C, B1, A, B2, A, object), (C) for <ClassDef.D l.12 at 0x10533a710>.
************* Module example
example.py:1:0: F0002: <class 'astroid.exceptions.DuplicateBasesError'>: Duplicates found in MROs (D), (C, B1, A, B2, A, object), (C) for <ClassDef.D l.12 at 0x10533a710>. (astroid-error)
```

### Expected behavior
Pylint should analyze the file without crashing.

### pylint --version output
I've reproduced the error in the following setups:

```
pylint 2.2.2
astroid 2.1.0
Python 3.6.5 (default, Nov  9 2018, 15:17:33)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

pylint 2.1.0
astroid 2.0.2
Python 3.7.1 (default, Nov  6 2018, 18:46:03)
[Clang 10.0.0 (clang-1000.11.45.5)]

pylint 2.2.2
astroid 2.1.0
Python 3.7.1 (default, Nov  6 2018, 18:46:03)
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Comment by PCManticore** [comment]
Thanks for reporting a bug, I can confirm the issue.

**Comment by SamyCookie** [comment]
Is https://github.com/PyCQA/pylint/commit/e3d4e80ca9be6b61d7c9773f8a20661a52fa9ed9 and https://github.com/PyCQA/astroid/pull/634 close this issue ?

**Comment by pdeblanc** [comment]
The underlying bug is now fixed in astroid master, but the pylint issue will remain unsolved until astroid is updated on PyPI and the pylint install requirements are updated.

**Comment by PCManticore** [comment]
Yeah, this is going to be part of 2.4 when it's going to be launched, no need for having it open.
