### ISSUE TITLE
win10 pylint.exe - UnicodeDecodeError - due to bad .pylintrc file - please add better stacktrace

### ISSUE THREAD

**Issue by fenchu** [PyCQA/pylint#2704]
pylint.exe is used by both my editor(vsc) and my code analyzer(sonarqube) so I see this a lot.

### Steps to reproduce
1. install python 3.7.2
2. install latest pylint
3. pylint.exe
(I use venv on windows ,but it is the same on base python also)

### Current behavior
```
(sensiotools) PS D:\sensio-data\sensiotools> pylint.exe
Traceback (most recent call last):
  File "D:\python\Python372\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\Python372\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\dev\sensiotools\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "d:\dev\sensiotools\lib\site-packages\pylint\__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "d:\dev\sensiotools\lib\site-packages\pylint\lint.py", line 1558, in __init__
    linter.read_config_file(verbose=self.verbose)
  File "d:\dev\sensiotools\lib\site-packages\pylint\config.py", line 729, in read_config_file
    parser.read_file(fp)
  File "D:\python\Python372\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "D:\python\Python372\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "D:\python\Python372\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "D:\python\Python372\lib\encodings\utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

```
(sensiotools) PS D:\sensio-data\sensiotools> pip install pylint --upgrade
Requirement already up-to-date: pylint in d:\dev\sensiotools\lib\site-packages (2.2.2)
Requirement already satisfied, skipping upgrade: astroid>=2.0.0 in d:\dev\sensiotools\lib\site-packages (from pylint) (2.1.0)
Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in d:\dev\sensiotools\lib\site-packages (from pylint) (0.4.0)
Requirement already satisfied, skipping upgrade: isort>=4.2.5 in d:\dev\sensiotools\lib\site-packages (from pylint) (4.3.4)
Requirement already satisfied, skipping upgrade: mccabe in d:\dev\sensiotools\lib\site-packages (from pylint) (0.6.1)
Requirement already satisfied, skipping upgrade: lazy-object-proxy in d:\dev\sensiotools\lib\site-packages (from astroid>=2.0.0->pylint) (1.3.1)
Requirement already satisfied, skipping upgrade: six in d:\dev\sensiotools\lib\site-packages (from astroid>=2.0.0->pylint) (1.11.0)
Requirement already satisfied, skipping upgrade: wrapt in d:\dev\sensiotools\lib\site-packages (from astroid>=2.0.0->pylint) (1.11.1)
```
Same with latest prerelase:
```
pip install pylint astroid --pre -U
Requirement already up-to-date: pylint in d:\dev\sensiotools\lib\site-packages (2.3.0.dev0)
Requirement already up-to-date: astroid in d:\dev\sensiotools\lib\site-packages (2.2.0.dev0)
Requirement already satisfied, skipping upgrade: mccabe in d:\dev\sensiotools\lib\site-packages (from pylint) (0.6.1)
Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in d:\dev\sensiotools\lib\site-packages (from pylint) (0.4.0)
Requirement already satisfied, skipping upgrade: isort>=4.2.5 in d:\dev\sensiotools\lib\site-packages (from pylint) (4.3.4)
Requirement already satisfied, skipping upgrade: wrapt in d:\dev\sensiotools\lib\site-packages (from astroid) (1.11.1)
Requirement already satisfied, skipping upgrade: six in d:\dev\sensiotools\lib\site-packages (from astroid) (1.11.0)
Requirement already satisfied, skipping upgrade: lazy-object-proxy in d:\dev\sensiotools\lib\site-packages (from astroid) (1.3.1)
```

### pylint --version output
```
see stacktrace above
```

**Comment by fenchu** [comment]
This was fixed by:
```
pylint --generate-rcfile | out-file -encoding utf8 .pylintrc
```
Please add a better description. Add filename to the raised error.

**Comment by PCManticore** [comment]
I don't think this is on `pylint`'s side. `out-file` must be doing something that is not necessarily `UTF-8` as per the stack trace. We cannot add a filename to the raised error as that error is not raised by `pylint`itself, but by `configparser` library.
