### ISSUE TITLE
StopIteration issue on Python 3.7 with pylint 1.9.4

### ISSUE THREAD

**Issue by andy-maier** [PyCQA/pylint#2762]
Pylint 1.9.4 on Python 3.7 still stumbles across the use of a `StopIteration` exception.

This has been reported already earlier in issue #2241 and #2579, which were both closed without solving the issue.

We would like to use pylint on both py2.7 and py3.4+, preferrably the same version.

According to the metadata of pylint 1.9.4 on pypi, Python 3.7 is supported (requires: `Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*`)

### Steps to reproduce

1. create `hello.py` with code `print('hello')`
2. run `python -m pylint hello.py`

### Current behavior

```
$ python -m pylint hello.py
No config file found, using default configuration
************* Module hello
C:  3, 0: Trailing newlines (trailing-newlines)
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/astroid/decorators.py", line 89, in wrapped
    res = next(generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/astroid/decorators.py", line 104, in wrapped
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/lint.py", line 1353, in __init__
    linter.check(args)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/lint.py", line 774, in check
    self._do_check(files_or_modules)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/lint.py", line 907, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/lint.py", line 986, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/checkers/base.py", line 1571, in visit_module
    self._check_docstring('module', node)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/checkers/base.py", line 1633, in _check_docstring
    func = utils.safe_infer(node.body[0].value.func)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/pylint/checkers/utils.py", line 825, in safe_infer
    next(inferit)
RuntimeError: generator raised StopIteration
```

### Expected behavior

Should produce output without failing.

### pylint --version output
```
$ pylint --version
No config file found, using default configuration
pylint 1.9.4, 
astroid 1.6.5
Python 3.7.2 (default, Feb 12 2019, 08:16:38) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```

### Further environment data
* MacOS
* Python is used in a virtualenv

**Comment by andy-maier** [comment]
I see two options:
1. roll back the fixes for StopIteration that are apparently in the latest version of pylint and astroid, into the 1.x versions
2. Change the metadata of pylint 1.x to exclude Python 3.7 and future higher versions

**Comment by andy-maier** [comment]
I verified that the latest pylint and astroid versions work for me on Python 3.7:
```
(pywbem37) Andreass-MacBook-Pro-2:pywbem maiera$ pylint --version
pylint 2.2.2
astroid 2.1.0
Python 3.7.2 (default, Feb 12 2019, 08:16:38) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```
We can live with using these versions on Python 3.4+, and the latest 1.x versions on Python 2.7.

**Comment by PCManticore** [comment]
@andy-maier pylint 1.9.4 does not support Python 3.7. If you need support for python 3.7, you need to use the 2.X releases instead. Thanks for pointing out the inconsistent metadata, just pushed a fix for that.
