### ISSUE TITLE
maximum recursion depth exceeded when pylinting based on run-time introspection

### ISSUE THREAD

**Issue by claw111** [PyCQA/pylint#2882]
I'm migrating a python project from py2 (2.7.15) to py3 (3.7.3).  The project use the python binding from libtorrent, which is built by the project.

With py2, pylint (1.9.4) has no problems with the project when libtorrent==1.1.12 is added to the extension package whitelist for run-time introspection.  When the project is changed to use libtorrent==1.2.0, then pylint blows it's stack with the following error snippet:

> ...
  File "/home/vagrant/derp/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 136, in qname
    return '%s.%s' % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 136, in qname
    return '%s.%s' % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 136, in qname
    return '%s.%s' % (self.parent.frame().qname(), self.name)
RuntimeError: maximum recursion depth exceeded

With py3, pylint (2.3.1) has a similar experience when libtorrent==1.2.0 is added to the extension package whitelist for run-time introspection.

> ...
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  [Previous line repeated 963 more times]
RecursionError: maximum recursion depth exceeded

It should be noted that libtorrent==1.1.12 fails to build for python3, so a like-for-like comparison will be inconclusive.

All built libtorrent python extensions do load and run within their expected py2 and py3 virtual environments, so it's not a compile-time or run-time linking problem causing grief for either python or astroid.

I can produce this issue on the following environments:
- Fedora 28
  - kernel: 5.0.7-100.fc28.x86_64
  - python2.x86_64: 2.7.15
  - gcc.x86_64: 8.3.1-2
- Fedora 29
  - kernel: 5.0.7-200.fc29.x86_64
  - python3.x86_64: 3.7.3-1
  - gcc.x86_64: 8.3.1-2

### Steps to reproduce

1. Create and activate a virtual environment:
> virtualenv derp
cd ./derp/
. ./bin/activate

2. Download and build boost==1.69.0:
> wget 'https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.zip'
unzip -q boost_1_69_0.zip
cd ./boost_1_69_0/
python -c 'import sysconfig; v=sysconfig.get_config_vars(); print("using python : {:s} : : {:s} ;".format(v["py_version_short"], v["INCLUDEPY"]));' > ./tools/build/user-config.jam
./bootstrap.sh --with-libraries=system,chrono,random,python --prefix=..
export BOOST_ROOT=$(pwd)
./b2 --hash -q link=shared threading=multi install
cd ../

3. Download and build libtorrent==1.1.12:
> wget 'https://github.com/arvidn/libtorrent/archive/libtorrent_1_1_12.zip'
unzip -q libtorrent_1_1_12.zip
cd ./libtorrent-libtorrent_1_1_12/bindings/python/
$BOOST_ROOT/b2 --hash -q threading=multi libtorrent-link=static boost-link=shared
find ./bin/ -type f -name '*.so' -exec cp -v {} ../../ \;
cd ../../../

4. Download and build libtorrent==1.2.0:
> wget 'https://github.com/arvidn/libtorrent/archive/libtorrent_1_2_0.zip'
unzip -q libtorrent_1_2_0.zip
cd ./libtorrent-libtorrent_1_2_0/bindings/python/
$BOOST_ROOT/b2 --hash -q threading=multi libtorrent-link=static boost-link=shared
find ./bin/ -type f -name '*.so' -exec cp -v {} ../../ \;
cd ../../../

5. Install the latest pylint available for the python within the virtualenv:
> pip install pylint
pip freeze

6. The pylint configuration file to apply when linting the sample python source code:
> cat > ./pylintrc <<'\_EOF\_'
[MASTER]
\# For pylint to perform analysis based on run-time introspection of living
\# libtorrent objects, the extension must be loaded into the python interpreter
\# that is running pylint.
extension-pkg-whitelist=libtorrent
\_EOF\_

7. Create a sample python source file to demonstrate the issue with pylint:
> cat > ./sample.py <<'\_EOF\_'
import libtorrent as x
print(x.version)
\_EOF\_

8. Demonstrate pylint has no issue with libtorrent==1.1.12, but produces a recursive error with libtorrent==1.2.0:
> for v in 1_1_12 1_2_0 ; do
        ln -vfs -t "$(python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())')" "$(pwd)/libtorrent-libtorrent_$v/libtorrent.so"
        LD_LIBRARY_PATH=./lib python --version
        LD_LIBRARY_PATH=./lib python ./sample.py
        LD_LIBRARY_PATH=./lib pylint --version
        LD_LIBRARY_PATH=./lib pylint ./sample.py
done

### Current behavior
Output from python==3.7.3, pylint==2.3.1, and libtorrent==1.2.0:

> '/home/vagrant/derp/lib/python3.7/site-packages/libtorrent.so' -> '/home/vagrant/derp/libtorrent-libtorrent_1_2_0/libtorrent.so'
Python 3.7.3
1.2.0.0
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 13:41:07) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
************* Module sample
sample.py:1:0: C0111: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/home/vagrant/derp/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/home/vagrant/derp/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1590, in visit_import
    module = next(_infer_name_module(node, parts[0]))
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/inference.py", line 240, in infer_import
    yield self.do_import_module(name)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 619, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/manager.py", line 152, in ast_from_module_name
    return self.ast_from_module(module, modname)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/manager.py", line 239, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/builder.py", line 97, in module_build
    node = self._manager.visit_transforms(node)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/manager.py", line 69, in visit_transforms
    return self._transform.visit(node)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 89, in visit
    module.body = [self._visit(child) for child in module.body]
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 89, in <listcomp>
    module.body = [self._visit(child) for child in module.body]
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 54, in _visit
    visited = self._visit_generic(value)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 61, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 61, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 67, in _visit_generic
    return self._visit(node)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 57, in _visit
    return self._transform(node)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/transforms.py", line 39, in _transform
    if predicate is None or predicate(node):
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/brain/brain_uuid.py", line 19, in <lambda>
    nodes.ClassDef, _patch_uuid_class, lambda node: node.qname() == "uuid.UUID"
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  File "/home/vagrant/derp/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 156, in qname
    return "%s.%s" % (self.parent.frame().qname(), self.name)
  [Previous line repeated 963 more times]
RecursionError: maximum recursion depth exceeded

### Expected behavior
Output similar to the working behaviour experienced from python==2.7.15, pylint==1.9.4, and libtorrent==1.1.12:

> '/home/vagrant/derp/lib/python2.7/site-packages/libtorrent.so' -> '/home/vagrant/derp/libtorrent-libtorrent_1_1_12/libtorrent.so'
Python 2.7.15
1.1.12.0
Using config file /home/vagrant/derp/pylintrc
pylint 1.9.4, 
astroid 1.6.6
Python 2.7.15 (default, Oct 15 2018, 15:24:06) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
Using config file /home/vagrant/derp/pylintrc
************* Module sample
C:  2, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:  1, 0: Missing module docstring (missing-docstring)
\------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

### pylint --version output

Fedora 28:

> Using config file /home/vagrant/derp/pylintrc
pylint 1.9.4, 
astroid 1.6.6
Python 2.7.15 (default, Oct 15 2018, 15:24:06) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

Fedora 29:

> pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 13:41:07) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

**Comment by PCManticore** [comment]
Thanks for the report @claw111

**Comment by noah-holland** [comment]
I'm similarly seeing this issue when using pylint on a file with the following:
```python3
from setuptools.extension import Extension
```

I noticed this when going from pylint 2.2.3 to 2.4.1.

**Comment by PCManticore** [comment]
Uff turns out this was quite complicated and I still did not manage to have `libtorrent` fully installed on MacOS. If it's possible, please post a Dockerfile through which I can reproduce the issue, but otherwise there's not much I can do to help since the steps to get an environment working are quite convoluted. Thanks!

@noah-holland I can not reproduce the `setuptools` issue. Regardless it should have been a separate issue, not a comment in this one.
