### ISSUE TITLE
Crashing when having bad syntax disabling pylint check for a comment

### ISSUE THREAD

**Issue by jooola** [PyCQA/pylint#2904]
### Steps to reproduce
1. Add a comment like the following to your code:
```python
# TODO: Blablablabla # pylint: fixme
def blablablabla(arg):
    pass
```

2. Run pylint against the code

### Current behavior
Raises some exceptions:
```
Traceback (most recent call last):
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/checkers/misc.py", line 155, in process_tokens
    _, value = disable_option_match.group(1).split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/utils.py", line 449, in is_one_message_enabled
    return self.file_state._module_msgs_state[msgid][line]
KeyError: 'I0010'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/__main__.py", line 8, in <module>
    pylint.run_pylint()
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/lint.py", line 1156, in check_astroid_module
    checker.process_tokens(tokens)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/checkers/misc.py", line 163, in process_tokens
    line=comment.string,
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/checkers/__init__.py", line 110, in add_message
    self.linter.add_message(msg_id, line, node, args, confidence, col_offset)
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/utils.py", line 496, in add_message
    message_definition, line, node, args, confidence, col_offset
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/utils.py", line 533, in add_one_message
    if not self.is_message_enabled(msgid, line, confidence):
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/utils.py", line 441, in is_message_enabled
    if self.is_one_message_enabled(msgid, line):
  File "/path/to/private/dir/venv/lib/python3.7/site-packages/pylint/utils.py", line 456, in is_one_message_enabled
    if max_line_number and line > max_line_number:
TypeError: '>' not supported between instances of 'str' and 'int'

```

### Expected behavior

I know I have a syntax error here, but the exception should at least print the file path and line where it occurred.

### pylint --version output

```
$ python -m pylint --version              
__main__.py 2.3.1
astroid 2.2.5
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0]
```

**Comment by PCManticore** [comment]
Thank you for the report @jooola !
