### ISSUE TITLE
RecursionError when len() of global list is referenced while mutating it

### ISSUE THREAD

**Issue by ulfalizer** [PyCQA/pylint#2906]
Running pylint3 2.2.2, astroid 2.1.0.

Run `pylint3` on this script to reproduce:

```python3
lst = []


def foo():
    lst.append(0)


def bar():
    global lst

    n = len(lst)
    lst += [n]
```

(Just `lst += n` also crashes.)

Output:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7fa1eb8bd488>, <Call l.9 at 0x7fa1eb6a3e48>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7fa1eb8bd488>, <Call l.9 at 0x7fa1eb6a3e48>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7fa1eb8bd488>, <Call l.9 at 0x7fa1eb6a3e48>)

... (etc.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint3", line 11, in <module>
    load_entry_point('pylint==2.2.2', 'console_scripts', 'pylint')()
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 1608, in __init__
    linter.check(args)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 938, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 1071, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 1154, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils.py", line 1266, in walk
    cb(astroid)
  File "/usr/lib/python3/dist-packages/pylint/checkers/base.py", line 1921, in visit_functiondef
    self._check_docstring(ftype, node)
  File "/usr/lib/python3/dist-packages/pylint/checkers/base.py", line 1952, in _check_docstring
    func = utils.safe_infer(node.body[0].value.func)
  File "/usr/lib/python3/dist-packages/pylint/checkers/utils.py", line 1077, in safe_infer
    next(inferit)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/lib/python3/dist-packages/astroid/inference.py", line 290, in infer_attribute
    for owner in self.expr.infer(context):
  File "/usr/lib/python3/dist-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/usr/lib/python3/dist-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/usr/lib/python3/dist-packages/astroid/bases.py", line 135, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/lib/python3/dist-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/usr/lib/python3/dist-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/usr/lib/python3/dist-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/usr/lib/python3/dist-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
... (etc.)
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 475, in statement
    return self.parent.statement()
RecursionError: maximum recursion depth exceeded
```

**Comment by ulfalizer** [comment]
Probably the same issue as in https://github.com/PyCQA/pylint/issues/2899.

**Comment by PCManticore** [comment]
Hi @ulfalizer Thanks for reporting an issue. Unfortunately I cannot reproduce this using the latest unreleased version (2.4.0 with astroid 2.3.0).
