### ISSUE TITLE
Pylint==1.9.4 exits with cannot import name ConverterMapping

### ISSUE THREAD

**Issue by flyingarg** [PyCQA/pylint#2935]
### Steps to reproduce
1.pylint <directory with python files>

### Current behavior
1. Exits with following error
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==1.9.4', 'console_scripts', 'pylint')()
  File "/home/mohitr/.local/lib/python2.7/site-packages/pylint/__init__.py", line 15, in run_pylint
    from pylint.lint import Run
  File "/home/mohitr/.local/lib/python2.7/site-packages/pylint/lint.py", line 67, in <module>
    from pylint import checkers
  File "/home/mohitr/.local/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 45, in <module>
    from pylint.config import OptionsProviderMixIn
  File "/home/mohitr/.local/lib/python2.7/site-packages/pylint/config.py", line 49, in <module>
    import configparser
  File "/home/mohitr/.local/lib/python2.7/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping

### Expected behavior
Usage error or pylint output listings

### pylint --version output
pylint==1.9.4
Python 2.7.16
configparser (3.7.4)

**Comment by flyingarg** [comment]
Seems to be broken when installed using ubuntu repo. 

Works when pylint is installed through pip and venv

**Comment by lamborghini1993** [comment]
same error，please help me

**Comment by hippo91** [comment]
@lamborghini1993 this is an old, closed, issue. From @flyingarg answer you have to install `pylint` in a virtual environment, using pip.
