### ISSUE TITLE
A pylint stopIteration Runtime Error caused by runpy.run_path()

### ISSUE THREAD

**Issue by yanqd0** [PyCQA/pylint#2960]
### Steps to reproduce

1. Install the latest pylint (2.3.1).
2. Write a `run.py` file.
3. Run `pylint run.py`.

The content of `run.py` file:

```python
from runpy import run_path
_STH = run_path('hello.py')
```

### Current behavior

```shell
$ pylint run.py
************* Module run
run.py:1:0: C0111: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/protocols.py", line 492, in _infer_context_manager
    enter = next(inferred.igetattr("__enter__", context=context))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/venv/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/checkers/base.py", line 1747, in visit_assignname
    if isinstance(utils.safe_infer(assign_type.value), astroid.ClassDef):
  File "/private/tmp/venv/lib/python3.7/site-packages/pylint/checkers/utils.py", line 1070, in safe_infer
    next(inferit)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 141, in raise_if_nothing_inferred
    yield from generator
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 219, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1664, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 213, in infer_call
    for callee in self.func.infer(context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 279, in infer_attribute
    for owner in self.expr.infer(context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 219, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 1664, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/bases.py", line 137, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 92, in wrapped
    generator = _func(node, context, **kwargs)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 832, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/bases.py", line 137, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/bases.py", line 137, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 279, in infer_attribute
    for owner in self.expr.infer(context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 279, in infer_attribute
    for owner in self.expr.infer(context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/bases.py", line 137, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 92, in wrapped
    generator = _func(node, context, **kwargs)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/inference.py", line 832, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/private/tmp/venv/lib/python3.7/site-packages/astroid/protocols.py", line 537, in with_assigned_stmts
    yield from _infer_context_manager(self, mgr, context)
RuntimeError: generator raised StopIteration
```

### Expected behavior

Do not crash.

### pylint --version output

```shell
$ pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.7.2 (default, Dec 30 2018, 16:59:44)
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Comment by yanqd0** [comment]
`pip install 'pylint<2.3'` can fix the issue.
`pip install 'astroid<2.2'` can also fix it, with this red line printed:

```
ERROR: pylint 2.3.1 has requirement astroid<3,>=2.2.0, but you'll have astroid 2.1.0 which is incompatible.
```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by PCManticore** [comment]
Doesn't seem to reproduce any longer with the latest unreleased code.
