### ISSUE TITLE
emacs-package-install and ConfigParser error when using it.

### ISSUE THREAD

**Issue by quoidautre** [PyCQA/pylint#2990]
Hi,
I've an error when I'm trying to install Pylint with apt.
I'm on a debian Jessie, using Vagrant : 
```
Linux jessie 3.16.0-9-amd64 #1 SMP Debian 3.16.68-1 (2019-05-22) x86_64 GNU/Linux
```
```
...
Paramétrage de python-logilab-common (0.62.0-1) ...
Paramétrage de python-astroid (1.2.1-3) ...
Paramétrage de pylint (1.3.1-3) ...
ERROR: pylint is broken - called emacs-package-install as a new-style add-on, but has no compat file.
Install pylint for emacs
Paramétrage de python-egenix-mxtools (3.2.8-1) ...
Paramétrage de python-egenix-mxdatetime (3.2.8-1) ...
Paramétrage de python-tk (2.7.8-2+b1) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.19-18+deb8u10) ...
...
```

### Steps to reproduce
1. sudo apt-get install pylint
2. pylint xxx.py

### Current behavior
$ pylint check_file.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/pylint/__main__.py", line 3, in <module>
    pylint.run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 21, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 967, in __init__
    linter.read_config_file()
  File "/usr/lib/python2.7/dist-packages/logilab/common/configuration.py", line 625, in read_config_file
    parser.read([config_file])
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/vagrant/.pylintrc, line: 1
'disable=locally-disabled, locally-enabled\n'

### pylint --version output
pylint==1.3.1
$ python --version
Python 2.7.9
```
$ pylint --version
Traceback (most recent call last):
  File "/usr/bin/pylint", line 3, in <module>
    run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 21, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 967, in __init__
    linter.read_config_file()
  File "/usr/lib/python2.7/dist-packages/logilab/common/configuration.py", line 625, in read_config_file
    parser.read([config_file])
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/vagrant/.pylintrc, line: 1
'disable=locally-disabled, locally-enabled\n'
```

Can anybody helps me ? :)

Thanks
Fabrice

**Comment by thisch** [comment]
Please post the contents of your pylintrc file "/home/vagrant/.pylintrc".

**Comment by quoidautre** [comment]
Hi,
```
$ cat /home/vagrant/.pylintrc
disable=locally-disabled, locally-enabled
```

**Comment by thisch** [comment]
Hi, this is an invalid pylint rc file, since it is missing the section headers. Please start with a clean pylintrc file (`pylint --generate-rcfile > ~/.pylintrc`) and adapt it to your needs.

**Comment by quoidautre** [comment]
Thanks, it's working :)

Have a nice day.

**Comment by PCManticore** [comment]
Thank you @thisch for the help! Let's close this one.
