### ISSUE TITLE
Crash involving object attribute that is conditionally a slice

### ISSUE THREAD

**Issue by tomduck** [PyCQA/pylint#3019]
### Steps to reproduce
1. Save the following minimum working example as `demo.py`:

   ```python
   class X():
       def __init__(self, flag):
           if flag:
               self.a = slice(None)
           else:
               self.a = []
               self.a.append(1)
   ```

2. Run `pylint demo.py`

### Current behavior

Pylint crashes with the following trace:

```
Traceback (most recent call last):
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/checkers/typecheck.py", line 876, in visit_attribute
    for n in owner.getattr(node.attrname)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/astroid/node_classes.py", line 3929, in getattr
    return self._proxied.getattr(attrname, context)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/astroid/scoped_nodes.py", line 2368, in getattr
    target=self, attribute=name, context=context
astroid.exceptions.AttributeInferenceError: 'append' not found on <ClassDef.slice l.0 at 0x1024ff978>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomduck/Library/Python/3.7/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  [Previous line repeated 3 more times]
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/checkers/typecheck.py", line 897, in visit_attribute
    ignored_none=self.config.ignore_none,
  File "/Users/tomduck/Library/Python/3.7/lib/python/site-packages/pylint/checkers/typecheck.py", line 402, in _emit_no_member
    if ignored_mixins and owner_name[-5:].lower() == "mixin":
TypeError: 'NoneType' object is not subscriptable
```

Note that if the `slice` in `demo.py` is replaced with an object of another immutable type (e.g., `NoneType`, `int`), then pylint doesn't have a problem.

### Expected behavior

The program is valid, and so pylint shouldn't crash.  Usage demonstration:

```
>>> import demo
>>> x = demo.X(True)
>>> x.a
slice(None, None, None)
>>> x = demo.X(False)
>>> x.a
[1]
```

### pylint --version output

```
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)]
```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by tomduck** [comment]
You're welcome!  Thanks for your work on this project.
