### ISSUE TITLE
pylint 2.3.1 crashes with (astroid) AttributeError: 'Lambda' object has no attribute 'decorators'

### ISSUE THREAD

**Issue by mucisland** [PyCQA/pylint#3091]
## Steps to reproduce
Lint the following code::

    class MyClass():
        fun = lambda self, x: x * 2
        def __init__(self):
            x = self.fun(1) # Crashes pylint 2.3.1
            print(x)

Versions:

    c:\user\dev\pylintbug>pylint --version
    pylint 2.3.1
    astroid 2.2.5
    Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

    c:\user\dev>python -m pip freeze
    astroid==2.2.5
    colorama==0.4.1
    isort==4.3.21
    lazy-object-proxy==1.4.2
    mccabe==0.6.1
    numpy==1.17.1
    Pillow==6.1.0
    pylint==2.3.1
    six==1.12.0
    typed-ast==1.4.0
    wrapt==1.11.2
    wxPython==4.0.6

## Current Behaviour
pylint crashes with the following traceback:

    c:\user\dev\pylintbug>pylint bug.py
    Traceback (most recent call last):
      File "c:\user\apps\python3\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\user\apps\python3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\user\apps\python3\Scripts\pylint.exe\__main__.py", line 9, in <module>
      File "c:\user\apps\python3\lib\site-packages\pylint\__init__.py", line 20, in run_pylint
        Run(sys.argv[1:])
      File "c:\user\apps\python3\lib\site-packages\pylint\lint.py", line 1628, in __init__
        linter.check(args)
      File "c:\user\apps\python3\lib\site-packages\pylint\lint.py", line 943, in check
        self._do_check(files_or_modules)
      File "c:\user\apps\python3\lib\site-packages\pylint\lint.py", line 1075, in _do_check
        self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
      File "c:\user\apps\python3\lib\site-packages\pylint\lint.py", line 1158, in check_astroid_module
        walker.walk(ast_node)
      File "c:\user\apps\python3\lib\site-packages\pylint\utils.py", line 1303, in walk
        self.walk(child)
      File "c:\user\apps\python3\lib\site-packages\pylint\utils.py", line 1303, in walk
        self.walk(child)
      File "c:\user\apps\python3\lib\site-packages\pylint\utils.py", line 1303, in walk
        self.walk(child)
      File "c:\user\apps\python3\lib\site-packages\pylint\utils.py", line 1300, in walk
        cb(astroid)
      File "c:\user\apps\python3\lib\site-packages\pylint\checkers\typecheck.py", line 958, in visit_assign
        and not function_node.decorators
      File "c:\user\apps\python3\lib\site-packages\astroid\bases.py", line 114, in __getattr__
        return getattr(self._proxied, name)
    AttributeError: 'Lambda' object has no attribute 'decorators'

## Expected Behaviour

pylint should not crash.

**Comment by PCManticore** [comment]
Thank you, I can reproduce the issue.
