### ISSUE TITLE
optparse.OptionConflictError: option --logging-modules: conflicting option string(s): --logging-modules

### ISSUE THREAD

**Issue by salrosa** [PyCQA/pylint#3290]
I keep getting an error when running pylint without argument seemingly out of nowhere.

```
Traceback (most recent call last):
  File "/Users/sr/Desktop/environments/automation/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/lint.py", line 1637, in __init__
    linter.load_default_plugins()
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/lint.py", line 645, in load_default_plugins
    checkers.initialize(self)
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/checkers/__init__.py", line 61, in initialize
    register_plugins(linter, __path__[0])
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/utils/utils.py", line 228, in register_plugins
    module.register(linter)
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/checkers/logging 2.py", line 384, in register
    linter.register_checker(LoggingChecker(linter))
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/lint.py", line 759, in register_checker
    self.register_options_provider(checker)
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/config.py", line 542, in register_options_provider
    provider,
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/config.py", line 575, in add_option_group
    self.add_optik_option(provider, group, opt, optdict)
  File "/Users/sr/Desktop/environments/automation/lib/python3.7/site-packages/pylint/config.py", line 579, in add_optik_option
    option = optikcontainer.add_option(*args, **optdict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 983, in _check_conflict
    option)
optparse.OptionConflictError: option --logging-modules: conflicting option string(s): --logging-modules
```

### Steps to reproduce

Not really sure about this. 
I pip upgraded pylint 2.4.2 to 2.4.4.
I ran pylint a few times with no problem and started getting the error above when running pylint with 0 or more arguments.

**Comment by doedotdev** [comment]
I have this same issue. Were you able to resolve this? 

I tried pip uninstalling and trying different versions and could not resolve it.

**Comment by doedotdev** [comment]
After some more investigation it looks like an environment where I installed loguru could have messed with my default logging settings? I just created a new virtualenv and was able to reinstall and it works fine. But that old environment is hosed and I will most likely delete it and recreate...

**Comment by salrosa** [comment]
I tried uninstalling, reinstalling, and changing version and I can not resolve. I may have to make a new environment. It sounds like duplicate command line options named -logging-modules are getting created for pylint. I'm trying to trace the issue in the source code but have not figured anything out yet.

**Comment by timsherwood** [comment]
Have the same (I think) issue.   With a fresh environment it seems to work fine for a while and then, for some unknown reason, all of a sudden the exact same OptionConflictError appears persistently and pylint won't even return the "--help" response.  It is so odd that all of a sudden it just seems to stop working.  I am running `pylint` from `tox`, but even when I use the pylint version installed by tox directly with no options it is hard stuck on this fault.  The only other place pylint is installed is in the .tox directory for the python2.7 checks (which also fail all of a sudden but with a different error).  I have no pylintrc anywhere in the searched paths nor specified in an environment variable. 

Once it wedges, the only option that appears to work is "--version":

```
[Laptop:git PyRTL] [development*]% ./.tox/37/bin/pylint --version
pylint 2.6.0
astroid 2.4.2
Python 3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)]
```
Even "--help" won't work anymore:

```
[Laptop:git PyRTL] [development*] sherwood% .tox/37/bin/pylint --help
Traceback (most recent call last):
  File ".tox/37/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/lint/run.py", line 260, in __init__
    linter.load_default_plugins()
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 475, in load_default_plugins
    checkers.initialize(self)
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/utils/utils.py", line 266, in register_plugins
    module.register(linter)
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/checkers/logging 2.py", line 415, in register
    linter.register_checker(LoggingChecker(linter))
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 589, in register_checker
    self.register_options_provider(checker)
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/config/option_manager_mixin.py", line 99, in register_options_provider
    provider,
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/config/option_manager_mixin.py", line 132, in add_option_group
    self.add_optik_option(provider, group, opt, optdict)
  File "/Users/sherwood/Desktop/work-stuff/GitProjects/PyRTL/.tox/37/lib/python3.7/site-packages/pylint/config/option_manager_mixin.py", line 136, in add_optik_option
    option = optikcontainer.add_option(*args, **optdict)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 983, in _check_conflict
    option)
optparse.OptionConflictError: option --logging-modules: conflicting option string(s): --logging-modules
```

For reference, the total environment includes:
```
alabaster==0.7.12,astroid==2.4.2,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,coverage==5.3,docutils==0.16,idna==2.10,imagesize==1.2.0,isort==5.5.4,Jinja2==2.11.2,lazy-object-proxy==1.4.3,MarkupSafe==1.1.1,mccabe==0.6.1,nose==1.3.7,packaging==20.4,pep8==1.7.1,Pygments==2.7.1,pylint==2.6.0,pyparsing==2.4.7,PyRTL==0.8.7,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==3.2.1,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==1.0.3,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.4,toml==0.10.1,typed-ast==1.4.1,urllib3==1.25.10,wrapt==1.12.1
```

It fails consistently when run directly and I am happy to run any tests necessary to help sort this out.  Thanks!

**Comment by DanielNoord** [comment]
Although this issue is quite old, do any of you know if you are using any of pylint extensions?

**Comment by DanielNoord** [comment]
I'm going to close this as I think this issue has been resolved. Let me know if any issues still persist and I'll reopen!
