### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution' -- python3.8 error

### ISSUE THREAD

**Issue by zesoft23** [PyCQA/pylint#3291]
Hey folks,

This is most likely because Python 3.8 isn't supported yet, but I get this error when trying to `pip install pylint` with python3.8.

```
jthomson@jthomson-t480:~$ sudo python3.8 -m pip install pylint
[sudo] password for jthomson: 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 267, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 93, in user_agent
    zip(["name", "version", "id"], platform.linux_distribution()),
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 242, in main
    with self._build_session(
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 93, in user_agent
    zip(["name", "version", "id"], platform.linux_distribution()),
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

I'm pretty sure this is because ```AttributeError: module 'platform' has no attribute 'linux_distribution'
``` was [deprecated](https://bugs.python.org/issue28167) in python3.5 and finally removed in python3.8.

Is there any expected support date for python3.8? Wanted to let y'all know it's an issue!

**Comment by PCManticore** [comment]
This is coming from pip, not from pylint.

**Comment by zesoft23** [comment]
oops, I'm a dummy thanks! If anyone stumbles upon this, I had an old version of wheels installed and fixed it with

`python3.8 -m pip install --upgrade pip setuptools wheel`

**Comment by Sadegh-Moayedizadeh** [comment]
I want to update pip via ``python3.8 -m pip install --upgrade pip`` but this command also raises the same error!
