### ISSUE TITLE
Pylint --version displaying errors

### ISSUE THREAD

**Issue by AmmeonSupport** [PyCQA/pylint#3333]
After installing pylint==1.1.0 and then checking the version we get the following output

We are using CentOS 7

[root@3SZ1HC2 ~]# pylint --version
Traceback (most recent call last):
  File "/bin/pylint", line 9, in <module>
    load_entry_point('pylint==1.1.0', 'console_scripts', 'pylint')()
  File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    from pylint.lint import Run
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 30, in <module>
    from pylint.checkers import utils
  File "/usr/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 46, in <module>
    from astroid.utils import ASTWalker
  File "/usr/lib/python2.7/site-packages/astroid/__init__.py", line 54, in <module>
    from astroid.nodes import *
  File "/usr/lib/python2.7/site-packages/astroid/nodes.py", line 48, in <module>
    from astroid.scoped_nodes import Module, GenExpr, Lambda, DictComp, \
  File "/usr/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 33, in <module>
    from logilab.common.compat import builtins
  File "/usr/lib/python2.7/site-packages/logilab/common/compat.py", line 38, in <module>
    import builtins
ImportError: No module named builtins

Tried upgrading pip, removing pylint and reinstalling. No joy. any suggestions would be much appreciated!

**Comment by PCManticore** [comment]
Hey @AmmeonSupport Pylint 1.1 is not supported, you'll need to update to the latest 2.X releases.
