### ISSUE TITLE
Pylint  --version throws TypeError:issubclass() arg 1 must be a class  

### ISSUE THREAD

**Issue by nikhilkarmude** [PyCQA/pylint#3357]
### Steps to reproduce
My System configurations are- Windows 10 (64 bit), Python 3.5.0 (32 Bit)
1. pip install pylint 
```
   Requirement already satisfied: mccabe<0.7,>=0.6 in c:\program files (x86)\python 3.5\lib\site-packages (from pylint) (0.6.1)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\program files (x86)\python 3.5\lib\site-packages (from pylint) (0.4.3)
Requirement already satisfied: isort<5,>=4.2.5 in c:\program files (x86)\python 3.5\lib\site-packages (from pylint) (4.3.21)
Requirement already satisfied: astroid<2.4,>=2.3.0 in c:\program files (x86)\python 3.5\lib\site-packages (from pylint) (2.3.3)
Requirement already satisfied: lazy-object-proxy==1.4.* in c:\program files (x86)\python 3.5\lib\site-packages (from astroid<2.4,>=2.3.0->pylint) (1.4.3)
Requirement already satisfied: wrapt==1.11.* in c:\program files (x86)\python 3.5\lib\site-packages (from astroid<2.4,>=2.3.0->pylint) (1.11.2)
Requirement already satisfied: six~=1.12 in c:\program files (x86)\python 3.5\lib\site-packages (from astroid<2.4,>=2.3.0->pylint) (1.13.0)
Requirement already satisfied: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in c:\program files (x86)\python 3.5\lib\site-packages (from astroid<2.4,>=2.3.0->pylint) (1.4.1)
Installing collected packages: pylint
Successfully installed pylint-2.4.4
```
2. pylint --version

### Current behavior
```
C:\>pylint --version
Traceback (most recent call last):
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python 3.5\Scripts\pylint.exe\__main__.py", line 4, in <module>
  File "c:\program files (x86)\python 3.5\lib\site-packages\pylint\__init__.py", line 16, in <module>
    from pylint.pyreverse.main import Run as PyreverseRun
  File "c:\program files (x86)\python 3.5\lib\site-packages\pylint\pyreverse\main.py", line 22, in <module>
    from pylint.pyreverse.diadefslib import DiadefsHandler
  File "c:\program files (x86)\python 3.5\lib\site-packages\pylint\pyreverse\diadefslib.py", line 22, in <module>
    from pylint.pyreverse.diagrams import ClassDiagram, PackageDiagram
  File "c:\program files (x86)\python 3.5\lib\site-packages\pylint\pyreverse\diagrams.py", line 16, in <module>
    from pylint.checkers.utils import decorated_with_property
  File "c:\program files (x86)\python 3.5\lib\site-packages\pylint\checkers\utils.py", line 626, in <module>
    def is_attr_private(attrname: str) -> Optional[Match[str]]:
  File "c:\program files (x86)\python 3.5\lib\typing.py", line 631, in __getitem__
    return Union[arg, type(None)]
  File "c:\program files (x86)\python 3.5\lib\typing.py", line 534, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "c:\program files (x86)\python 3.5\lib\typing.py", line 491, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "c:\program files (x86)\python 3.5\lib\typing.py", line 491, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
**TypeError: issubclass() arg 1 must be a class**
```

### Expected behavior
pylint version should be displayed in console.

### pylint --version output
Getting exception for same command.

### Following are installed python packages: pip list
```
Package             Version
------------------- ----------
adodbapi            2.6.2.0
aniso8601           8.0.0
astroid             2.3.3
bandit              1.6.2
beautifulsoup4      4.8.2
bs4                 0.0.1
certifi             2019.11.28
cffi                1.13.2
chardet             3.0.4
Click               7.0
colorama            0.4.3
colorclass          2.2.0
configparser        4.0.2
cryptography        2.8
DateTime            4.3
dicttoxml           1.7.4
easygui             0.98.1
enum34              1.1.6
et-xmlfile          1.0.1
Flask               1.1.1
Flask-Jsonpify      1.5.0
Flask-RESTful       0.3.7
gitdb2              2.0.6
GitPython           3.0.5
idna                2.8
isodate             0.6.0
isort               4.3.21
itsdangerous        1.1.0
jdcal               1.4.1
Jinja2              2.10.3
lazy-object-proxy   1.4.3
lxml                4.4.2
MarkupSafe          1.1.1
mccabe              0.6.1
msoffcrypto-tool    4.10.1
numpy               1.17.4
olefile             0.46
oletools            0.55.1
openpyxl            2.6.4
panda               0.3.1
pandas              0.24.2
pbr                 5.4.4
pcodedmp            1.2.6
pip                 19.3.1
pycparser           2.19
pylint              2.4.4
pyodbc              4.0.27
pyparsing           2.3.0
python-dateutil     2.8.1
pytz                2019.3
pywin32             227
PyYAML              5.3
requests            2.22.0
schedule            0.6.0
setuptools          18.2
six                 1.13.0
smmap2              2.0.5
soupsieve           1.9.5
SQLAlchemy          1.3.11
stevedore           1.31.0
typed-ast           1.4.1
typing              3.7.4.1
urllib3             1.25.7
Werkzeug            0.16.0
win-unicode-console 0.5
wrapt               1.11.2
xlrd                1.2.0
XlsxWriter          1.2.6
xmltodict           0.12.0
zope.interface      4.7.1
```

**Comment by PCManticore** [comment]
Thanks for the report. I'm not entirely sure this comes from `pylint` itself, it looks to me that it's a `typing` issue, probably related to Python 3.5 as well. I'm afraid I can't help much with this.

**Comment by justXiLiu** [comment]
I had the same problem and found out it is related to python3.5.0. I switched to py3.5.6 and py3.6, `pylint --version` didn't cause such error.
