### ISSUE TITLE
Crash in _inference_tip_cached for a particular script

### ISSUE THREAD

**Issue by mjkramer** [PyCQA/pylint#3359]
### Steps to reproduce
1. Put the following nonsense (extracted from a real-world script that causes the same crash) in `crash_pylint.py`. Further removal of any line/block will prevent the crash.
```python
def get_runtime(logfile):
    read_stamp = lambda line: int(line.split()[2])
    for line in open(logfile):
        if line.startswith('Beginning at '):
            beg = read_stamp(line)
        elif line.startswith('Ending at '):
            end = read_stamp(line)
    if None in [beg, end]:
        return None
    return end - beg

def dump_times(bmId: BenchmarkId):
    for d in dirs:
        runtime = get_runtime(logfiles[0])
        if runtime == None:
            score = "SLOW"
```
2. `pylint crash_pylint.py`

### Current behavior

Get the following output:

```
************* Module crash_pylint
crash_pylint.py:1:0: C0114: Missing module docstring (missing-module-docstring)
crash_pylint.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
crash_pylint.py:12:0: C0103: Argument name "bmId" doesn't conform to snake_case naming style (invalid-name)
crash_pylint.py:12:0: C0116: Missing function or method docstring (missing-function-docstring)
crash_pylint.py:12:21: E0602: Undefined variable 'BenchmarkId' (undefined-variable)
crash_pylint.py:13:8: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
crash_pylint.py:13:13: E0602: Undefined variable 'dirs' (undefined-variable)
crash_pylint.py:14:30: E0602: Undefined variable 'logfiles' (undefined-variable)
Traceback (most recent call last):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7f9218b6b9d0>, <Call l.2 at 0x7f92187faf10>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/inference.py", line 227, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 1210, in infer_call_result
    return self.body.infer(context)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/node_classes.py", line 353, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/__init__.py", line 93, in _inference_tip_cached
    result = func(*args, **kwargs)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/brain/brain_builtin_inference.py", line 129, in _transform_wrapper
    result = transform(node, context=context)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/brain/brain_builtin_inference.py", line 716, in infer_int
    first_value = next(call.positional_arguments[0].infer(context=context))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mkramer/tmp/pylint/pylint_venv/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/lint.py", line 1731, in __init__
    linter.check(args)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/lint.py", line 1004, in check
    self._do_check(files_or_modules)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/lint.py", line 1165, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/lint.py", line 1252, in check_astroid_module
    walker.walk(ast_node)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/checkers/base.py", line 2273, in visit_compare
    self._check_callable_comparison(node)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/checkers/base.py", line 2255, in _check_callable_comparison
    sum(
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/checkers/base.py", line 2258, in <genexpr>
    if isinstance(utils.safe_infer(operand), bare_callables)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/pylint/checkers/utils.py", line 1088, in safe_infer
    next(inferit)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 141, in raise_if_nothing_inferred
    yield from generator
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/bases.py", line 133, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 141, in raise_if_nothing_inferred
    yield from generator
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/bases.py", line 133, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 141, in raise_if_nothing_inferred
    yield from generator
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/inference.py", line 227, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 1677, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 117, in yes_if_nothing_inferred
    yield next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/inference.py", line 468, in _filter_operation_errors
    for result in infer_callable(self, context):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/inference.py", line 754, in _infer_binop
    for lhs, rhs in itertools.product(lhs_iter, rhs_iter):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/bases.py", line 133, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/bases.py", line 133, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/mkramer/tmp/pylint/pylint_venv/lib/python3.8/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
RuntimeError: generator raised StopIteration
```

### Expected behavior

No crash

### pylint --version output

Tried preview release on Python 3.8.1, 2.4.4 on 3.8.1, and 2.3.1 on 3.7.3:
```
# Same for preview and 2.4.4:
pylint 2.4.4
astroid 2.3.3
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0]

# For 2.3.1:
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by PCManticore** [comment]
The crash seems to be gone with the next release of astroid, namely:
```
pylint 2.5.0-dev1
astroid 2.4.0
Python 3.8.1 (default, Feb 13 2020, 10:17:07)
[Clang 8.1.0 (clang-802.0.42)]
```
