### ISSUE TITLE
Pylint still requiring pylint_common 

### ISSUE THREAD

**Issue by markmiscavage** [PyCQA/pylint#3440]
I'm running python 3.7.6 installed via pyenv. 

pylint==2.4.4
astroid==2.3.3

`$ pylint
Traceback (most recent call last):
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 1686, in __init__
    linter.load_plugin_modules(plugins)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 660, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/astroid/modutils.py", line 198, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/astroid/modutils.py", line 240, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/Users/mark.miscavage/.pyenv/versions/3.7.6/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'pylint_common'`

If I pip install pylint_common, and pylint_django then calling `pylint` from the command line works. But when I try to run pylint via SublimeLinter I end up with 

`Traceback (most recent call last):
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 1731, in __init__
    linter.check(args)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 1004, in check
    self._do_check(files_or_modules)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 1165, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/lint.py", line 1252, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 55, in augment_func
    augmentation(chain, node)
  File "/Users/mark.miscavage/workspace/ship-compliant-proxy/env/lib/python3.7/site-packages/pylint_common/augmentations.py", line 23, in allow_attribute_comments
    isinstance(node.parent, (astroid.Class, astroid.Module)) and \
AttributeError: module 'astroid' has no attribute 'Class'`

This seems like a circular problem with versions but I'm not sure what set of things works. Has anyone else run into this and can help?

**Comment by PCManticore** [comment]
`pylint` does not use `pylint_common` at all. That is a `pylint-django` dependency if I recall right and this issue should be reported to them. You might have it in your `pylintrc` file somewhere as from the traceback it seems to be triggered when loading the plugins with `load_plugin_modules`.
