### ISSUE TITLE
Execution Error encountered linting by file name

### ISSUE THREAD

**Issue by scottfurry** [PyCQA/pylint#3513]
### Steps to reproduce
1. latest commit of pylint installed
2. cd into project folder
3. execute 'pylint [filename]'

### Current behavior
Following error message is produced on the command line:
```
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.5.0.dev1', 'console_scripts', 'pylint')()
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/lint.py", line 1786, in __init__
    linter.check(args)
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/lint.py", line 976, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/lint.py", line 1008, in _check_files
    for name, filepath, modname in file_descrs:
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/lint.py", line 1065, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules):
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/lint.py", line 1074, in _expand_files
    modules, self.config.black_list, self.config.black_list_re
  File "/usr/lib64/python3.7/site-packages/pylint-2.5.0.dev1-py3.7.egg/pylint/utils/utils.py", line 150, in expand_modules
    modutils.modpath_from_file(something, path=additional_search_path)
TypeError: modpath_from_file() got an unexpected keyword argument 'path'
```
### Expected behavior
Normal execution and output indicating results of linting a single file

### pylint --version output
```
pylint --version
pylint 2.5.0-dev1
astroid 2.3.3
Python 3.7.6 (default, Apr  6 2020, 13:28:26) 
[GCC 9.2.0]
```
commit hash installed: 0ccf1bca9fcd889e7f5ac85cc06098614d9e8ca3

**Comment by scottfurry** [comment]
Problem persists after refactoring applied by commits leading up to and including commit 9a11ae2cc9b20d6f570f5a3e410354902ef818b2.

Calling `pylint [args] [files]` produces error trace shown above.
Calling `python -m pylint [args] [files]` seems to be the only way to execute pylint at the moment.

**Comment by PCManticore** [comment]
Hey @scottfurry Thanks for opening an issue. You need to install `astroid` from the master branch for `pylint` to work correctly since the new release of `pylint` depends on some changes done in the  next release of `astroid`.

**Comment by scottfurry** [comment]
@PCManticore - yup. Looks like bumping astroid fixed things.
For future reference - and for others to "LFMF" (learn from my fail), would it not be prudent to bump astroid revision required? Pip should have caught this (and circumvented the whole issue).
Yes? Patch to fix going forward below.
```
diff --git a/pylint/__pkginfo__.py b/pylint/__pkginfo__.py
index 90312fd4..feb551fe 100644
--- a/pylint/__pkginfo__.py
+++ b/pylint/__pkginfo__.py
@@ -30,7 +30,7 @@ if dev_version is not None:
     version += "-dev" + str(dev_version)
 
 install_requires = [
-    "astroid>=2.3.0,<=2.5",
+    "astroid>=2.4.0,<=2.5",
     "isort>=4.2.5,<5",
     "mccabe>=0.6,<0.7",
     "toml>=0.7.1",
```
