### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'exit'

### ISSUE THREAD

**Issue by susz007** [PyCQA/pylint#3533]
### Steps to reproduce
1. python manage.py jenkins --enable-coverage
2.
3.

### Current behavior

(venv) D:\Repository\GIT\VICAS\api>python manage.py jenkins --enable-coverage
System check identified no issues (0 silenced).
............................
----------------------------------------------------------------------
Ran 28 tests in 239.656s

OK
Storing coverage info...
Executing django_jenkins.tasks.run_pylint...
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django_jenkins\management\commands\jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django_jenkins\management\commands\jenkins.py", line 116, in handle
    coverage.save(tested_locations, options)
  File "D:\Repository\GIT\VICAS\api\venv\lib\site-packages\django_jenkins\tasks\run_pylint.py", line 44, in run
    lint.Run(args, reporter=ParseableTextReporter(output=output), exit=False)
TypeError: __init__() got an unexpected keyword argument 'exit'

### Expected behavior

(venv) D:\Repository\GIT\VICAS\api>python manage.py jenkins --enable-coverage
System check identified no issues (0 silenced).
............................
----------------------------------------------------------------------
Ran 28 tests in 242.236s

OK
Storing coverage info...
Executing django_jenkins.tasks.run_pylint...
Done

### pylint --version output
2.4

FIX
    I fixed the file manually by changing **run_pylint.py**
                 
       ` lint.Run(args, reporter=ParseableTextReporter(output=output), exit=False)`

changed to 
        
       ` lint.Run(args, reporter=ParseableTextReporter(output=output), do_exit=False)
`

**Comment by PCManticore** [comment]
Thank you for the report! This should be fixed with 2.5.1 once this PR lands https://github.com/PyCQA/pylint/pull/3554.
