### ISSUE TITLE
-j0 option broken in pylint 2.5.0  - ImportError: Unable to find module .... in sys.path

### ISSUE THREAD

**Issue by crisbal** [PyCQA/pylint#3543]
Hello, the `-j0` option is broken in pylint 2.5.0
This also breaks with any j > 1, thus when multiprocessing is enabled. 

### Steps to reproduce

```bash
# setup venv
cd /tmp
python -m venv venv
source venv/bin/activate
# install
pip install 'pylint==2.5.0'
# create some files
mkdir package
touch package/__init__.py
touch package/file.py
mkdir package/subpackage
touch package/subpackage/__init__.py
```

### Current behavior
```bash
pylint --version
# pylint 2.5.0
# astroid 2.4.0
pylint -j0 ./package
```
Outputs the following:

```
Traceback (most recent call last):
  File "/tmp/venv/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/tmp/venv/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/tmp/venv/lib/python3.8/site-packages/pylint/lint/run.py", line 338, in __init__
    linter.check(args)
  File "/tmp/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 874, in check
    check_parallel(
  File "/tmp/venv/lib/python3.8/site-packages/pylint/lint/check_parallel.py", line 100, in check_parallel
    for module, messages, stats, msg_status in pool.imap_unordered(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
ImportError: Unable to find module for package/file.py in /tmp/venv/bin, 
/usr/lib/python38.zip, 
/usr/lib/python3.8, 
/usr/lib/python3.8/lib-dynload, 
/tmp/venv/lib/python3.8/site-packages, 
/tmp/venv/lib/python3.8/site-packages/astroid/brain
```

Running:

```bash
pylint  ./package
# no output, it works
```

### Expected behavior

In version pylint-2.4.4/astroid-2.3.3 it was working fine.

```bash
pip install 'pylint==2.4.4'
pylint --version
# pylint 2.4.4
# astroid 2.3.3
pylint -j0 ./package
# no output, it works
```
### pylint --version output

```
pylint 2.5.0
astroid 2.4.0
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]
```

**Comment by crisbal** [comment]
Duplicate of #3524
