### ISSUE TITLE
Running Pylint@2.5.0 on single file throws TypeError

### ISSUE THREAD

**Issue by TaraWilson17** [PyCQA/pylint#3552]
### Steps to reproduce
1. Write simple python script called `test.py`
2. run `pylint test.py` from command prompt
3. run into TypeError:

Traceback (most recent call last):
  File "/home/wwtara/miniconda/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/lint/run.py", line 338, in __init__
    linter.check(args)
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 903, in _check_files
    for name, filepath, modname in file_descrs:
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 960, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules):
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 969, in _expand_files
    modules, self.config.black_list, self.config.black_list_re
  File "/home/wwtara/miniconda/lib/python3.7/site-packages/pylint/utils/utils.py", line 150, in expand_modules
    modutils.modpath_from_file(something, path=additional_search_path)
TypeError: modpath_from_file() got an unexpected keyword argument 'path'

### pylint --version output
`pylint 2.5.0`
`astroid 2.3.3`
`Python 3.7.6`

### Temp resolution
Reverting to `pylint 2.4.4` solved the issue.

**Comment by PCManticore** [comment]
Thanks for the report. You probably have `astroid` pinned, but installing pylint 2.5.0 should update your astroid version to 2.4.0, which solves this error you are seeing.
