### ISSUE TITLE
PyLint depends on Toml but it is not declared on setup.py?

### ISSUE THREAD

**Issue by goanpeca** [PyCQA/pylint#3553]
Hello, I am core dev with Spyder and we started seeing some issue that said:

```python-traceback
"File "C:\Users\ssegal\Anaconda3\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in
import pylint.config
File "C:\Users\ssegal\Anaconda3\lib\site-packages\pylint\config.py", line 54, in
import toml
ModuleNotFoundError: No module named 'toml'"
```

I was wondering if we have a missing dependency?

### Current behavior
ModuleNotFoundError: No module named 'toml'"

### Expected behavior
No error

**Comment by PCManticore** [comment]
Not sure how you did the update to 2.5, but we do depend on `toml` https://github.com/PyCQA/pylint/blob/4bae2af51ee8685abbbaf4f4d0f2027771d2b421/pylint/__pkginfo__.py#L42

**Comment by goanpeca** [comment]
Hi, yes it is a problem with conda packages that did not include the toml dependency. 

Sorry for the noise!

**Comment by contrivable** [comment]
Additionally, `astroid` dependency is wrong. conda thinks it should be `astroid >=2.3.0,<2.4` when `astroid >=2.4.0` is needed. I guess, a newer build needs to be uploaded to conda repo(s).
```
$ conda search --info pylint==2.5.0=py37_0
Loading channels: done
pylint 2.5.0 py37_0
-------------------
file name   : pylint-2.5.0-py37_0.conda
name        : pylint
version     : 2.5.0
build       : py37_0
build number: 0
size        : 443 KB
license     : GPL 2
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/pylint-2.5.0-py37_0.conda
md5         : ba389bea3b918474aee9a9f3cad1a842
timestamp   : 2020-04-30 00:44:35 UTC
dependencies: 
  - astroid >=2.3.0,<2.4
  - isort >=4.2.5,<5
  - mccabe >=0.6,<0.7
  - python >=3.7,<3.8.0a0
```

Same for py36 and py38.

Steps to Recreate
-----------------
```
$ cat > mvp-pylint.yaml << EOM
name: mvp-pylint
dependencies:
  - python==3.7.3
  - pylint==2.5.0
  - toml
EOM
$ conda env create --file mvp-pylint.yaml
$ conda activate mvp-pylint
(mvp-pylint) $ pylint --version
pylint 2.5.0
astroid 2.3.3
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
$ pylint .
Traceback (most recent call last):
  File "USERHOME/miniconda3/envs/mvp-pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/run.py", line 338, in __init__
    linter.check(args)
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 903, in _check_files
    for name, filepath, modname in file_descrs:
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 960, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules):
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 969, in _expand_files
    modules, self.config.black_list, self.config.black_list_re
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/utils/utils.py", line 150, in expand_modules
    modutils.modpath_from_file(something, path=additional_search_path)
TypeError: modpath_from_file() got an unexpected keyword argument 'path'
```

Side note, without `toml` I cannot even get versions `pylint`:
```
$ pylint --version
Traceback (most recent call last):
  File "USERHOME/miniconda3/envs/mvp-pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/__init__.py", line 19, in run_pylint
    from pylint.lint import Run as PylintRun
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.pylinter import PyLinter
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 20, in <module>
    from pylint import checkers, config, exceptions, interfaces, reporters
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/checkers/__init__.py", line 45, in <module>
    from pylint.checkers.base_checker import BaseChecker, BaseTokenChecker
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/checkers/base_checker.py", line 20, in <module>
    from pylint.config import OptionsProviderMixIn
  File "USERHOME/miniconda3/envs/mvp-pylint/lib/python3.7/site-packages/pylint/config.py", line 54, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

**Comment by PCManticore** [comment]
I'm sorry, this should be moved to conda's issue tracker. I never interacted with conda or with conda builds.

**Comment by contrivable** [comment]
Would you happen to know whether https://github.com/conda/conda/issues is the correct tracker?

**Comment by contrivable** [comment]
For posterity, conda seems to collect package dependencies in `repodata.json` - see [main/linux-64 repo](https://repo.anaconda.com/pkgs/main/linux-64/).

redodata.json has the outdated dependencies. Checking the distributed package `pylint-2.5.0-py37_0.tar.bz2` we find `info/recipe/meta.yaml` also with outdated dependencies.
So, it's not a conda problem but a recipe problem. 

meta.yaml has a field `recipe-maintainers`.
This led to finding a PR for the toml and astroid problems here - https://github.com/conda-forge/pylint-feedstock/pull/42 - also revealing [conda-forge/pylint-feedstock](https://github.com/conda-forge/pylint-feedstock) as the repo of pylint's conda recipe maintenance.
