### ISSUE TITLE
astroid/rebuilder.py: KeyError: <class '_ast.Is'> running pylint

### ISSUE THREAD

**Issue by raymond-grointel** [PyCQA/pylint#3558]
Downgrading `astroid` from 2.4.0 to 2.3.2 fixes the issue.

### Steps to reproduce

1. Update `pylint` 
2. Run `pylint`

### Current behavior

```
Traceback (most recent call last):
  File "/venvs/venv3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/run.py", line 338, in __init__
    linter.check(args)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 1218, in visit_call
    called = safe_infer(node.func)
  File "/venvs/venv3/lib/python3.6/site-packages/pylint/checkers/utils.py", line 1119, in safe_infer
    value = next(infer_gen)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 319, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 273, in infer_import_from    module = self.do_import_module()
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 225, in delayed_assattr
    for inferred in node.expr.infer():
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 227, in infer_call
    for callee in self.func.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 319, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 273, in infer_import_from
    module = self.do_import_module()
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 225, in delayed_assattr
    for inferred in node.expr.infer():
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 227, in infer_call
    for callee in self.func.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 293, in infer_attribute
    for owner in self.expr.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 850, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/protocols.py", line 391, in assign_assigned_stmts
    self.value.infer(context), assign_path, context
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/protocols.py", line 414, in _resolve_assignment_parts
    for part in parts:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 293, in infer_attribute
    for owner in self.expr.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 293, in infer_attribute
    for owner in self.expr.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 227, in infer_call
    for callee in self.func.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 293, in infer_attribute
    for owner in self.expr.infer(context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 850, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/protocols.py", line 331, in _arguments_infer_argname
    is_metaclass = isinstance(cls, nodes.ClassDef) and cls.type == "metaclass"
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1830, in _class_type
    if _is_metaclass(klass):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1799, in _is_metaclass
    for baseobj in base.infer():
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 273, in infer_import_from
    module = self.do_import_module()
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 225, in delayed_assattr
    for inferred in node.expr.infer():
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 850, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/protocols.py", line 331, in _arguments_infer_argname
    is_metaclass = isinstance(cls, nodes.ClassDef) and cls.type == "metaclass"
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1830, in _class_type
    if _is_metaclass(klass):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1799, in _is_metaclass
    for baseobj in base.infer():
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/inference.py", line 273, in infer_import_from
    module = self.do_import_module()
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 137, in file_build
    module = self._data_build(data, modname, path)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/builder.py", line 190, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in visit_module
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in <listcomp>
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 177, in visit
    return visit_method(node, parent)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 455, in visit_classdef
    [self.visit(child, newnode) for child in node.body],
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 455, in <listcomp>
    [self.visit(child, newnode) for child in node.body],
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 177, in visit
    return visit_method(node, parent)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 676, in visit_functiondef
    return self._visit_functiondef(nodes.FunctionDef, node, parent)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 666, in _visit_functiondef
    body=[self.visit(child, newnode) for child in node.body],
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 666, in <listcomp>
    body=[self.visit(child, newnode) for child in node.body],
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 177, in visit
    return visit_method(node, parent)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 721, in visit_if
    self.visit(node.test, newnode),
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 177, in visit
    return visit_method(node, parent)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 489, in visit_compare
    for (op, expr) in zip(node.ops, node.comparators)
  File "/venvs/venv3/lib/python3.6/site-packages/astroid/rebuilder.py", line 489, in <listcomp>
    for (op, expr) in zip(node.ops, node.comparators)
KeyError: <class '_ast.Is'>
```

### Expected behavior

```
------------------------------------
Your code has been rated at 10.00/10
```

### pylint --version output

```
pylint 2.5.0
astroid 2.4.0
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
```

**Comment by raymond-grointel** [comment]
Maybe related to #3540?

**Comment by Pierre-Sassoulas** [comment]
Yes look like a duplicate, could you try with Astroid  `2.4.1` ?

**Comment by raymond-grointel** [comment]
not on pypi yet https://pypi.org/project/astroid/#history

**Comment by raymond-grointel** [comment]
will test against astroid master

**Comment by raymond-grointel** [comment]
Ok - it works with `pylint` 2.5.0 the latest `astroid` master @ e40ac59 `pip install 'git+git://github.com/PyCQA/astroid@e40ac59'`

**Comment by Pierre-Sassoulas** [comment]
Thank you for the report and for the time you took to test it again :) !
