### ISSUE TITLE
REGRESSION: logging-format-style support for fstr broken

### ISSUE THREAD

**Issue by ahonnecke** [PyCQA/pylint#3570]
## Bug
If this isn't a bug, then I would like it to be a feature request.

### Steps to reproduce
1. Install 2.5.0 (or --pre)
2. set fstr as the logging-format-style in .pylintrc
3. execute pylint on any file, or even just ask for the version

### Current behavior
Throws an exception

#### style=fstr
```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ cat .pylintrc | grep logging
logging-format-style=fstr
```
```
Traceback (most recent call last):
  File "/home/ahonnecke/.local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/lint/run.py", line 300, in __init__
    linter.load_config_file()
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 787, in load_config_file
    self.global_set_option(option, value)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 668, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 880, in set_option
    value = _validate(value, optdict, optname)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 273, in _validate
    return _call_validator(_type, optdict, name, value)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 254, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 242, in <lambda>
    "choice": lambda opt, name, value: _choice_validator(opt["choices"], name, value),
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 196, in _choice_validator
    raise optparse.OptionValueError(msg % (name, value, choices))
optparse.OptionValueError: option logging-format-style: invalid value: 'fstr', should be in ['old', 'new']
```

#### style=new

```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ cat .pylintrc | grep logging
logging-format-style=new
```

```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ pylint ./serverless/utils/scraper.py
SNIP
------------------------------------------------------------------
Your code has been rated at 7.30/10 (previous run: 6.64/10, +0.66)
```

### pylint --version output
```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ pylint --version
pylint 2.5.0
astroid 2.4.0
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
```

### Expected behavior
Accepts fstr the same way 2.4.2 does

### 2.4.2

```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ cat .pylintrc | grep logging
logging-format-style=fstr
```

```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ pip install pylint==2.4.2 --user
Collecting pylint==2.4.2
  Using cached pylint-2.4.2-py3-none-any.whl (302 kB)
Requirement already satisfied: mccabe<0.7,>=0.6 in /home/ahonnecke/.local/lib/python3.8/site-packages (from pylint==2.4.2) (0.6.1)
Collecting astroid<2.4,>=2.3.0
  Using cached astroid-2.3.3-py3-none-any.whl (205 kB)
Requirement already satisfied: isort<5,>=4.2.5 in /home/ahonnecke/.local/lib/python3.8/site-packages (from pylint==2.4.2) (4.3.21)
Requirement already satisfied: lazy-object-proxy==1.4.* in /home/ahonnecke/.local/lib/python3.8/site-packages (from astroid<2.4,>=2.3.0->pylint==2.4.2) (1.4.3)
Requirement already satisfied: wrapt==1.11.* in /usr/lib/python3/dist-packages (from astroid<2.4,>=2.3.0->pylint==2.4.2) (1.11.2)
Requirement already satisfied: six~=1.12 in /usr/lib/python3/dist-packages (from astroid<2.4,>=2.3.0->pylint==2.4.2) (1.14.0)
Installing collected packages: astroid, pylint
  Attempting uninstall: astroid
    Found existing installation: astroid 2.4.0
    Uninstalling astroid-2.4.0:
      Successfully uninstalled astroid-2.4.0
  Attempting uninstall: pylint
    Found existing installation: pylint 2.5.0
    Uninstalling pylint-2.5.0:
      Successfully uninstalled pylint-2.5.0
Successfully installed astroid-2.3.3 pylint-2.4.2
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ pylint ./serverless/utils/scraper.py 
SNIP
------------------------------------------------------------------
Your code has been rated at 7.30/10 (previous run: 7.30/10, +0.00)
```
```
ahonnecke@homonym:~/src/web3/web3-maker-scraper$ pylint --version
pylint 2.4.2
astroid 2.3.3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
```

**Comment by PCManticore** [comment]
Thanks for the report. Please read the last release entry from http://pylint.pycqa.org/en/latest/whatsnew/2.5.html. The `fstr` option for `logging-format-style` is gone and instead you need to manually disable `logging-fstring-interpolation` if you want to use f-strings for logging.

**Comment by IceflowRE** [comment]
@PCManticore how to enable disable `logging-fstring-interpolation` in setup.cfg?

**Comment by koffie** [comment]
@IceflowRE 
[pylint.FORMAT]
disable=logging-fstring-interpolation

**Comment by eduarhit** [comment]
so does that mean that format.{} is preferred and not f"{}" for string formatting in log messages?

**Comment by Pierre-Sassoulas** [comment]
No it's either f-strings or [lazy interpolation](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-format-interpolation.html) depending on your preferred configuration.
