### ISSUE TITLE
Bug with pyreverse if random.Random() is used

### ISSUE THREAD

**Issue by glefebvr** [PyCQA/pylint#3589]
I start from the following code, in a file named test.py:

```
import random

class randompick():    
    def __init__(self):
        self.rrand = random.Random()
```
I want need a class diagram.  Usually, I use the following command to build a file classes.gv :
`Pyreverse -o gv -A -my -S test.py`

But run this command raises an error:
```
parsing popcell\utils\test.py...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\pyreverse-script.py", line 10, in <module>
    sys.exit(run_pyreverse())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\__init__.py", line 37, in run_pyreverse
    PyreverseRun(sys.argv[1:])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\pyreverse\main.py", line 184, in __init__
    sys.exit(self.run(args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\pyreverse\main.py", line 209, in run
    writer.DotWriter(self.config).write(diadefs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\pyreverse\writer.py", line 38, in write
    self.write_classes(diagram)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\pyreverse\writer.py", line 59, in write_classes
    self.printer.emit_node(i, **self.get_values(obj))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\pyreverse\writer.py", line 134, in get_values
    args = [arg.name for arg in func.args.args if arg.name != "self"]
TypeError: 'NoneType' object is not iterable
```

It is probably a regression, because I'm almost certainly this code have been works with an older version (before v2 I think).

My configuration:
>>> pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by PCManticore** [comment]
This has been fixed in pylint 2.5, please update and let us know if you can still reproduce it.
