### ISSUE TITLE
Pylint crash

### ISSUE THREAD

**Issue by SamyCookie** [PyCQA/pylint#3690]
Hi !

### Steps to reproduce
1. crash when linting on our private code

### Current behavior
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/check_parallel.py", line 69, in _worker_check_single_file
    _worker_linter.check_single_file(name, filepath, modname)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 890, in check_single_file
    self.get_ast, check_astroid_module, name, filepath, modname
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/checkers/base.py", line 1091, in visit_if
    self._check_using_constant_test(node, node.test)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/checkers/base.py", line 1138, in _check_using_constant_test
    call_inferred = inferred.infer_call_result()
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/astroid/objects.py", line 311, in infer_call_result
    raise exceptions.InferenceError("Properties are not callable")
astroid.exceptions.InferenceError: Properties are not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samuel/venv/buster/pylint/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 878, in check
    files_or_modules,
  File "/home/samuel/venv/buster/pylint/lib/python3.7/site-packages/pylint/lint/check_parallel.py", line 102, in check_parallel
    _worker_check_single_file, files
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
astroid.exceptions.InferenceError: Properties are not callable
*** [comscope_lint] Error code 1
```

### Expected behavior
No crash

### pylint --version output
pylint 2.5.3
astroid 2.4.2
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]

That code was previouly perfectly linted with Pylint 2.4.4 with no crash.

Have fun ;)

**Comment by PCManticore** [comment]
Can you provide a minimal reproduction example?

**Comment by SamyCookie** [comment]
Of course, I should do this at the first beginning.

```python
class A:
    @property
    @classmethod
    def b(cls):
        return 42
if A.b:
    pass
```

**Comment by SamyCookie** [comment]
even more minimal, but not very functional code:
```python
class A:
    @property
    def b():
        return 42
if A.b:
    pass
```

**Comment by brycepg** [comment]
Thanks @SamyCookie, I can reproduce

**Comment by brycepg** [comment]
The regression is occuring somehwere between `astroid==2.4.0` and `astroid==2.3.3`

**Comment by SamyCookie** [comment]
Awesome, thanks !

**Comment by pylint** [comment]
I'm not a pylint maintainer. I was a bot.
