### ISSUE TITLE
Traceback on unknown encoding

### ISSUE THREAD

**Issue by jwilk** [PyCQA/pylint#3860]
### Steps to reproduce

Run Pylint against the following code:
```python
# encoding=UTF-9
```

### Current behavior

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.7/tokenize.py", line 397, in find_cookie
    codec = lookup(encoding)
LookupError: unknown encoding: UTF-9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jwilk/.local/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 863, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 895, in _check_files
    for name, filepath, modname in file_descrs:
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 952, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules):
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 961, in _expand_files
    modules, self.config.black_list, self.config.black_list_re
  File "/home/jwilk/.local/lib/python3.7/site-packages/pylint/utils/utils.py", line 187, in expand_modules
    modparts, path=additional_search_path
  File "/home/jwilk/.local/lib/python3.7/site-packages/astroid/modutils.py", line 423, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/jwilk/.local/lib/python3.7/site-packages/astroid/modutils.py", line 648, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/jwilk/.local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 337, in find_spec
    _path, modname, module_parts, processed, submodule_path or path
  File "/home/jwilk/.local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 300, in _find_spec_with_path
    spec = finder.find_module(modname, module_parts, processed, submodule_path)
  File "/home/jwilk/.local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 124, in find_module
    stream, mp_filename, mp_desc = imp.find_module(modname, submodule_path)
  File "/usr/lib/python3.7/imp.py", line 301, in find_module
    encoding = tokenize.detect_encoding(file.readline)[0]
  File "/usr/lib/python3.7/tokenize.py", line 426, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/lib/python3.7/tokenize.py", line 405, in find_cookie
    raise SyntaxError(msg)
SyntaxError: unknown encoding for './test.py': UTF-9
```
### Expected behavior
```
test.py:1:3: E0001: unknown encoding: UTF-9 (<unknown>, line 1) (syntax-error)
```
(or something similar)

### pylint --version output
```
pylint 2.6.0
astroid 2.4.2
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
```

**Comment by hippo91** [comment]
@jwilk thanks for the report.
This bug is triggered in the `imp` module that `astroid` uses.
To be honest i don't think it worth developing a fix inside `astroid` to solve this kind of issue that is rare and quite easy to avoid.
@AWhetter @Pierre-Sassoulas @PCManticore what do you think about it?

**Comment by Pierre-Sassoulas** [comment]
This is strange, we have a functional test with a bogus encoding already (https://github.com/PyCQA/pylint/blob/master/tests/functional/u/unknown_encoding_py29.py) so this should not be happening (?)
