### ISSUE TITLE
Issue installing via pip in Mac Big Sur update

### ISSUE THREAD

**Issue by Souldat** [PyCQA/pylint#3967]
## Question
Python % pip3 install pylint
Collecting pylint
  Using cached pylint-2.6.0-py3-none-any.whl (325 kB)
Collecting astroid<=2.5,>=2.4.0
  Using cached astroid-2.4.2-py3-none-any.whl (213 kB)
Requirement already satisfied: six~=1.12 in /usr/local/lib/python3.9/site-packages (from astroid<=2.5,>=2.4.0->pylint) (1.15.0)
Collecting isort<6,>=4.2.5
  Using cached isort-5.6.4-py3-none-any.whl (98 kB)
Collecting lazy-object-proxy==1.4.*
  Using cached lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting mccabe<0.7,>=0.6
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting toml>=0.7.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting wrapt~=1.11
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Building wheels for collected packages: lazy-object-proxy, wrapt
  Building wheel for lazy-object-proxy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/tmpjdn44jhq
       cwd: /private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/lazy-object-proxy_a47eedce85f74ca4b86cd9abd85606db
  Complete output (84 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.9
  creating build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/compat.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/_version.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/slots.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/__init__.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/utils.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  copying src/lazy_object_proxy/simple.py -> build/lib.macosx-11-x86_64-3.9/lazy_object_proxy
  running build_ext
  building 'lazy_object_proxy.cext' extension
  creating build/temp.macosx-11-x86_64-3.9
  creating build/temp.macosx-11-x86_64-3.9/src
  creating build/temp.macosx-11-x86_64-3.9/src/lazy_object_proxy
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Isrc/lazy_object_proxy -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/lazy_object_proxy/cext.c -o build/temp.macosx-11-x86_64-3.9/src/lazy_object_proxy/cext.o
  ********************************************************************************
  WARNING:
  
      An optional code optimization (C extension) could not be compiled.
  
      Optimizations for this package will not be available!
  
  CAUSE:
  
      AttributeError("'int' object has no attribute 'split'")
  ********************************************************************************
  installing to build/bdist.macosx-11-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-11-x86_64
  creating build/bdist.macosx-11-x86_64/wheel
  creating build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/compat.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/_version.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/slots.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/__init__.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/utils.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  copying build/lib.macosx-11-x86_64-3.9/lazy_object_proxy/simple.py -> build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy
  running install_egg_info
  running egg_info
  writing src/lazy_object_proxy.egg-info/PKG-INFO
  writing dependency_links to src/lazy_object_proxy.egg-info/dependency_links.txt
  writing top-level names to src/lazy_object_proxy.egg-info/top_level.txt
  reading manifest file 'src/lazy_object_proxy.egg-info/SOURCES.txt'
  writing manifest file 'src/lazy_object_proxy.egg-info/SOURCES.txt'
  Copying src/lazy_object_proxy.egg-info to build/bdist.macosx-11-x86_64/wheel/lazy_object_proxy-1.4.3-py3.9.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 61, in <module>
      setup(
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 337, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 260, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 52, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-build-env-sgcjmme1/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for lazy-object-proxy
  Building wheel for wrapt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py'"'"'; __file__='"'"'/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-wheel-q3w2_b2z
       cwd: /private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/
  Complete output (61 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.9
  creating build/lib.macosx-11-x86_64-3.9/wrapt
  copying src/wrapt/importer.py -> build/lib.macosx-11-x86_64-3.9/wrapt
  copying src/wrapt/__init__.py -> build/lib.macosx-11-x86_64-3.9/wrapt
  copying src/wrapt/wrappers.py -> build/lib.macosx-11-x86_64-3.9/wrapt
  copying src/wrapt/decorators.py -> build/lib.macosx-11-x86_64-3.9/wrapt
  running build_ext
  building 'wrapt._wrappers' extension
  creating build/temp.macosx-11-x86_64-3.9
  creating build/temp.macosx-11-x86_64-3.9/src
  creating build/temp.macosx-11-x86_64-3.9/src/wrapt
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/wrapt/_wrappers.c -o build/temp.macosx-11-x86_64-3.9/src/wrapt/_wrappers.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py", line 102, in <module>
      run_setup(with_extensions=True)
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py", line 72, in run_setup
      setup(**setup_kwargs_tmp)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py", line 25, in run
      build_ext.run(self)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/nx/05b5xfpx03bcx4ctwszlzm340000gp/T/pip-install-a9o_173u/wrapt_4fe17efa52654a288df20368da3f8fd1/setup.py", line 31, in build_extension
      build_ext.build_extension(self, ext)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
      objects = self.compiler.compile(sources,
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 66, in spawn
      if _cfg_target_split > [int(x) for x in cur_target.split('.')]:
  AttributeError: 'int' object has no attribute 'split'
  ----------------------------------------
  ERROR: Failed building wheel for wrapt
  Running setup.py clean for wrapt
Failed to build lazy-object-proxy wrapt
ERROR: Could not build wheels for lazy-object-proxy which use PEP 517 and cannot be installed directly

**Comment by dbaty** [comment]
The problem happens while installing the *dependencies* of pylint. It seems that the `lazy-object-proxy` package cannot be installed on your system (and possibly `wrapt`, too, I am not sure). Since it's not related to pylint per se, I would suggest closing this issue here and reporting it to the maintainers of `lazy-object-proxy`. (You should probably report the error that you get when trying `pip install 'lazy-object-proxy==1.4.*'`, and/or `pip install lazy-object-proxy`, which should be the same error as you report, albeit smaller and more specific and actionable by the maintainers of `lazy-object-proxy`.

**Comment by hippo91** [comment]
@dbaty thanks for your investigation!
