### ISSUE TITLE
Multiple assignment with asterisk causes crash

### ISSUE THREAD

**Issue by asgerius** [PyCQA/pylint#4022]
### Steps to reproduce
1. Create a file `test.py` with the following content:
```py
def a():
    *b, c = (1, 2, 3)
```
2. Run `pylint test.py`

### Current behavior
Running the steps causes pylint to crash with the output below. Moving the asterisk to `c` instead of `b` (that is, `b, *c = (1, 2, 3)`) prevents a crash with a code rating of -25.

Curiously, this behavior is only observed when the multiple assignment is inside a function. Moving it top level results in a code rating of 0 in both cases.

```
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: C0103: Function name "a" doesn't conform to snake_case naming style (invalid-name)
test.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
Traceback (most recent call last):
  File "/home/asger/.local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/checkers/base.py", line 1990, in visit_assignname
    self._check_name("variable", node.name, node)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/checkers/base.py", line 2068, in _check_name
    if match is None and not _should_exempt_from_invalid_name(node):
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/checkers/base.py", line 2044, in _should_exempt_from_invalid_name
    inferred = utils.safe_infer(node)
  File "/home/asger/.local/lib/python3.9/site-packages/pylint/checkers/utils.py", line 1143, in safe_infer
    value = next(infer_gen)
  File "/home/asger/.local/lib/python3.9/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/asger/.local/lib/python3.9/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/home/asger/.local/lib/python3.9/site-packages/astroid/inference.py", line 850, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/home/asger/.local/lib/python3.9/site-packages/astroid/decorators.py", line 124, in yes_if_nothing_inferred
    yield from generator
  File "/home/asger/.local/lib/python3.9/site-packages/astroid/protocols.py", line 678, in starred_assigned_stmts
    elts.popleft()
AttributeError: 'list' object has no attribute 'popleft'
```

### Expected behavior
It should not crash, and output score should be equal in both cases mentioned.

### pylint --version output
```
pylint 2.6.0
astroid 2.4.2
Python 3.9.1 (default, Dec 25 2020, 13:07:14) 
[GCC 10.2.0]
```

### lsb_release -a
```
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2.1
Codename:       Nibia
```

**Comment by dbaty** [comment]
Looks like a duplicate of #3968. As per [this comment on that issue](https://github.com/PyCQA/pylint/issues/3968#issuecomment-752398965), the bug has been fixed in astroid.

I would hence close this issue.

**Comment by asgerius** [comment]
Thanks, missed that one
