### ISSUE TITLE
Regression: AttributeError in _check_super_with_arguments since pylint 2.6.0 

### ISSUE THREAD

**Issue by mbarkhau** [PyCQA/pylint#4036]
### Steps to reproduce

```python
# scratch/pylint_testcase.py
class Foo:
    def bar(self):
        pass

def patch_class(cls):
    def bar(self):
        super(cls, self)

    cls.bar = bar

patch_class(Foo)
```

```
$ ./env3/bin/pylint --version
pylint 2.6.0
astroid 2.4.2
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
```

```
$ ./env3/bin/pylint scratch/pylint_testcase.py
************* Module pylint_testcase
scratch/pylint_testcase.py:1:0: C0114: Missing module docstring (missing-module-docstring)
...
scratch/pylint_testcase.py:7:4: C0102: Black listed name "bar" (blacklisted-name)
Traceback (most recent call last):
  File "./env3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 3 more times]
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/checkers/refactoring.py", line 732, in visit_call
    self._check_super_with_arguments(node)
  File "/home/mbarkhau/env3/lib/python3.8/site-packages/pylint/checkers/refactoring.py", line 763, in _check_super_with_arguments
    or node.args[0].name != node_frame_class(node).name
AttributeError: 'NoneType' object has no attribute 'name'
```

```
$ ./env3/bin/pip install -U "pylint<2.6"
Collecting pylint<2.6
...
Successfully installed pylint-2.5.3
```

```
$ ./env3/bin/pylint --version
pylint 2.5.3
astroid 2.4.2
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
```

```
$ ./env3/bin/pylint  scratch/pylint_testcase.py
************* Module pylint_testcase
...
scratch/pylint_testcase.py:10:4: C0102: Black listed name "bar" (blacklisted-name)

-----------------------------------
Your code has been rated at 2.00/10
```

**Comment by hippo91** [comment]
@mbarkhau thanks for the report. It should have been fixed thanks to PR #3858.
