### ISSUE TITLE
Pylint crash - AttributeError: 'PosixPath' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by thibaut-singlefile** [PyCQA/pylint#4044]
Hi !

### Steps to reproduce
1. crash when linting on our private code

### Current behavior
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 229, in file_from_module_name
    value = self._mod_file_cache[(modname, contextfile)]
KeyError: ('_dummy_threading', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thibaut/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/check_parallel.py", line 69, in _worker_check_single_file
    _worker_linter.check_single_file(name, filepath, modname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 882, in check_single_file
    self.get_ast, check_astroid_module, name, filepath, modname
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1055, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1191, in visit_import
    self._check_module_attrs(node, module, parts[1:])
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1884, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 547, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 226, in delayed_assattr
    for inferred in node.expr.infer():
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/inference.py", line 850, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/protocols.py", line 331, in _arguments_infer_argname
    is_metaclass = isinstance(cls, nodes.ClassDef) and cls.type == "metaclass"
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1830, in _class_type
    if _is_metaclass(klass):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1799, in _is_metaclass
    for baseobj in base.infer():
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 93, in wrapped
    generator = _func(node, context, **kwargs)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/inference.py", line 273, in infer_import_from
    module = self.do_import_module()
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 158, in _post_build
    self.delayed_assattr(delayed)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 226, in delayed_assattr
    for inferred in node.expr.infer():
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield from generator
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield from generator
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield from generator
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/inference.py", line 227, in infer_call
    for callee in self.func.infer(context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield from generator
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/inference.py", line 293, in infer_attribute
    for owner in self.expr.infer(context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield from generator
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/inference.py", line 252, in infer_import
    yield self.do_import_module(self.real_name(name))
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 155, in _post_build
    self.add_from_names_to_locals(from_node)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/builder.py", line 209, in add_from_names_to_locals
    imported = node.do_import_module()
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 145, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/manager.py", line 233, in file_from_module_name
    modname.split("."), context_file=contextfile
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/modutils.py", line 423, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/modutils.py", line 648, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/interpreter/_import/spec.py", line 337, in find_spec
    _path, modname, module_parts, processed, submodule_path or path
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/interpreter/_import/spec.py", line 300, in _find_spec_with_path
    spec = finder.find_module(modname, module_parts, processed, submodule_path)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/interpreter/_import/spec.py", line 192, in find_module
    file_type, filename, path = _search_zip(module_parts, self._zipimporters)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/astroid/interpreter/_import/spec.py", line 281, in _search_zip
    found = importer.find_module(modpath[0])
  File "<frozen importlib._bootstrap_external>", line 423, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1223, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1268, in find_spec
  File "<frozen importlib._bootstrap_external>", line 60, in _path_join
  File "<frozen importlib._bootstrap_external>", line 60, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 870, in check
    files_or_modules,
  File "/Users/thibaut/.local/share/virtualenvs/singlefile-Y1CezQv3/lib/python3.6/site-packages/pylint/lint/check_parallel.py", line 109, in check_parallel
    ) in pool.imap_unordered(_worker_check_single_file, files):
  File "/Users/thibaut/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```

### Expected behavior
No crash

### pylint --version output
pylint 2.6.0
astroid 2.4.2
Python 3.6.8 (default, Jan  6 2020, 13:56:43) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]

Seems similar to: https://github.com/PyCQA/pylint/issues/3690

**Comment by dbaty** [comment]
Could you please provide a minimal piece of code that shows the issue, so that we can reproduce it?

**Comment by thibaut-singlefile** [comment]
Here's an example:
```
class A:
    @property
    def b():
        pass
if A.b:
    pass
```

If linting this file in the root folder, I get a reasonable pylint output:
```
pipenv run pylint --rcfile=.pylintrc --load-plugins=pylint_django test.py
Loading .env environment variables…
************* Module test
test.py:1:0: C0103: Class name "A" doesn't conform to PascalCase naming style (invalid-name)
test.py:3:4: C0103: Attribute name "b" doesn't conform to snake_case naming style (invalid-name)
test.py:3:4: E0211: Method has no argument (no-method-argument)
test.py:5:0: W0125: Using a conditional statement with a constant value (using-constant-test)

----------------------------------------------------------------------
Your code has been rated at -6.00/10 (previous run: -16.00/10, +10.00)
```

If I move the file to a subfolder (e.g. `pipenv run pylint --rcfile=.pylintrc --load-plugins=pylint_django src/test.py`), linting fails with the `AttributeError: 'PosixPath' object has no attribute 'rstrip'` error above.

**Comment by thibaut-singlefile** [comment]
Rolling pylint-django back to 2.3.0 fixed the issue so I cut an issue there: https://github.com/PyCQA/pylint-django/issues/308

**Comment by atodorov** [comment]
> 
> astroid 2.4.2
> Seems similar to: #3690

Both #3690 and this issue use astroid 2.4.2 and the traceback looks more like an astroid issues. @pylint maintainers  do you know if astroid changed somehow causing pylint/plugins to crash ? I didn't see anything obvious on the astroid repo.

**Comment by hippo91** [comment]
@thibaut-singlefile thanks for the report.
However i'm not able to reproduce it. May you try to reproduce it without using the plugin please?

**Comment by thibaut-singlefile** [comment]
It does not repro without the plugin. I also noticed that it always failed with the plugin and the `--django-settings-module=singlefile.settings` flag. We removed that flag with the latest version of `pylint-django` and pylint now works as expected. We can close this issue.

**Comment by pylint** [comment]
@atodorov I'm not a pylint maintainer. I was a bot.

**Comment by hippo91** [comment]
Thanks @thibaut-singlefile !
