### ISSUE TITLE
pyreverse: Cannot use on Django app/project

### ISSUE THREAD

**Issue by crazyscientist** [PyCQA/pylint#4187]
Up to version 2.7 it was possible to use `pyreverse` to also create diagrams for Django apps. Starting from version 2.7.0 this no longer works.

### Steps to reproduce

* Install Django (`pip install "Django<2.3"`, let's assume the LTS version)
* Setup a Django project: `django-admin startproject foo`
* Create a Django app:
```
$ cd foo
$ ./manage.py startapp bar
```
* Add `bar` to `INSTALLED_APPS` in `foo/foo/settings.py`
* Create a sub-module (e.g. `submod`) in `bar` and do something Django related in `submod/__init__.py`, e.g.:
```python
from django.contrib.auth.models import Group
```

The directory structure now should look like this
```
$ tree foo
foo/
├── bar
│   ├── admin.py
│   ├── apps.py
│   ├── __init__.py
│   ├── migrations
│   │   └── __init__.py
│   ├── models.py
│   ├── submod
│   │   └── __init__.py
│   ├── tests.py
│   └── views.py
├── foo
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
└── manage.py

4 directories, 13 files
```

### Current behavior
```
$ cd bar/
$ pyreverse bar
parsing bar/__init__.py...
parsing /tmp/foo/bar/views.py...
parsing /tmp/foo/bar/tests.py...
parsing /tmp/foo/bar/models.py...
parsing /tmp/foo/bar/apps.py...
parsing /tmp/foo/bar/admin.py...
parsing /tmp/foo/bar/__init__.py...
parsing /tmp/foo/bar/submod/__init__.py...
parsing /tmp/foo/bar/migrations/__init__.py...
Traceback (most recent call last):
  File "/home/andi/virtualenvs/smelt/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    PyreverseRun(sys.argv[1:])
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 188, in __init__
    sys.exit(self.run(args))
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 206, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 236, in get_diadefs
    diagrams = DefaultDiadefGenerator(linker, self).visit(project)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 162, in visit_module
    self.linker.visit(node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/inspector.py", line 258, in visit_importfrom
    relative = modutils.is_relative(basename, context_file)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/astroid/modutils.py", line 586, in is_relative
    submodule_spec = importlib.util.find_spec(
  File "/usr/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/tmp/foo/bar/submod/__init__.py", line 1, in <module>
    from django.contrib.auth.models import Group
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/db/models/base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/apps/registry.py", line 134, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/conf/__init__.py", line 60, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
The instruction is pretty straight forward, let's try again with the environment variable:
```
$ DJANGO_SETTINGS_MODULE=foo.settings pyreverse bar
parsing bar/__init__.py...
parsing /tmp/foo/bar/views.py...
parsing /tmp/foo/bar/tests.py...
parsing /tmp/foo/bar/models.py...
parsing /tmp/foo/bar/apps.py...
parsing /tmp/foo/bar/admin.py...
parsing /tmp/foo/bar/__init__.py...
parsing /tmp/foo/bar/submod/__init__.py...
parsing /tmp/foo/bar/migrations/__init__.py...
Traceback (most recent call last):
  File "/home/andi/virtualenvs/smelt/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    PyreverseRun(sys.argv[1:])
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 188, in __init__
    sys.exit(self.run(args))
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 206, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 236, in get_diadefs
    diagrams = DefaultDiadefGenerator(linker, self).visit(project)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 162, in visit_module
    self.linker.visit(node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/inspector.py", line 258, in visit_importfrom
    relative = modutils.is_relative(basename, context_file)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/astroid/modutils.py", line 586, in is_relative
    submodule_spec = importlib.util.find_spec(
  File "/usr/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/tmp/foo/bar/submod/__init__.py", line 1, in <module>
    from django.contrib.auth.models import Group
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/db/models/base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

### Expected behavior
Until the release of version 2.7 pyreverse did not attempt to actually execute Django code. So it was able to create diagrams for Django projects.

I suppose, this new behavior makes sense to get a better representation for dynamic relations, but in this case I'd favor the behavior of version 2.6. 

Maybe a command line argument to suppress this behavior can be the solution?

### pylint --version output

Result of `pylint --version` output:
```
pylint 2.7.0
astroid 2.5
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
---
pylint 2.7.2
astroid 2.5.1
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
```
This behavior is consistent in version 2.7.0 and 2.7.2

**Comment by crazyscientist** [comment]
There seems to have been some progress. With pyreverse version 2.8.3 I get a different error message:

```
parsing smeltapp/processors/__init__.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/__init__.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/progress.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/smash.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/bugzilla.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/scc.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/base.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/buildservice/changelog.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/buildservice/request.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/buildservice/bugowner.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/buildservice/__init__.py...
parsing /home/andi/workspace/smelt/smelt/smeltapp/processors/buildservice/incident.py...
Traceback (most recent call last):
  File "/home/andi/virtualenvs/smelt/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/__init__.py", line 39, in run_pyreverse
    PyreverseRun(sys.argv[1:])
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 201, in __init__
    sys.exit(self.run(args))
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/main.py", line 219, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 236, in get_diadefs
    diagrams = DefaultDiadefGenerator(linker, self).visit(project)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/diadefslib.py", line 162, in visit_module
    self.linker.visit(node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/pylint/pyreverse/inspector.py", line 246, in visit_import
    relative = astroid.modutils.is_relative(name[0], context_file)
  File "/home/andi/virtualenvs/smelt/lib/python3.8/site-packages/astroid/modutils.py", line 583, in is_relative
    parent_spec = importlib.util.find_spec(name, from_file)
  File "/usr/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'processors'
```

### pylint --version output
```
pylint 2.8.3
astroid 2.5.6
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]

**Comment by DudeNr33** [comment]
Hi @crazyscientist,
first of all thank you for the very detailed description!
I could not reproduce this issue with the current `pylint` version.
Can you confirm that this issue is solved?

**Comment by crazyscientist** [comment]
> Can you confirm that this issue is solved?

Sorry, completely forgot about this issue. Yes, it seems the problem was fixed sometime before September 2021.
