### ISSUE TITLE
Pylint 2.7.2 can't find its plugins on PYTHONPATH if the latter points to cwd

### ISSUE THREAD

**Issue by stanislavlevin** [PyCQA/pylint#4252]
### Steps to reproduce
```console
[builder@localhost test]$ touch pylint_plugins.py
[builder@localhost test]$ PYTHONPATH=. python3 -m pylint --load-plugins pylint_plugins
```

### Current behavior
Pylint can't find plugins in current working directory(PYTHONPATH is set to this directory):
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/.local/lib/python3/site-packages/pylint/__main__.py", line 18, in <module>
    pylint.run_pylint()
  File "/usr/src/.local/lib/python3/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/run.py", line 266, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 490, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/usr/src/.local/lib/python3/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pylint_plugins'
```
The regression is caused by cc8d9185d1b0ca79ed49efd0ee2d3cae5b1cacbb:
```python
> /usr/src/.local/lib/python3/site-packages/pylint/__main__.py(17)<module>()
-> sys.path = [p for p in sys.path if p not in ("", os.getcwd())]
(Pdb) sys.path
['/usr/src/test', '/usr/src/test', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/src/.local/lib/python3/site-packages', '/usr/lib64/python3/site-packages', '/usr/lib/python3/site-packages']
(Pdb) n
> /usr/src/.local/lib/python3/site-packages/pylint/__main__.py(19)<module>()
-> pylint.run_pylint()
(Pdb) sys.path
['/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/src/.local/lib/python3/site-packages', '/usr/lib64/python3/site-packages', '/usr/lib/python3/site-packages']
(Pdb) 
```
Changing the cwd can workaround this.

In the meantime:
```
[builder@localhost test]$ PYTHONPATH=. pylint.py3 --load-plugins pylint_plugins
> /usr/src/.local/lib/python3/site-packages/pylint/__init__.py(22)run_pylint()
-> try:
(Pdb) sys.path
['/usr/bin', '/usr/src/test', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/src/.local/lib/python3/site-packages', '/usr/lib64/python3/site-packages', '/usr/lib/python3/site-packages', '/usr/src/.local/lib/python3/site-packages/astroid/brain']
(Pdb) 
```
predictable doesn't cause such behaviour.

### Expected behavior
Pylint should find its plugins in PYTHONPATH.

### pylint --version output

Result of `pylint --version` output:
```console
[builder@localhost test]$ python3 -m pylint --version
pylint 2.7.2
astroid 2.5.1
Python 3.9.2 (default, Feb 26 2021, 15:33:46) 
[GCC 10.2.1 20201125 (ALT Sisyphus 10.2.1-alt2)]
```
Also checked on master(same result).

**Comment by stanislavlevin** [comment]
CC: @cdce8p, @sbraz.

**Comment by sbraz** [comment]
Hi @stanislavlevin,
Was this not the case in older versions? Does `PYTHONPATH="$(cwd)"` make a difference?

**Comment by stanislavlevin** [comment]
@sbraz, neither absolute nor relative path work. I pointed to concrete commit with which the issue happens.

**Comment by stanislavlevin** [comment]
This worked for years. In particular, the regression breaks FreeIPA (https://github.com/freeipa/freeipa/blob/master/Makefile.am#L363).

**Comment by sbraz** [comment]
Shrug, I just wanted to fix some failing tests, maybe the commit should just be reverted.

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Do you have a suggestion how we should handle this one? Should we revert the change? If so, it might make sense to include it in `2.7.3`

**Comment by Pierre-Sassoulas** [comment]
We'll need to add tests again, but I don't know how to fix precisely. Those change were done to handle python path starting or ending with a colon, so I think not being able to use our plugins is a bigger problem than not handling python starting or ending with a  colon. I think the fast thing to do would be to revert and add something in the doc about the current pythonpath limitation, what do you think ?

**Comment by cdce8p** [comment]
I might have found a way to fix this one without reverting the previous change: #4258

**Comment by stanislavlevin** [comment]
The fix was verified. Thank you!
