### ISSUE TITLE
The coveralls job is broken in continuous integration

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4408]
See [here](https://github.com/PyCQA/pylint/pull/4401/checks?check_run_id=2437252161)

```
Submitting coverage to coveralls.io...
Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/runner/work/pylint/pylint/venv/lib/python3.8/site-packages/coveralls/api.py", line 257, in wear
    response.raise_for_status()
  File "/home/runner/work/pylint/pylint/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/pylint/pylint/venv/lib/python3.8/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/home/runner/work/pylint/pylint/venv/lib/python3.8/site-packages/coveralls/api.py", line 260, in wear
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

@cdce8p do you have an idea how to fix it ?

**Comment by cdce8p** [comment]
Just from the error code, I would say this is a coveralls issue. It's a bit strange though, the status page doesn't mention any outages: https://status.coveralls.io

**Comment by grozdz** [comment]
Apparently it's a coveralls issue: https://github.com/lemurheavy/coveralls-public/issues/1543

**Comment by Pierre-Sassoulas** [comment]
Thank you for the link @grozdz ! Closing because we can't do anything about it.

**Comment by cdce8p** [comment]
Seams like the issue is fixed now
