### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by mMerlin** [PyCQA/pylint#4662]
### Steps to reproduce

This appears very sensitive to the exact current code and environment. My attempts to create a simplified case for testing have failed. I have a commit in a local git repo of the failing state. I can publish that if needed to debug the root cause. There is nothing proprietory in the project.

Commenting out a single line `assert uni.dimensions == 2` avoids the error.
Uncommenting 2 following lines
```py
    assert isinstance(uni.neighbourhood, frozenset)
    assert uni.neighbourhood == frozenset(test_neighbourhood)
```
avoids the error. Removing other test cases avoids the error. With or without the error condition, pytest can run the code without errors.

```txt .pylintrc
init-hook="from pylint.config import find_pylintrc; import os, sys; sys.path.append(os.path.dirname(find_pylintrc()))"
```
```py tests/test_create_universe.py
# pylint: disable=E1120,E1121
```
```sh
pipenv run pylint tests/test_create_universe.py
```

### Current behavior

```t
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Exception ignored in: <generator object infer_attribute at 0x7f98d58f6b30>
Traceback (most recent call last):
  File "/home/phil/.local/share/virtualenvs/cellular-automata-JH0ZnjF-/lib/python3.9/site-packages/astroid/inference.py", line 326, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/phil/.local/share/virtualenvs/cellular-automata-JH0ZnjF-/lib/python3.9/site-packages/astroid/bases.py", line 232, in igetattr
    yield from _infer_stmts(
ValueError: generator already executing
```

### Expected behavior

```t
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

### pylint --version output

```sh
% uname -r
5.12.13-200.fc33.x86_64
% pipenv --version
pipenv, version 2021.5.29
% pipenv run pylint --version
pylint 2.9.3
astroid 2.6.2
Python 3.9.5 (default, May 14 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
% pipenv graph
pylint==2.9.3
  - astroid [required: >=2.6.2,<2.7, installed: 2.6.2]
    - lazy-object-proxy [required: >=1.4.0, installed: 1.6.0]
    - wrapt [required: >=1.11,<1.13, installed: 1.12.1]
  - isort [required: >=4.2.5,<6, installed: 5.9.1]
  - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
  - toml [required: >=0.7.1, installed: 0.10.2]
pytest==6.2.4
  - attrs [required: >=19.2.0, installed: 21.2.0]
  - iniconfig [required: Any, installed: 1.1.1]
  - packaging [required: Any, installed: 20.9]
    - pyparsing [required: >=2.0.2, installed: 2.4.7]
  - pluggy [required: >=0.12,<1.0.0a1, installed: 0.13.1]
  - py [required: >=1.8.2, installed: 1.10.0]
  - toml [required: Any, installed: 0.10.2]
```

Needs the main project files being imported for the unittest cases.

**Comment by mMerlin** [comment]
I encountered another state in the source code that causes the same error. I saved that as another commit, and published the [repo on github](https://github.com/mMerlin/cellular_automata/). Then I reproduced the failure and working cases on a bare, but fully updated, Fedora 33 virtual machine. I hope this helps track down the cause.

```sh
sudo dnf install pipenv
mkdir development
cd development/
git clone https://github.com/mMerlin/cellular_automata.git
cd cellular_automata
pipenv --three
pipenv install --dev
git checkout 09e1c
pipenv run pylint tests/test_create_universe.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Exception ignored in: <generator object infer_attribute at 0x7f99e7bae510>
Traceback (most recent call last):
  File "/home/phil/.local/share/virtualenvs/cellular_automata-j_gSvSpf/lib/python3.9/site-packages/astroid/inference.py", line 326, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/phil/.local/share/virtualenvs/cellular_automata-j_gSvSpf/lib/python3.9/site-packages/astroid/bases.py", line 232, in igetattr
    yield from _infer_stmts(

git checkout 9cec8
pipenv run pylint tests/test_create_universe.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Exception ignored in: <generator object infer_attribute at 0x7f4f67d82510>
Traceback (most recent call last):
  File "/home/phil/.local/share/virtualenvs/cellular_automata-j_gSvSpf/lib/python3.9/site-packages/astroid/inference.py", line 326, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/phil/.local/share/virtualenvs/cellular_automata-j_gSvSpf/lib/python3.9/site-packages/astroid/bases.py", line 232, in igetattr
    yield from _infer_stmts(
ValueError: generator already executing

# modify tests/test_create_universe.py to have one fewer assertion
git diff
diff --git a/tests/test_create_universe.py b/tests/test_create_universe.py
index df61228..082be4a 100644
--- a/tests/test_create_universe.py
+++ b/tests/test_create_universe.py
@@ -508,7 +508,7 @@ def test_properties() -> None:
     uni = AutomataUniverse(test_neighbourhood, test_survival, test_birth)
     assert isinstance(uni, AutomataUniverse)
     assert isinstance(uni.dimensions, int)
-    assert uni.dimensions == 2 # previously caused pylint crash/trace
+    # assert uni.dimensions == 2 # previously caused pylint crash/trace
     # assert isinstance(uni.neighbourhood, frozenset)
     # assert uni.neighbourhood == frozenset(test_neighbourhood)
     # assert isinstance(uni.neighbourhood_population, int)
pipenv run pylint tests/test_create_universe.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

# modify tests/test_create_universe.py to have three more assertions
git diff
diff --git a/tests/test_create_universe.py b/tests/test_create_universe.py
index df61228..6befefd 100644
--- a/tests/test_create_universe.py
+++ b/tests/test_create_universe.py
@@ -509,9 +509,9 @@ def test_properties() -> None:
     assert isinstance(uni, AutomataUniverse)
     assert isinstance(uni.dimensions, int)
     assert uni.dimensions == 2 # previously caused pylint crash/trace
-    # assert isinstance(uni.neighbourhood, frozenset)
-    # assert uni.neighbourhood == frozenset(test_neighbourhood)
-    # assert isinstance(uni.neighbourhood_population, int)
+    assert isinstance(uni.neighbourhood, frozenset)
+    assert uni.neighbourhood == frozenset(test_neighbourhood)
+    assert isinstance(uni.neighbourhood_population, int)
     # assert uni.neighbourhood_population == len(test_neighbourhood)
     # assert isinstance(uni.survival_rules, frozenset)
     # assert uni.survival_rules == frozenset(test_survival)
pipenv run pylint tests/test_create_universe.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

uname -r
5.12.13-200.fc33.x86_64
pipenv --version
pipenv, version 2020.8.13
pipenv graph
pylint==2.9.3
  - astroid [required: >=2.6.2,<2.7, installed: 2.6.2]
    - lazy-object-proxy [required: >=1.4.0, installed: 1.6.0]
    - wrapt [required: >=1.11,<1.13, installed: 1.12.1]
  - isort [required: >=4.2.5,<6, installed: 5.9.1]
  - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
  - toml [required: >=0.7.1, installed: 0.10.2]
pytest==6.2.4
  - attrs [required: >=19.2.0, installed: ?]
  - iniconfig [required: Any, installed: 1.1.1]
  - packaging [required: Any, installed: 20.4]
  - pluggy [required: >=0.12,<1.0.0a1, installed: 0.13.1]
  - py [required: >=1.8.2, installed: 1.10.0]
  - toml [required: Any, installed: 0.10.2]
```

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I see you have assigned yourself to this.

I have checked out the latest commit on https://github.com/mMerlin/cellular_automata/, `09e1c` and `9cec8` and none of them crash any longer. I think this has been fixed already. Should we close this?

**Comment by Pierre-Sassoulas** [comment]
Thank you for checking @DanielNoord 😄 Indeed I think we can close
