### ISSUE TITLE
new unused-private-member causes a crash

### ISSUE THREAD

**Issue by stanislavlevin** [PyCQA/pylint#4755]
### Bug description

Given a file `test.py`:

```python
# Please disable message unrelated to the bug
# pylint: disable=missing-docstring,too-few-public-methods,protected-access
class Context:
    def __init__(self):
        self.__messages = None

class Command:
    def __init__(self):
        self.context = Context()

    def method(self):
        self.context.__messages = []
        for message in self.context.__messages:
            print(message)
```

### Command used

Result of `pylint test.py`:
```
************* Module test
test.py:4:8: W0238: Unused private member `Context.__messages` (unused-private-member)
Exception on node <ClassDef.Command l.6 at 0x7f4ee5bd05e0> in file '/usr/src/RPM/BUILD/test.py'
Traceback (most recent call last):
  File "/usr/bin/pylint.py3", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.8.2', 'console_scripts', 'pylint')())
  File "/usr/src/.local/lib/python3/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/run.py", line 384, in __init__
    linter.check(args)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 951, in check
    self._check_files(
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 985, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1011, in _check_file
    check_astroid_module(ast_node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1145, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1190, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/usr/src/.local/lib/python3/site-packages/pylint/utils/ast_walker.py", line 79, in walk
    callback(astroid)
  File "/usr/src/.local/lib/python3/site-packages/pylint/checkers/classes.py", line 893, in leave_classdef
    self._check_unused_private_members(node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/checkers/classes.py", line 953, in _check_unused_private_members
    and attribute.expr.name == "self"
AttributeError: 'Attribute' object has no attribute 'name'

```

### (Expected behavior)

pylint shouldn't crash.

### (Version affected)

```shell
pylint 2.9.0+ (including today's main).
```

### (OS / Environment)

ALTLinux

**Comment by stanislavlevin** [comment]
traceback for today's `main`:
```
************* Module test
test.py:4:8: W0238: Unused private member `Context.__messages` (unused-private-member)
Exception on node <ClassDef.Command l.6 at 0x7feb211e4940> in file '/usr/src/RPM/BUILD/test.py'
Traceback (most recent call last):
  File "/usr/bin/pylint.py3", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.8.2', 'console_scripts', 'pylint')())
  File "/usr/src/.local/lib/python3/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/run.py", line 384, in __init__
    linter.check(args)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 975, in check
    self._check_files(
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1009, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1035, in _check_file
    check_astroid_module(ast_node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1172, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/src/.local/lib/python3/site-packages/pylint/lint/pylinter.py", line 1217, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/usr/src/.local/lib/python3/site-packages/pylint/utils/ast_walker.py", line 79, in walk
    callback(astroid)
  File "/usr/src/.local/lib/python3/site-packages/pylint/checkers/classes.py", line 904, in leave_classdef
    self._check_unused_private_attributes(node)
  File "/usr/src/.local/lib/python3/site-packages/pylint/checkers/classes.py", line 983, in _check_unused_private_attributes
    assign_attr.expr.name == "cls"
AttributeError: 'Attribute' object has no attribute 'name'
```

**Comment by stanislavlevin** [comment]
IMO, non-current node's private attributes should be skipped.

**Comment by yushao2** [comment]
hi, looked into it and came up with a PR :) please take a look

**Comment by stanislavlevin** [comment]
The fix is verified. Thank you! (fixed + no regressions were found)
