### ISSUE TITLE
Pylint error: 'optparse.OptionValueError: option spelling-dict: invalid value: 'en_US', should be in ['']'

### ISSUE THREAD

**Issue by AndreasLuckert** [PyCQA/pylint#5092]
### Bug description

```python
Cannot apply pylint to files in parent- and sub-folders using bash CLI.

I've already filed this issue on StackOverFlow, but was redirected here by Pierre Sassoulas:
https://stackoverflow.com/questions/69203782/pylint-error-optparse-optionvalueerror-option-spelling-dict-invalid-value
```

### Command used

```shell
pylint src/packages/ics/plugins/
```

### Pylint output

```shell
Traceback (most recent call last):
  File "C:\Users\andreas.luckert\.pyenv\pyenv-win\versions\3.9.4\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andreas.luckert\.pyenv\pyenv-win\versions\3.9.4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andreas.luckert\Projects\proj-venv\Scripts\pylint.exe\__main__.py", line 7, in <module>
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\lint\run.py", line 324, in __init__
    linter.load_config_file()
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option_manager_mixin.py", line 321, in load_config_file     
    self.global_set_option(option, value)
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option_manager_mixin.py", line 189, in global_set_option    
    self._all_options[opt].set_option(opt, value)
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\options_provider_mixin.py", line 54, in set_option
    value = _validate(value, optdict, optname)
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option.py", line 115, in _validate
    return _call_validator(_type, optdict, name, value)
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option.py", line 96, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option.py", line 83, in <lambda>
    "choice": lambda opt, name, value: _choice_validator(opt["choices"], name, value),
  File "C:\users\andreas.luckert\projects\proj-venv\lib\site-packages\pylint\config\option.py", line 31, in _choice_validator
    raise optparse.OptionValueError(msg % (name, value, choices))
optparse.OptionValueError: option spelling-dict: invalid value: 'en_US', should be in ['']
```

### Expected behavior

Linting all files within the given directory.

### Pylint version

```shell
PYLINTHOME is now 'C:\Users\andreas.luckert\AppData\Local\pylint\pylint\Cache' but obsolescent 'C:\Users\andreas.luckert\.pylint.d' is found; you can safely remove the latter
pylint 2.11.1
astroid 2.8.0
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
```

### OS / Environment

Windows 10

### Additional dependencies

alabaster==0.7.12
appdirs==1.4.4
argon2-cffi==20.1.0
asn1crypto==1.4.0
astroid==2.8.0
async-generator==1.10
atomicwrites==1.4.0
attrs==21.2.0
Authlib==0.15.4
awswrangler==2.8.0
Babel==2.9.1
backcall==0.2.0
bandit==1.7.0
beautifulsoup4==4.9.3
bleach==3.3.0
boto3==1.17.77
botocore==1.20.77
category-encoders==2.2.2
certifi==2021.5.30
cffi==1.14.5
cfgv==3.3.0
chardet==3.0.4
colorama==0.4.4
commonmark==0.9.1
cryptography==3.4.7
cycler==0.10.0
decorator==4.4.2
defusedxml==0.7.1
distlib==0.3.2
dnspython==1.16.0
docformatter==1.4
docopt==0.6.2
docutils==0.16
entrypoints==0.3
et-xmlfile==1.1.0
fett==0.3.2
filelock==3.0.12
flake8==3.9.2
future==0.18.2
gitdb==4.0.7
GitPython==3.1.18
identify==2.2.10
idna==2.10
imagesize==1.2.0
iniconfig==1.1.1
ipykernel==5.5.5
ipython==7.25.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.9.1
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
joblib==1.0.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
lazy-object-proxy==1.6.0
livereload==2.6.3
lxml==4.6.3
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.3.4
matplotlib-inline==0.1.2
mccabe==0.6.1
mistune==0.8.4
mypy==0.910
mypy-extensions==0.4.3
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.5.1
nodeenv==1.6.0
notebook==6.4.0
numpy==1.20.3
openpyxl==3.0.7
packaging==20.9
pandas==1.1.5
pandocfilters==1.4.3
parso==0.8.2
pathtools==0.1.2
patsy==0.5.1
pbr==5.6.0
pg8000==1.19.5
pickleshare==0.7.5
Pillow==8.2.0
platformdirs==2.4.0
pluggy==1.0.0
pre-commit==2.13.0
prometheus-client==0.11.0
prompt-toolkit==3.0.19
py==1.10.0
py4j==0.10.9
pyarrow==4.0.0
pycodestyle==2.7.0
pycparser==2.20
pydocstyle==6.1.1
pyflakes==2.3.1
Pygments==2.9.0
pylint==2.11.1
pymongo==3.11.4
PyMySQL==1.0.2
pyparsing==2.4.7
pyrsistent==0.18.0
pyspark==3.1.2
pytest==6.2.5
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
pytz==2021.1
pywin32==301
pywinpty==1.1.3
PyYAML==5.3.1
pyzmq==22.1.0
qtconsole==5.1.0
QtPy==1.9.0
recommonmark==0.7.1
redshift-connector==2.0.882
requests==2.24.0
rstcheck==3.3.1
s3transfer==0.4.2
scikit-learn==0.24.2
scipy==1.7.0
scramp==1.4.0
Send2Trash==1.7.1
simple-salesforce==1.0.0
six==1.16.0
smmap==4.0.0
snooty-lextudio==1.11.4.dev0
snowballstemmer==2.1.0
soupsieve==2.2.1
Sphinx==4.2.0
sphinx-autobuild==2021.3.14
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-confluencebuilder==1.5.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
statsmodels==0.12.2
stevedore==3.3.0
terminado==0.10.1
testpath==0.5.0
threadpoolctl==2.1.0
toml==0.10.2
tornado==6.1
traitlets==5.0.5
types-requests==2.25.6
typing-extensions==3.10.0.2
untokenize==0.1.1
urllib3==1.25.11
virtualenv==20.4.7
watchdog==1.0.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.12.1
yapf==0.31.0

**Comment by DanielNoord** [comment]
Do you have a `pylintrc` file? If so, could you paste it here?

**Comment by AndreasLuckert** [comment]
I've just checked the whereabouts of my `pylintrc `files:

```
./.cache/pre-commit/repo0iwlpid1/.pylintrc
./.cache/pre-commit/repo0v23xj4q/.pylintrc
./.cache/pre-commit/repo8bzi95iu/examples/pylintrc
./.cache/pre-commit/repo8bzi95iu/examples/pylintrc_camelcase
./.cache/pre-commit/repo8bzi95iu/pylintrc
./.cache/pre-commit/repo8bzi95iu/tests/functional/d/disabled_msgid_in_pylintrc.py
./.cache/pre-commit/repo8bzi95iu/tests/functional/d/disabled_msgid_in_pylintrc.rc
./.cache/pre-commit/repo8bzi95iu/tests/regrtest_data/.pylintrc
./.cache/pre-commit/repo8bzi95iu/tests/regrtest_data/comments_pylintrc
./.cache/pre-commit/repo8bzi95iu/tests/regrtest_data/test_pylintrc_comments.py
./.cache/pre-commit/repokqe4_938/examples/pylintrc
./.cache/pre-commit/repokqe4_938/examples/pylintrc_camelcase
./.cache/pre-commit/repokqe4_938/pylintrc
./.cache/pre-commit/repokqe4_938/tests/functional/d/disabled_msgid_in_pylintrc.py
./.cache/pre-commit/repokqe4_938/tests/functional/d/disabled_msgid_in_pylintrc.rc
./.cache/pre-commit/repokqe4_938/tests/regrtest_data/.pylintrc
./.cache/pre-commit/repokqe4_938/tests/regrtest_data/comments_pylintrc
./.cache/pre-commit/repokqe4_938/tests/regrtest_data/test_pylintrc_comments.py
./.cache/pre-commit/repoltjy0ux6/examples/pylintrc
./.cache/pre-commit/repoltjy0ux6/examples/pylintrc_camelcase
./.cache/pre-commit/repoltjy0ux6/pylintrc
./.cache/pre-commit/repoltjy0ux6/tests/functional/d/disabled_msgid_in_pylintrc.py
./.cache/pre-commit/repoltjy0ux6/tests/functional/d/disabled_msgid_in_pylintrc.rc
./.cache/pre-commit/repoltjy0ux6/tests/regrtest_data/.pylintrc
./.cache/pre-commit/repoltjy0ux6/tests/regrtest_data/comments_pylintrc
./.cache/pre-commit/repoltjy0ux6/tests/regrtest_data/test_pylintrc_comments.py
./.cache/pre-commit/repoozydvb7d/examples/pylintrc
./.cache/pre-commit/repoozydvb7d/examples/pylintrc_camelcase
./.cache/pre-commit/repoozydvb7d/pylintrc
./.cache/pre-commit/repoozydvb7d/tests/functional/d/disabled_msgid_in_pylintrc.py
./.cache/pre-commit/repoozydvb7d/tests/functional/d/disabled_msgid_in_pylintrc.rc
./.cache/pre-commit/repoozydvb7d/tests/regrtest_data/.pylintrc
./.cache/pre-commit/repoozydvb7d/tests/regrtest_data/comments_pylintrc
./.cache/pre-commit/repoozydvb7d/tests/regrtest_data/test_pylintrc_comments.py
./.cache/pre-commit/repot7yxyz2x/pylintrc
....
```

Thus, I picked the very first one in the list:
[pylintrc.txt](https://github.com/PyCQA/pylint/files/7252767/pylintrc.txt)

Hope its content will help you along.

**Comment by DanielNoord** [comment]
Hm, that file seems to be fine.
I would expect a `pylintrc` file with a line:
`spelling-dict=en_US` or `spelling-dict="en_US"`

If that's not the case then something else is trying to set `spelling-dict` which would require some additional investigation.

**Comment by AndreasLuckert** [comment]
Could this be the culprit?:

```
[pylint.spelling]
spelling-dict = en_US
spelling-private-dict-file = .dictionary
```

I found it in 'setup.cfg' inside the project's parent directory.

**Comment by DanielNoord** [comment]
Yeah, that is most definitely an incorrect setting. I'm looking at the code and trying to solve this, but I don't know what this setting is supposed to do.

Do you know if you have installed the `python-enchant` package? Or if it is supposed to be installed in your environment? According to the code it might be necessary for this setting to work correctly.

**Comment by AndreasLuckert** [comment]
I didn't have installed the `pyenchant `package.

Now, after installing it, **it works** indeed:

```
$ pip install pyenchant
Collecting pyenchant
  Using cached pyenchant-3.2.1-py3-none-win_amd64.whl (11.9 MB)
Installing collected packages: pyenchant
Successfully installed pyenchant-3.2.1


$ pylint src/packages/ics/plugins/
************* Module ics.plugins.ics_account_de
src\packages\ics\plugins\ics_account_de.py:514:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)
************* Module ics.plugins.ics_frequency
src\packages\ics\plugins\ics_frequency.py:226:53: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)

-----------------------------------
Your code has been rated at 9.99/10
```

**Comment by DanielNoord** [comment]
I guess we should work on the error code here. I'm going to change the title to something actionable that we can work towards!

**Comment by clavedeluna** [comment]
I'm having a similar issue with this.  running with this in pylintrc `spelling-dict=en-US` or even `spelling-dict=en_US` I always get
```
usage: pylint [options]
pylint: error: argument --spelling-dict: invalid choice: 'en-US' (choose from '')
```

same behavior if I run this via command line with `--spelling-dict=en`

and yes I do have `pyenchant` installed. What could be the issue here?

**Comment by Pierre-Sassoulas** [comment]
You do not have any local dict available for pyenchant (probably). The error message need to be different when the choices are an empty list.

**Comment by clavedeluna** [comment]
Ah, seems like it would be good to link users to https://pyenchant.github.io/pyenchant/install.html in case of this failure. I didn't realize I needed more than just pip installing.

**Comment by clavedeluna** [comment]
Ok I ran `brew install enchant` and that solved my issue which I think is probably the same as the original issue. I'm not sure updating this `instr = " To make it work, install the 'python-enchant' package."` to include the url above is sufficient because this `instr` doesn't seem to be hit?

**Comment by Pierre-Sassoulas** [comment]
Let's not couple our message with something too precise about pyenchant that we do not control. 'check your pyenchant installation in particular system dependencies' will still be right if pyenchant change URL and installation methods.
