### ISSUE TITLE
Exception in 2.11.0

### ISSUE THREAD

**Issue by mafrosis** [PyCQA/pylint#5096]
### Bug description

```python
I get a stacktrace linting a single file in 2.11.0. This crash does not happed in 2.10.2.
```

### Configuration

```ini
[MESSAGES CONTROL]
disable=bad-whitespace, consider-iterating-dictionary, import-error, invalid-name, missing-docstring, no-else-return, no-member, line-too-long, too-many-ancestors, too-many-arguments, too-many-branches, too-many-locals, too-many-return-statements, too-many-statements, too-few-public-methods, ungrouped-imports, inconsistent-return-statements, wrong-import-order, wrong-import-position, raise-missing-from, use-dict-literal

[SIMILARITIES]
min-similarity-lines=8
```

### Command used

```shell
pylint models.py
```

### Pylint output

```shell
Exception on node <If l.533 at 0x7fb45d978be0> in file '/app/models.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/base.py", line 1104, in visit_if
    self._check_using_constant_test(node, node.test)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/base.py", line 1142, in _check_using_constant_test
    inferred = utils.safe_infer(test)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/utils.py", line 1181, in safe_infer
    value = next(infer_gen)
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 105, in infer
    yield from self._infer(context, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/astroid/inference.py", line 872, in _infer_compare
    retval = _do_compare(lhs, op, rhs)
  File "/usr/local/lib/python3.8/site-packages/astroid/inference.py", line 842, in _do_compare
    left, right = _to_literal(left), _to_literal(right)
  File "/usr/local/lib/python3.8/site-packages/astroid/inference.py", line 814, in _to_literal
    return ast.literal_eval(node.as_string())
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 547, in as_string
    return AsStringVisitor()(self)
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/as_string.py", line 55, in __call__
    return node.accept(self).replace(DOC_NEWLINE, "\n")
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 186, in accept
    return func(self)
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/as_string.py", line 185, in visit_classdef
    args += [n.accept(self) for n in node.keywords]
TypeError: 'NoneType' object is not iterable
Can't write the issue template for the crash in /root/.cache/pylint/pylint-crash-2021-09-30-20.txt.
************* Module jira_offline.models
jira_offline/models.py:1:0: F0001: Fatal error while checking 'jira_offline/models.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/root/.cache/pylint/pylint-crash-2021-09-30-20.txt'. (fatal)

------------------------------------
Your code has been rated at 10.00/10
```

### Expected behavior

No stacktrace

### Pylint version

```shell
pylint 2.11.0
astroid 2.8.0
Python 3.8.12 (default, Sep  3 2021, 02:24:44)
[GCC 10.2.1 20210110]
```

### OS / Environment

Docker `python:3.8-slim`

**Comment by DanielNoord** [comment]
I think this should be fixed with #5037 which is due to be included in a release in the near future!
