### ISSUE TITLE
Crash in `VariablesChecker._is_only_type_assignment`

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#5162]
This change causes a crash when testing Home Assistant.

```
Exception on node <Name.event_ids l.16 at 0x1052e2230> in file '/Users/marc/Develop/pylint/test5.py'
Traceback (most recent call last):
  File "/Users/marc/Develop/pylint/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/Users/marc/Develop/pylint/pylint/checkers/variables.py", line 1189, in visit_name
    elif self._is_only_type_assignment(node, name, defstmt):
  File "/Users/marc/Develop/pylint/pylint/checkers/variables.py", line 1560, in _is_only_type_assignment
    for ref_node in node.scope().locals[name][1:]:
KeyError: 'event_ids'
```

To reproduce
```py
# pylint: disable=undefined-variable

def _purge_filtered_states(session) -> None:
    """Remove filtered states and linked events."""
    state_ids: list[int]
    event_ids: list[int | None]
    state_ids, event_ids = zip(
        *(
            session.query(States.state_id, States.event_id)
            .filter(States.entity_id.in_(excluded_entity_ids))
            .limit(MAX_ROWS_TO_PURGE)
            .all()
        )
    )
    event_ids = [id_ for id_ in event_ids if id_ is not None]
```

--
Taken from here: [homeassistant/components/recorder/purge.py -> _purge_filtered_states](https://github.com/home-assistant/core/blob/aeb00823aa0cacc124196765d1a38b40da7fa9f1/homeassistant/components/recorder/purge.py#L179-L198)

_Originally posted by @cdce8p in https://github.com/PyCQA/pylint/issues/5158#issuecomment-944471574_

**Comment by cdce8p** [comment]
The issue is caused by #5158.
In particular if a variable is not defined in the current astroid scope. For the example above the scope is `ListComp` whereas the `AnnAssign` is in the `FunctionDef` scope.

A similar error can be created by using `global`.
```py
var: int

def func():
    global var
    print(var)
```

--
@DanielNoord Would you like to take a look at this?
