### ISSUE TITLE
Crash `AttributeError` for new `use_implicit_booleaness_not_comparison`

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#5170]
### Bug description

```python
class Custom:
    var = [1, 2, 3]

Custom.var != []
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Exception on node <Compare l.4 at 0x109cdb310> in file '/.../pylint/test.py'
Traceback (most recent call last):
  File "/.../pylint/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/.../pylint/pylint/checkers/refactoring/implicit_booleaness_checker.py", line 142, in visit_compare
    self._check_use_implicit_booleaness_not_comparison(node)
  File "/.../pylint/pylint/checkers/refactoring/implicit_booleaness_checker.py", line 192, in _check_use_implicit_booleaness_not_comparison
    variable_name = target_node.name
AttributeError: 'Attribute' object has no attribute 'name'
```

### Expected behavior

_no error_

### Pylint version

```shell
Current main
```

**Comment by jaehoonhwang** [comment]
Fix Merge Request: https://github.com/PyCQA/pylint/pull/5176
