### ISSUE TITLE
Crash with walrus in nested if block

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#5178]
### Bug description

```python
def get_media_info(media_library, val):
    media = None

    if val == 1:
        media = media_library.get_episodes()
        if media := media.get("episodes"):  # <-- causes crash
            pass

    elif val == 2:
        media = media_library.get_channels()
        media = media.get("channels")

    return media  # <-- error here
```

Replacing the assignment expressions fixes the issue:
```py
        media = media.get("episodes")
        if media:
            pass
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Exception on node <Name.media l.13 at 0x1084d7df0> in file '/.../pylint/test6.py'
Traceback (most recent call last):
  File "/.../pylint/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/.../pylint/pylint/checkers/variables.py", line 1046, in visit_name
    self._loopvar_name(node, name)
  File "/.../pylint/pylint/checkers/variables.py", line 1619, in _loopvar_name
    astmts = [stmt for stmt in node.lookup(name)[1] if hasattr(stmt, "assign_type")]
  File "/.../astroid/astroid/nodes/node_classes.py", line 373, in lookup
    return self.scope().scope_lookup(self, name)
  File "/.../astroid/astroid/nodes/scoped_nodes.py", line 1840, in scope_lookup
    return super().scope_lookup(node, name, offset)
  File "/.../astroid/astroid/nodes/scoped_nodes.py", line 1332, in scope_lookup
    return frame._scope_lookup(node, name, offset)
  File "/.../astroid/astroid/nodes/scoped_nodes.py", line 255, in _scope_lookup
    stmts = node._filter_stmts(self.locals[name], self, offset)
  File "/.../astroid/astroid/nodes/node_classes.py", line 500, in _filter_stmts
    if _stmts[pindex].assign_type().parent_of(assign_type):
IndexError: list index out of range
```

### Expected behavior

_no error_

### Pylint version

```shell
pylint main (2021-10-18)
astroid main (2021-10-18)
```

**Comment by DanielNoord** [comment]
I did a little investigation and found that the following can be used as a minimal reproducing example in a test:

```python
def func5(val):
    variable = None

    if val == 1:
        variable = "value"
        if variable := "value":
            pass

    elif val == 2:
        variable = "value"
        variable = "value"

    return variable 
```

Commenting out any of these assigns (even one of the double `variable = "value"`) fixes the crash.

**Comment by DanielNoord** [comment]
I've written a fix for `astroid` but did not have an internet connection on my laptop.
Will upload it today or tomorrow. Should be able to put this in `2.12.x`.
