### ISSUE TITLE
Crash on dataclasses attributes within `open()` calls

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#5321]
### Bug description

This code should be added to `tests/functional/u/unspecified_encoding_py38.py`:

```python
import dataclasses
from typing import Optional

FILENAME = "test_two.py"


@dataclasses.dataclass
class IOArgs:
    """Dataclass storing information about how to open a file"""

    encoding: Optional[str]
    mode: str


args_good_one = IOArgs(encoding=None, mode="wb")
args_good_two = IOArgs(encoding="utf8", mode="w")
args_bad_one = IOArgs(encoding=None, mode="w")
LOCALE_ENCODING = None
args_bad_two = IOArgs(encoding=LOCALE_ENCODING, mode="w")

file = open(FILENAME, args_good_one.mode, encoding=args_good_one.encoding)
file = open(FILENAME, args_good_two.mode, encoding=args_good_two.encoding)
file = open(FILENAME, args_bad_one.mode, encoding=args_bad_one.encoding)
file = open(FILENAME, args_bad_two.mode, encoding=args_bad_two.encoding)
```

This currently creates a crash.

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
pylint test.py
Exception on node <Call l.21 at 0x10f881e40> in file '/Users/daniel/DocumentenLaptop/Programming/Github/pylint/test.py'
Traceback (most recent call last):
  File "/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/checkers/stdlib.py", line 534, in visit_call
    self._check_open_encoded(node, inferred.root().name)
  File "/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/checkers/stdlib.py", line 631, in _check_open_encoded
    if not mode_arg or "b" not in mode_arg.value:
  File "/Users/daniel/.pyenv/versions/3.10.0/envs/pylint-3.10.0/lib/python3.10/site-packages/astroid/bases.py", line 133, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'ClassDef' object has no attribute 'value'
************* Module test
test.py:1:0: F0001: Fatal error while checking 'test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/daniel/Library/Caches/pylint/pylint-crash-2021-11-16-14.txt'. (fatal)

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)
```

### Expected behavior

This shouldn't crash.

It has something to do with the inference of dataclasses but I couldn't figure it out easily. I only know that `astroid` handles this in a special way but I have no knowledge of that part of the codebase.
Any help would be appreciated!

### Pylint version

```shell
Latest commit on `main`
```

**Comment by Pierre-Sassoulas** [comment]
I think this is a duplicate of https://github.com/PyCQA/pylint/issues/5266

**Comment by cdce8p** [comment]
This seems like a two part issue:
1. `args_good_one.encoding` is inferred as `<Instance of builtins.str>`. It should have been a `Const` (string) node with value `wb`. Likely an issue in the dataclass brain.
2. `_check_open_encoded` does an unprotected attribute access to `mode_arg.value`. A fix could be to add an `isinstance(mode_arg, nodes.Const)` check. I would think this should resolve #5266 as well.

https://github.com/PyCQA/pylint/blob/7d2b6c9bd807dda7502e739c7b9fb2182d89f457/pylint/checkers/stdlib.py#L629

**Comment by cdce8p** [comment]
I just removed the milestone here. The crash was fixed with #5332 (closed #5266 for it). Should we leave this open for the dataclass inference issue?

**Comment by DanielNoord** [comment]
I think so! I'll update the OP and title!
