### ISSUE TITLE
[crash] doc params extension: --accept-no-param-doc: conflicting option string(s)

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5322]
### Bug description

There is a crash when using the doc_params extension.

### Command used

```shell
pylint --load-plugins=pylint.extensions.docparams a.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/home/pierre/myproject_bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/lint/run.py", line 345, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/lint/pylinter.py", line 591, in load_plugin_modules
    module.register(self)
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/extensions/check_docs.py", line 26, in register
    linter.register_checker(docparams.DocstringParameterChecker(linter))
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/lint/pylinter.py", line 717, in register_checker
    self.register_options_provider(checker)
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/config/option_manager_mixin.py", line 99, in register_options_provider
    self.add_option_group(
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/config/option_manager_mixin.py", line 136, in add_option_group
    self.add_optik_option(provider, group, opt, optdict)
  File "/home/pierre/myproject_lib/python3.8/site-packages/pylint/config/option_manager_mixin.py", line 140, in add_optik_option
    option = optikcontainer.add_option(*args, **optdict)
  File "/usr/lib/python3.8/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "/usr/lib/python3.8/optparse.py", line 980, in _check_conflict
    raise OptionConflictError(
optparse.OptionConflictError: option --accept-no-param-doc: conflicting option string(s): --accept-no-param-doc
```

### Expected behavior

No crash.

### Pylint version

```shell
pylint 2.11.2-dev0
astroid 2.8.5
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
```

**Comment by jolaf** [comment]
> You are likely loading the extension twice because the only effect of loading `check_docs` is to load the `docparams` extension.

Probably the problem is `--list-extensions` lists BOTH `check_docs` AND `docparams`, probably `--enable-all-extensions` does the same mistake.
```$ pylint --list-extensions  | sort
pylint.extensions.bad_builtin
pylint.extensions.broad_try_clause
pylint.extensions.check_docs
pylint.extensions.check_elif
pylint.extensions.code_style
pylint.extensions.comparetozero
pylint.extensions.comparison_placement
pylint.extensions.confusing_elif
pylint.extensions.consider_ternary_expression
pylint.extensions.docparams
pylint.extensions.docstyle
pylint.extensions.empty_comment
pylint.extensions.emptystring
pylint.extensions.for_any_all
pylint.extensions.mccabe
pylint.extensions.overlapping_exceptions
pylint.extensions.redefined_variable_type
pylint.extensions.set_membership
pylint.extensions.typing
pylint.extensions.while_used
```

**Comment by Pierre-Sassoulas** [comment]
Yes @jolaf this is what caused the problem, I wanted to use all extensions in my configuration.

**Comment by jolaf** [comment]
@DanielNoord @Pierre-Sassoulas Thanks!
