### ISSUE TITLE
Crash on combination of decorators and properties

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#5382]
### Bug description

The following file should be added to our functional tests:

`tests/functional/r/regression_02/regression_node_statement_two.py`:
```python
"""Test to see we don't crash on this code in pandas.
See: https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/period.py
"""
# pylint: disable=no-member, redefined-builtin, invalid-name, missing-class-docstring


def my_decorator(*params):
    def decorator(decorated):
        return decorated

    return decorator


class ClassWithProperty:
    def f():
        return "string"

    f.__name__ = "name"
    f.__doc__ = "docstring"

    hour = property(f)


class ClassWithDecorator:
    @my_decorator(ClassWithProperty.hour.fget)
    def my_property(self) -> str:
        return "a string"
```

Found while working on https://github.com/PyCQA/pylint/pull/5310

Similar crash occurs on this file:
https://github.com/django/django/blob/main/django/template/response.py

### Command used

```shell
pylint
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/checkers/typecheck.py", line 1041, in visit_attribute
    for n in owner.getattr(node.attrname)
  File "/Users/daniel/.pyenv/versions/3.10.0/envs/pylint-3.10.0/lib/python3.10/site-packages/astroid/nodes/scoped_nodes.py", line 1795, in getattr
    found_attrs.append(self.special_attributes.lookup(name))
  File "/Users/daniel/.pyenv/versions/3.10.0/envs/pylint-3.10.0/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 127, in lookup
    return getattr(self, IMPL_PREFIX + name)
  File "/Users/daniel/.pyenv/versions/3.10.0/envs/pylint-3.10.0/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 802, in attr_fget
    property_accessor.postinit(args=func.args, body=func.body)
AttributeError: 'Property' object has no attribute 'args'
```

### Expected behavior

No crash

### Pylint version

```shell
Latest commit on `main`.
```

**Comment by Pierre-Sassoulas** [comment]
Blocker for 2.12, right ? :)

**Comment by DanielNoord** [comment]
Not necessarily if we postpone using `statement(future=True)` as well. I looked it into this but couldn't find a fix in 5 minutes so I had to give up for now.

Current code works fine (`primer` passes), crash only occurs on future behaviour.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Could you test and see if you can reproduce this? I no longer can but I don't think I changed anything related to this crash.. 😅

**Comment by jacobtylerwalls** [comment]
I actually tested this morning and couldn't reproduce either.

**Comment by DanielNoord** [comment]
Thanks @jacobtylerwalls! I'll close this then.

Obviously if anybody reports back that this is still an issue we can reopen.

**Comment by jacobtylerwalls** [comment]
Do you want to add the test case?

**Comment by DanielNoord** [comment]
That's not a bad idea actually. I'll create a PR, thanks for the tip!
