### ISSUE TITLE
'VariablesChecker' object has no attribute '_is_undefined_variable_enabled'

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#5477]
### Bug description

When running pylint the below error occurs. Looking in the code, the method is really not defined

### Command used

```shell
pylint ...
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/root/git/basement/venv/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/root/git/basement/venv/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1018, in visit_name
    self._undefined_and_used_before_checker(node, stmt)
  File "/root/git/basement/venv/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1039, in _undefined_and_used_before_checker
    node, stmt, frame, current_consumer, i, base_scope_type
  File "/root/git/basement/venv/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1143, in _check_consumer
    self._is_undefined_variable_enabled
AttributeError: 'VariablesChecker' object has no attribute '_is_undefined_variable_enabled'
```

### Expected behavior

Works fine

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.0
python 3.7.1
```

**Comment by kasium** [comment]
Sorry, that was my fault...

**Comment by Pierre-Sassoulas** [comment]
I don't understand how it could be your fault ? Where you modifying pylint locally ?

**Comment by kasium** [comment]
@Pierre-Sassoulas I misread some CI stuff and thought it was pylint execution, but I were some custom tests which forgot to call checker.open()
