### ISSUE TITLE
ImportError: cannot import name 'settings' from partially initialized module 'isort' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mcauley-penney** [PyCQA/pylint#5522]
### Bug description

I updated Python (from 3.9.9 to 3.10.1) as well as Pylint this morning. Afterwards, when executing Pylint, I receive the errors shown below. This is for __any__ execution: when using --help, on a fiile, or without any arguments. The error given after the traceback is `ImportError: cannot import name 'settings' from partially initialized module 'isort' (most likely due to a circular import) (/home/m/.local/lib/python3.10/site-packages/isort/__init__.py)`. I'm honestly assuming this is my error somehow, despite that the traceback and error are saying that there is a source code issue.

Thanks!

![image](https://user-images.githubusercontent.com/59481467/145871488-34914ac4-db71-4418-83c3-da4132263ff5.png)

### Command used

```shell
any pylint command
```

### Pylint output

```shell
~/files/work/GitHub-Repo-Extractor-2/extractor/base
» pylint
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pylint/utils/utils.py", line 6, in <module>
    import isort.api
  File "/home/m/.local/lib/python3.10/site-packages/isort/__init__.py", line 21, in <module>
    from . import settings
ImportError: cannot import name 'settings' from partially initialized module 'isort' (most likely due to a circular import) (/home/m/.local/lib/python3.10/site-packages/isort/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 48, in <module>
    from pylint.utils.docs import print_full_documentation
  File "/usr/lib/python3.10/site-packages/pylint/utils/docs.py", line 9, in <module>
    from pylint.utils.utils import get_rst_section, get_rst_title
  File "/usr/lib/python3.10/site-packages/pylint/utils/utils.py", line 10, in <module>
    import isort
  File "/home/m/.local/lib/python3.10/site-packages/isort/__init__.py", line 21, in <module>
    from . import settings
ImportError: cannot import name 'settings' from partially initialized module 'isort' (most likely due to a circular import) (/home/m/.local/lib/python3.10/site-packages/isort/__init__.py)```
```

### Expected behavior

For pylint commands to execute

### Pylint version

```shell
pylint in /usr/lib/python3.10/site-packages (2.12.2)
Python 3.10.1
```

### OS / Environment

```
» uname -r
5.15.7-arch1-1
```

### Additional dependencies

```
» pip freeze
appdirs==1.4.4
argon2-cffi==21.1.0
astroid==2.9.0
async-generator==1.10
attrs==21.2.0
backcall==0.2.0
black==21.12b0
bleach==4.1.0
btrfsutil==5.15.1
CacheControl==0.12.6
cffi==1.15.0
chardet==4.0.0
click==8.0.3
colorama==0.4.4
contextlib2==0.6.0.post1
cryptography==36.0.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
Deprecated==1.2.13
distlib==0.3.3
distro==1.6.0
entrypoints==0.3
html5lib==1.1
idna==3.3
importlib-metadata==4.8.1
ipykernel==6.6.0
ipython==7.30.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
isort==5.10.1
jedi==0.18.1
Jinja2==3.0.3
jsonschema==3.2.0
jupyter-client==7.1.0
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
lazy-object-proxy==1.6.0
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.10.0
msgpack==1.0.2
mypy-extensions==0.4.3
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.4
notebook==6.4.4
ordered-set==4.0.2
packaging==20.9
pandocfilters==1.4.3
parso==0.8.2
pathspec==0.9.0
pep517==0.12.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.4.0
ply==3.11
progress==1.6
prometheus-client==0.11.0
prompt-toolkit==3.0.22
ptyprocess==0.7.0
pulsemixer==1.5.1
pycparser==2.21
PyGithub==1.55
Pygments==2.10.0
PyJWT==2.3.0
pylint==2.12.2
PyNaCl==1.4.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pyzmq==22.2.1
requests==2.26.0
resolvelib==0.5.5
retrying==1.3.3
Send2Trash==1.8.0
six==1.16.0
terminado==0.11.1
testpath==0.5.0
toml==0.10.2
tomli==1.2.2
tornado==6.1
traitlets==5.1.0
typing-extensions==4.0.1
ufw==0.36.1
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.13.3
zipp==3.6.0
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, it look like a problem with isort API that can't be imported. In order to reproduce more easily could you tell us how you installed pylint ?

**Comment by mcauley-penney** [comment]
I installed Pylint through pip. When this error popped up this morning after updating, I uninstalled Pylint and all of its dependencies via pip and reinstalled all of them through pacman, Arch's package manager. I received all of the same errors.

**Comment by mcauley-penney** [comment]
Updated isort today and the issue was resolved
