### ISSUE TITLE
Crash "``<class 'PySide6.QtCore.PyClassProperty'>`` object has no `__doc__` attribute"

### ISSUE THREAD

**Issue by idelect** [PyCQA/pylint#5545]
### Bug description

When parsing the following file:

```python
from PySide6.QtCore import QAbstractTableModel, Qt, QSortFilterProxyModel
from PySide6.QtWidgets import QTableView, QApplication

def main():
    pass


if __name__ == "__main__":
    main()
```

pylint crashed with a ``AttributeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\lint\pylinter.py", line 1034, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\lint\pylinter.py", line 1069, in _check_file
    check_astroid_module(ast_node)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\lint\pylinter.py", line 1203, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\lint\pylinter.py", line 1250, in _check_astroid_module
    walker.walk(node)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\utils\ast_walker.py", line 75, in walk
    self.walk(child)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\utils\ast_walker.py", line 72, in walk
    callback(astroid)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\checkers\variables.py", line 1339, in visit_importfrom
    module = self._check_module_attrs(node, module, name_parts[1:])
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\pylint\checkers\variables.py", line 2168, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\nodes\scoped_nodes.py", line 620, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\nodes\scoped_nodes.py", line 735, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\manager.py", line 190, in ast_from_module_name
    return self.ast_from_module(module, modname)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\manager.py", line 287, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\builder.py", line 97, in module_build
    node = self.inspect_build(module, modname=modname, path=path)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\raw_building.py", line 326, in inspect_build
    self.object_build(node, module)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\raw_building.py", line 363, in object_build
    class_node = object_build_class(node, member, name)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\raw_building.py", line 186, in object_build_class
    return _base_class_object_build(node, member, basenames, localname=localname)
  File "C:\Users\idele\My Drive\Python\Python38\lib\site-packages\astroid\raw_building.py", line 244, in _base_class_object_build
    member.__doc__,
AttributeError: <class 'PySide6.QtCore.PyClassProperty'> object has no `__doc__` attribute
```

### Command used

```shell
pylint scratch.py
```

### Pylint output

```shell
Exception on node <ImportFrom l.1 at 0x274ba5b9af0> in file 'C:\Users\idele\My Drive\Semaphore Software\Signal Scout\scratch.py'
Traceback (most recent call last):
    node = self.inspect_build(module, modname=modname, path=path)
    node = self.inspect_build(module, modname=modname, path=path)
  File "c:\users\idele\my drive\python\python38\lib\site-packages\astroid\raw_building.py", line 326, in inspect_build
    self.object_build(node, module)
  File "c:\users\idele\my drive\python\python38\lib\site-packages\astroid\raw_building.py", line 363, in object_build
    class_node = object_build_class(node, member, name)
  File "c:\users\idele\my drive\python\python38\lib\site-packages\astroid\raw_building.py", line 186, in object_build_class
    return _base_class_object_build(node, member, basenames, localname=localname)
  File "c:\users\idele\my drive\python\python38\lib\site-packages\astroid\raw_building.py", line 244, in _base_class_object_build
    member.__doc__,
AttributeError: <class 'PySide6.QtCore.PyClassProperty'> object has no `__doc__` attribute
************* Module scratchscratch.py:1:0: F0001: Fatal error while checking 'scratch.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\idele\AppData\Local\pylint\pylint\Cache\pylint-crash-2021-12-17-10.txt'. (fatal)
```

### Expected behavior

Not a crash.

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.0
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
```

### OS / Environment

Windows 11

### Additional dependencies

astroid==2.9.0
lazy-object-proxy==1.7.1
pandas==1.3.5
pylint==2.12.2
PySide6==6.2.2.1
shiboken6==6.2.2.1

**Comment by Pierre-Sassoulas** [comment]
I think it could be a good idea to add PyQT to the primer while fixinjg this.

**Comment by DanielNoord** [comment]
The same issue is reported in #5495 

They also mention something that changed in the latest version of `PyQT`.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas This seems to be a bug in `PyQT`, see https://bugreports.qt.io/browse/PYSIDE-1727

We could add something to `astroid` to fix this crash for this particular affected version but seeing the quick response of the `PyQT` team to the issue reported against them I believe this pattern shouldn't really be supported/happening anyway. Perhaps we can close/`won't-fix` this?

The other issue in #5495 remains though I think.

**Comment by Pierre-Sassoulas** [comment]
I don't think we should crash even on "wrong" code. Could we handle this kind of crash generically in astroid instead ? Imo ideally this should be a fatal "astroid-parse-error" (extact name unknown, but the one in `PyLinter`).

**Comment by DanielNoord** [comment]
We could but after a quick read of the issue report in `PyQT` their code breaks core assumptions of python: namely that `__doc__` is defined. The maintainer actually refers to this here:
https://bugreports.qt.io/browse/PYSIDE-1727?focusedCommentId=601513&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-601513

They changed how they initialise their classes and the attribute became uninitialised.

We could support that but I get the sense that it is similar to how a `dict` should have a `__getitem__` etc. We should be allowed to make some assumptions about the code we analyse without putting `if` statements everywhere 😄

**Comment by Pierre-Sassoulas** [comment]
Fair point, closing as won't fix / downstream bug.
