### ISSUE TITLE
Crash "list index out of range" for a specific sequence of commands

### ISSUE THREAD

**Issue by J0ern** [PyCQA/pylint#5546]
### Bug description

When parsing the following file:

```python
a = True
if a:
    a = True
    if a := True:
        pass
    a = True
b = 1 if a else 0

```

pylint crashed with a ``IndexError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pylint/lint/pylinter.py", line 1024, in _check_files
    self._check_file(
  File "/usr/local/lib/python3.9/dist-packages/pylint/lint/pylinter.py", line 1063, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.9/dist-packages/pylint/lint/pylinter.py", line 1200, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.9/dist-packages/pylint/lint/pylinter.py", line 1245, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.9/dist-packages/pylint/utils/ast_walker.py", line 78, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/dist-packages/pylint/utils/ast_walker.py", line 78, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/dist-packages/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/usr/local/lib/python3.9/dist-packages/pylint/checkers/base.py", line 1979, in visit_assignname
    if isinstance(utils.safe_infer(assign_type.value), nodes.ClassDef):
  File "/usr/local/lib/python3.9/dist-packages/pylint/checkers/utils.py", line 1192, in safe_infer
    value = next(infer_gen)
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/node_ng.py", line 99, in infer
    yield from self._infer(context, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.9/dist-packages/astroid/inference.py", line 922, in infer_ifexp
    test = next(self.test.infer(context=context.clone()))
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/usr/local/lib/python3.9/dist-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.9/dist-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.9/dist-packages/astroid/inference.py", line 202, in infer_name
    frame, stmts = self.lookup(self.name)
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/node_classes.py", line 371, in lookup
    return self.scope().scope_lookup(self, name)
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/scoped_nodes.py", line 575, in scope_lookup
    return self._scope_lookup(node, name, offset)
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/scoped_nodes.py", line 251, in _scope_lookup
    stmts = node._filter_stmts(self.locals[name], self, offset)
  File "/usr/local/lib/python3.9/dist-packages/astroid/nodes/node_classes.py", line 498, in _filter_stmts
    if _stmts[pindex].assign_type().parent_of(assign_type):
IndexError: list index out of range
```

### Command used

```shell
I am using the Pylance plugin v2021.12.2 (12/13/2021, 23:25:06) in a Visual Studio Code 1.63.2
```

### Pylint output

```shell
Fatal error while checking '/home/XXX/repos/XXX/pylint_fatal.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/XXX/.cache/pylint/pylint-crash-2021-12-17-16.txt'.
```

### Expected behavior

Code is fully correct.
There should be no complaints at all.
(BTW, in the Windows environment, everything is fine in Visual Studio Code. This only happens in VSC running on Ubuntu 20.04.2)

### Pylint version

```shell
pylint 2.10.2
astroid 2.7.3
Python 3.9.9 (main, Nov 16 2021, 03:08:02) 
[GCC 9.3.0]
```

### OS / Environment

Ubuntu 20.04.2 LTS
Visual Studio Code v1.63.2

**Comment by Pierre-Sassoulas** [comment]
It's fixed in the latest pylint (2.12.2).
