### ISSUE TITLE
Crash ``'Call' object has no attribute 'name'`` when accessing a private class variable

### ISSUE THREAD

**Issue by bugale** [PyCQA/pylint#5569]
### Bug description

Seems similar to #4638, but reproduces after its fix

When parsing the following file:

```python
class A:
    @classmethod
    def b(cls) -> None:
        cls.__a = ''

    def a(self):
        type(self).__a

```

pylint crashed with a ``AttributeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\pylinter.py", line 1034, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\pylinter.py", line 1069, in _check_file
    check_astroid_module(ast_node)
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\pylinter.py", line 1203, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\pylinter.py", line 1250, in _check_astroid_module
    walker.walk(node)
  File "C:\Program Files\Python39\lib\site-packages\pylint\utils\ast_walker.py", line 75, in walk
    self.walk(child)
  File "C:\Program Files\Python39\lib\site-packages\pylint\utils\ast_walker.py", line 77, in walk
    callback(astroid)
  File "C:\Program Files\Python39\lib\site-packages\pylint\checkers\classes.py", line 901, in leave_classdef
    self._check_unused_private_attributes(node)
  File "C:\Program Files\Python39\lib\site-packages\pylint\checkers\classes.py", line 1008, in _check_unused_private_attributes
    and attribute.expr.name in {"cls", "self", node.name}
AttributeError: 'Call' object has no attribute 'name'
```

### Command used

```shell
pylint bugale_test.py
```

### Pylint output

```shell
Exception on node <ClassDef.A l.1 at 0x19bf0e5c820> in file 'C:\Users\bugaleb\Documents\GitHub\winagent\SmartViz\AutomationTests\bugale_test.py'
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pylint\utils\ast_walker.py", line 77, in walk
    callback(astroid)
  File "C:\Program Files\Python39\lib\site-packages\pylint\checkers\classes.py", line 901, in leave_classdef
    self._check_unused_private_attributes(node)
  File "C:\Program Files\Python39\lib\site-packages\pylint\checkers\classes.py", line 1008, in _check_unused_private_attributes
    and attribute.expr.name in {"cls", "self", node.name}
AttributeError: 'Call' object has no attribute 'name'
bugale_test.py:1:0: F0001: Fatal error while checking 'bugale_test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\bugaleb\AppData\Local\pylint\pylint\Cache\pylint-crash-2021-12-21-00.txt'. (fatal)
```

### Expected behavior

Not to crash

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.0
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

### OS / Environment

Windows 11

**Comment by Pierre-Sassoulas** [comment]
I can reproduce this with the latest main, thank you for opening the issue.
