### ISSUE TITLE
Add a flag to disable config parsing

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/pylint#5667]
### Current problem

Here's a sample broken `.pylintrc`, placed in the root folder:

```ini
[pylint]
test = '%A'
```

This is what happens when I try to use pylint now:
```console
$ pylint myfile.py
Traceback (most recent call last):
  File "/Users/tusharsadhwani/code/marvin-python/venv3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/lint/run.py", line 324, in __init__
    linter.load_config_file()
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 319, in load_config_file
    for option, value in parser.items(section):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 860, in items
    return [(option, value_getter(option)) for option in orig_keys]
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 860, in <listcomp>
    return [(option, value_getter(option)) for option in orig_keys]
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 856, in <lambda>
    value_getter = lambda option: self._interpolation.before_get(self,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%A'"

$ pylint --help   
Traceback (most recent call last):
[...]
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%A'"

$ pylint       
Traceback (most recent call last):
[...]
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%A'"
```

Is it possible to add a flag that disables config parsing entirely, so that the pylint isn't completely broken when this happens? `--ignore-config-file` for example?

P.S. this is a feature I want, and I'd be willing to contribute it.

**Comment by tushar-deepsource** [comment]
Optionally, raising a warning using a logger when config parsing fails might be a good idea.

**Comment by DanielNoord** [comment]
I'd recommend waiting for the `argparse` migration to do this if we want to.

That said, I'm not sure this should be allowed. I'm probably missing something, but in what scenario would you want to run `pylint` without being able to fix a faulty `pylintrc`?

**Comment by Pierre-Sassoulas** [comment]
There's [functional tests for the configuration](https://github.com/PyCQA/pylint/tree/main/tests/config/functional) that would permit to implement this relatively easily (at least on the testing side.) Also there's already [specific messages raised for faulty configuration](https://github.com/PyCQA/pylint/blob/main/pylint/lint/pylinter.py#L182), it would be possible to add a generic one like "bad-configuration-file". Personally I would appreciate to have proper error message instead of a crash.

But as @DanielNoord pointed out, the current implementation with optparse and callback is not ideal. I think adding test for badly configured option is valuable but it's entirely possible that a complicated solution with a message raised could be replaced by a simple ``type=a_check_function`` argument to ``argparse.ArgumentParser.add_argument`` once the migration from optparse to argparse is complete.

**Comment by tusharsadhwani** [comment]
Adding a message for bad config would be just as good (probably better I suppose, as it's more directly actionable)

**Comment by DanielNoord** [comment]
Adding it to the `argparse` project then :)

That should get some traction again after `2.13` is released.

**Comment by Pierre-Sassoulas** [comment]
@tushar-deepsource this is not blocked anymore as we almost migrated to argparse at this point. If you still want to contribute there's an example of configuration functional test in #6328

**Comment by tusharsadhwani** [comment]
@Pierre-Sassoulas yeah, feel free to assign me. I'll work on it in this weekend.

**Comment by DanielNoord** [comment]
@tusharsadhwani Would you be okay with raising a warning about a broken config file and then continuing the run instead of adding a flag? That would probably also fit your use-case right?

**Comment by tusharsadhwani** [comment]
@DanielNoord yup, that works.
