### ISSUE TITLE
Crash with argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by henryiii** [PyCQA/pylint#5731]
### Bug description

PyLint crashes when running on Plumbum. (it continues on other files just fine, though). Pretty sure it's choking on this:

https://github.com/tomerfiliba/plumbum/blob/bd29e7f21b1a9856d81553f149c68d07fbc38ce9/plumbum/commands/base.py#L474-L475

### Command used

```shell
python -m pip install . paramiko pylint ipython
pylint plumbum

# (inside of a local noxfile)
```

### Pylint output

```pytb
Traceback (most recent call last):
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1034, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1069, in _check_file
    check_astroid_module(ast_node)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1203, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1250, in _check_astroid_module
    walker.walk(node)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/checkers/stdlib.py", line 534, in visit_call
    self._check_open_encoded(node, inferred.root().name)
  File "/Users/henryschreiner/git/software/plumbum/.nox/pylint/lib/python3.10/site-packages/pylint/checkers/stdlib.py", line 633, in _check_open_encoded
    and "b" not in mode_arg.value
TypeError: argument of type 'NoneType' is not iterable
```

### Expected behavior

No crash?

### Pylint version

```shell
pylint 2022.1.7
```

### OS / Environment

macOS, Python 3.10. Targeting 3.6.

**Comment by jacobtylerwalls** [comment]
Thanks for the report! I reproduced on main with this:

```python
open(fp, mode=None)
```
