### ISSUE TITLE
Crash ``list index out of range``

### ISSUE THREAD

**Issue by gh-tsc** [PyCQA/pylint#5737]
### Bug description
minimal.py containing
```
e = "aaaa"
a = str(e).split(sep=": ")[-1]
```

### Command used

```shell
pylint minimal.py
```

### Pylint output

```shell
minimal.py:1: [C0103(invalid-name), ] Constant name "e" doesn't conform to UPPER_CASE naming style ('([^\\W\\da-z][^\\Wa-z]*|__.*__)$' pattern)
Exception on node <Call l.2 at 0x7f1aefe51580> in file '/home/tsc@gatehouse.local/dev/daas-ais-service/minimal.py'
Traceback (most recent call last):
  File "/home/tsc@gatehouse.local/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/home/tsc@gatehouse.local/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/recommendation_checker.py", line 65, in visit_call
    self._check_use_maxsplit_arg(node)
  File "/home/tsc@gatehouse.local/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/recommendation_checker.py", line 140, in _check_use_maxsplit_arg
    + f"({node.args[0].as_string()}, maxsplit=1)[{subscript_value}]"
IndexError: list index out of range
minimal.py:1: [F0001(fatal), ] Fatal error while checking 'minimal.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/tsc@gatehouse.local/.cache/pylint/pylint-crash-2022-01-28-11.txt'.
```

### Expected behavior

Didn't expect any fatal error

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
```

### OS / Environment

Ubuntu 20.04

**Comment by gh-tsc** [comment]
After changing the file to:
```
e = "aaaa"
a = str(e).split(": ")[-1]
```
Pylint doesn't crash
