### ISSUE TITLE
[Bug] Pylint and astroid

### ISSUE THREAD

**Issue by DavidMeu** [PyCQA/pylint#5759]
### Bug description

https://stackoverflow.com/questions/70937230/pylint-attributeerror/70939018#70939018

### Configuration

```ini
Just install latest Pylint
```

### Command used

```shell
pylint some_file.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\Scripts\pylint.exe\__main__.py", line 7, in <module>
  File "\lib\site-packages\pylint\__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "\lib\site-packages\pylint\lint.py", line 1394, in __init__
    linter.check(args)
  File "\lib\site-packages\pylint\lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "\lib\site-packages\pylint\lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "\lib\site-packages\pylint\lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "\lib\site-packages\pylint\utils.py", line 1159, in walk
    self.walk(child)
  File "\lib\site-packages\pylint\utils.py", line 1156, in walk
    cb(astroid)
  File "\lib\site-packages\pylint\checkers\variables.py", line 1331, in visit_import
    module = next(node.infer_name_module(parts[0]))
AttributeError: 'Import' object has no attribute 'infer_name_module'
```

### Expected behavior

No errors

### Pylint version

```shell
pylint 2.12.2
```

### OS / Environment

Windows 10

**Comment by cdce8p** [comment]
@DavidMeu Are you certain that you've installed `2.12.2` and used that version?
Just from looking at the traceback, the code in question has long been fixed. Judging by the line numbers, I would guess that you unknowingly used pylint `2.0.1` or an even older one.

**Comment by DavidMeu** [comment]
correct used `2.0.1`
