### ISSUE TITLE
Crash ``'Call' object has no attribute 'name'`` (if possible, be more specific about what made pylint crash)

### ISSUE THREAD

**Issue by jdavidagudelo** [PyCQA/pylint#5980]
### Bug description

When parsing the following file:

```python
def format_manifest_serializer_errors(errors):
    errors_messages = []
    for key, value in errors.items():
        for message in format_manifest_serializer_errors(value):
            error_message = f"{key}: {message}"
            errors_messages.append(error_message)
    return errors_messages

```

pylint crashed with a ``AttributeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 61, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 67, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 75, in _modified_iterating_check
    if self._modified_iterating_list_cond(node, iter_obj):
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 124, in _modified_iterating_list_cond
    self._common_cond_list_set(node, iter_obj, infer_val)
  File "/home/jdavidagudelo/.cache/pypoetry/virtualenvs/core-lkCHMl49-py3.10/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 105, in _common_cond_list_set
    node.value.func.expr.name == iter_obj.name
AttributeError: 'Call' object has no attribute 'name'
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Pylint crashes.
```

### Expected behavior

The command should not raise an exception.

### Pylint version

```shell
pylint 2.13.0
```

**Comment by DanielNoord** [comment]
Duplicate of #5969, although that issue was lacking a code example so posting this example there might help get this resolved!
