### ISSUE TITLE
astroid.exceptions.AstroidError: Could not find <Set.set l.311 at 0x2557e123ac8> in <Dict.dict l.311 at 0x2557e123948>'s children

### ISSUE THREAD

**Issue by burrussmp** [PyCQA/pylint#6048]
### Bug description

Asteroid error when upgrading from pylint 2.12 to 2.13. Code cannot be shared.

### Configuration

```ini
Not relevant
```

### Command used

```shell
pylint <file_name>.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\pylint\utils\ast_walker.py", line 73, in walk
    callback(astroid)
  File "c:\program files\python37\lib\site-packages\pylint\checkers\ellipsis_checker.py", line 49, in visit_const
    len(node.parent.parent.child_sequence(node.parent)) > 1
  File "c:\program files\python37\lib\site-packages\astroid\nodes\node_ng.py", line 399, in child_sequence
    raise AstroidError(msg % (repr(child), repr(self)))
astroid.exceptions.AstroidError: Could not find <Set.set l.310 at 0x291c720f508> in <Dict.dict l.310 at 0x291c720f388>'s children
tests\pipeline\platforms\platform_test.py:1: [F] F0002 tests\pipeline\platforms\platform_test.py: Fatal error while checking 'tests\pipeline\platforms\platform_test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\mburruss\AppData\Local\pylint\pylint\Cache\pylint-crash-2022-03-29-13.txt'. [pylint]
```

### Expected behavior

Return nothing or linting failures.

### Pylint version

```shell
pylint 2.13.3
astroid 2.11.2
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

### OS / Environment

Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎10/‎23/‎2021
OS build	22000.556
Serial number	047128602457
Experience	Windows Feature Experience Pack 1000.22000.556.0

**Comment by mbyrnepr2** [comment]
Looks similar to https://github.com/PyCQA/pylint/issues/6037. I'll address this in the merge request linked over there.

**Comment by mbyrnepr2** [comment]
Can be reproduced with this example:
```python
x = {'a': {...}}
```

This issue is addressed and a functional test added in: https://github.com/PyCQA/pylint/issues/6037.
