### ISSUE TITLE
Crash ``'Values' object has no attribute 'additional_builtins'``

### ISSUE THREAD

**Issue by mh21** [PyCQA/pylint#6408]
### Bug description

When parsing the following file:

```python
"""YAML CLI tools for miscellaneous operations not supported by shyaml."""
import argparse
import re
import sys
import typing

import yaml


def split_dot(data: str) -> typing.List[str]:
    """Split string on dots, but ignore backslash+dot."""
    return list(t.replace(r'\.', '.') for t in re.split(r'(?<!\\)\.', data))


def set_value(data: typing.Any, key_path: str, value: typing.Any) -> None:
    """Implement the set-value command."""
    target = data
    keys = split_dot(key_path)
    key: typing.Union[str, int]
    for index, key in enumerate(keys):
        if isinstance(target, list):
            key = int(key)
        if index < len(keys) - 1:
            target = target[key]
        else:
            target[key] = yaml.safe_load(value)


def delete(data: typing.Any, key_path: str) -> None:
    """Implement the del command."""
    target = data
    keys = split_dot(key_path)
    key: typing.Union[str, int]
    for index, key in enumerate(keys):
        if isinstance(target, list):
            key = int(key)
        if index < len(keys) - 1:
            target = target[key]
        else:
            del target[key]


def main(args: typing.Sequence[str]) -> None:
    """Run CLI YAML tool."""
    parser = argparse.ArgumentParser(description='Miscellaneous YAML operations')

    parser.add_argument('action', choices=('set-value', 'del'), help='Action to perform')
    parser.add_argument('key', help='Target for the action')
    parser.add_argument('value', nargs='?', help='YAML-formatted value')
    parsed_args = parser.parse_args(args)

    data = yaml.safe_load(sys.stdin)

    if parsed_args.action == 'set-value':
        set_value(data, parsed_args.key, parsed_args.value)
    elif parsed_args.action == 'del':
        delete(data, parsed_args.key)
    else:
        raise Exception(f'Unknown action {parsed_args.action}')

    yaml.safe_dump(data, stream=sys.stdout)


if __name__ == '__main__':
    main(sys.argv[1:])

```

pylint crashed with a ``AttributeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  [Previous line repeated 3 more times]
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/checkers/variables.py", line 1377, in visit_name
    self._undefined_and_used_before_checker(node, stmt)
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/checkers/variables.py", line 1419, in _undefined_and_used_before_checker
    action, nodes_to_consume = self._check_consumer(
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/checkers/variables.py", line 1680, in _check_consumer
    elif self._is_only_type_assignment(node, defstmt):
  File "/home/mh21/git/cki/cki-tools/.direnv/python-3.8.10/lib/python3.8/site-packages/pylint/checkers/variables.py", line 2072, in _is_only_type_assignment
    if node.name in self.linter.config.additional_builtins or utils.is_builtin(
AttributeError: 'Values' object has no attribute 'additional_builtins'
```

### Command used

```shell
pylint cki/cki_tools/yaml.py
```

### Pylint output

```shell
see above
```

### Expected behavior

no crash

### Pylint version

```shell
$ pylint --version
pylint 2.13.6
astroid 2.11.3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
```
```


### OS / Environment

Ubuntu 20.04 LTS

### Additional dependencies

_No response_

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, it look like we cherry-picked a commit that we could not cherry-pick.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas we might want to yank `2.13.6` asap. That build is broken.

Faulty commit is https://github.com/PyCQA/pylint/commit/ddca4dd30ebe3c7bb529a96a541192b73a5b1c85.

L2072 with `self.linter.config.additional_builtins` doesn't work.

**Comment by mbyrnepr2** [comment]
I don't see the crash happening on latest main:
```
pylint 2.14.0-dev0
astroid 2.11.3
Python 3.10.0b2
```

Can reproduce with 2.13.6 as reported.

**Comment by Pierre-Sassoulas** [comment]
>  we might want to yank 2.13.6 asap.

Yeah, the issue is that I don't have managing right. Let's release 2.13.7 after #6410
