### ISSUE TITLE
AttributeError: 'Values' object has no attribute 'additional_builtins'

### ISSUE THREAD

**Issue by acl-cqc** [PyCQA/pylint#6411]
### Bug description

Sorry I cannot provide code, but the final line in the stack trace may provide clues:
```
File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/checkers/variables.py", line 2072, in _is_only_type_assignment
    if node.name in self.linter.config.additional_builtins or utils.is_builtin(
AttributeError: 'Values' object has no attribute 'additional_builtins'
```

### Command used

```shell
pylint src/
```

### Pylint output

```shell
Exception on node <Name.result l.105 at 0x106ed6e50> in file '[snip].py'
Traceback (most recent call last):
  File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/checkers/variables.py", line 1377, in visit_name
    self._undefined_and_used_before_checker(node, stmt)
  File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/checkers/variables.py", line 1419, in _undefined_and_used_before_checker
    action, nodes_to_consume = self._check_consumer(
  File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/checkers/variables.py", line 1680, in _check_consumer
    elif self._is_only_type_assignment(node, defstmt):
  File "/Users/alanlawrence/tienv/lib/python3.9/site-packages/pylint/checkers/variables.py", line 2072, in _is_only_type_assignment
    if node.name in self.linter.config.additional_builtins or utils.is_builtin(
AttributeError: 'Values' object has no attribute 'additional_builtins'
```

### Expected behavior

Code was passing with pylint 2.13.5

### Pylint version

```shell
pylint 2.13.6
astroid 2.11.3, also 2.11.2
Python 3.9.10 (main, Jan 15 2022, 11:40:53) 
[Clang 13.0.0 (clang-1300.0.29.3)]
```

### OS / Environment

Mac OS X arm64

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, this will be fixed in #6410
