### ISSUE TITLE
Crash ``'Attribute' object has no attribute 'name'`` 

### ISSUE THREAD

**Issue by FPENGKAR** [PyCQA/pylint#6557]
### Bug description

```python
class A:
  pass

my_dict = {}
a = A()
for input_output in my_dict.items():
  a.input_output = input_output
  my_dict[a.input_output[0]]
```

### Command used

```shell
pylint with a settings file
```

### Pylint output

```shell
pylint crashed with a ``AttributeError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1034, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1069, in _check_file
    check_astroid_module(ast_node)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1203, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1250, in _check_astroid_module
    walker.walk(node)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 637, in visit_for
    self._check_unnecessary_dict_index_lookup(node)
  File "/home/azureuser/runners/ScenarioExtractor_runner/_work/_tool/Python/3.10.1/x64/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1906, in _check_unneces
sary_dict_index_lookup
    or node.target.name != value.value.name
AttributeError: 'Attribute' object has no attribute 'name'
```

### Expected behavior

Not fail? I think

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.0
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. Could you maybe provide the code extract that made pylint crash ?

**Comment by FPENGKAR** [comment]
No, I'm afraid that is not possible. However, it seems I managed to handle the bug by changing:

`for input_output in mydictionary.items();`

to:
`
for inputkey,outputkey in mydictionary.items():`

So it seems it doesn't like using a tuple?

**Comment by jacobtylerwalls** [comment]
Reproducer:
```python
class A:
  pass

my_dict = {}
a = A()
for input_output in my_dict.items():
  a.input_output = input_output
  my_dict[a.input_output[0]]
```
