### ISSUE TITLE
Could not find <Property.myfunc l.3 at 0x7f1c41ca7c40> in <TryExcept l.2 at 0x7f1c41c5b070>'s children

### ISSUE THREAD

**Issue by yilei** [PyCQA/pylint#6596]
When parsing the following file:

```python
def myfunc():
  try:
    @property
    def myfunc():
      return None
  except TypeError:
    pass

  @myfunc.setter
  def myfunc():
    pass

  return myfunc()

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1015, in visit_call
    self._check_raising_stopiteration_in_generator_next_call(node)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1078, in _check_raising_stopiteration_in_generator_next_call
    inferred = utils.safe_infer(node.func)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pylint/checkers/utils.py", line 1221, in safe_infer
    value = next(infer_gen)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 168, in infer
    yield from self._infer(context=context, **kwargs)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/inference.py", line 203, in infer_name
    frame, stmts = self.lookup(self.name)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 384, in lookup
    return self.scope().scope_lookup(self, name)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1810, in scope_lookup
    return super().scope_lookup(node, name, offset)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1245, in scope_lookup
    return frame._scope_lookup(node, name, offset)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/mixin.py", line 54, in _scope_lookup
    stmts = _filter_stmts(node, self.locals[name], self, offset)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/filter_statements.py", line 194, in _filter_stmts
    if not (optional_assign or nodes.are_exclusive(_stmts[pindex], node)):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 135, in are_exclusive
    c2attr, c2node = node.locate_child(previous)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 425, in locate_child
    raise AstroidError(msg % (repr(child), repr(self)))
astroid.exceptions.AstroidError: Could not find <Property.myfunc l.3 at 0x7f1c41ca7c40> in <TryExcept l.2 at 0x7f1c41c5b070>'s children
```

Version info:

```
$ pylint --version
pylint 2.13.8
astroid 2.11.4
Python 3.9.10 (main, Mar 16 2022, 06:54:08)
[GCC 11.2.0]
```

**Comment by jacobtylerwalls** [comment]
Reproduced on `main` and `pylint==2.6.0` and `astroid==2.6.0`

**Comment by Pierre-Sassoulas** [comment]
I suppose you meant pylint 2.14.0 and astroid 2.11.5 @jacobtylerwalls ?

**Comment by jacobtylerwalls** [comment]
No I just checked out early versions to make sure it wasn't caused recently!
