### ISSUE TITLE
Crash ``<lambda>() missing 1 required positional argument: 'scope_type'``

### ISSUE THREAD

**Issue by TylerYep** [PyCQA/pylint#6638]
### Bug description

pylint crashed with a ``TypeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 661, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 701, in _check_file
    check_astroid_module(ast_node)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 896, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 946, in _check_astroid_module
    walker.walk(node)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    callback(astroid)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 740, in wrap_func
    return with_method(orig_method, *args, **kwargs)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 318, in ignore_import_warnings_for_related_fields
    consumer._atomic = ScopeConsumer(new_things, consumer.consumed, consumer.scope_type)  # pylint: disable=W0212
TypeError: <lambda>() missing 1 required positional argument: 'scope_type'
```

Super long test file

pylint crashed with a ``TypeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 661, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 701, in _check_file
    check_astroid_module(ast_node)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 896, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 946, in _check_astroid_module
    walker.walk(node)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    callback(astroid)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 740, in wrap_func
    return with_method(orig_method, *args, **kwargs)
  File "/Users/tyler.yep/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 318, in ignore_import_warnings_for_related_fields
    consumer._atomic = ScopeConsumer(new_things, consumer.consumed, consumer.scope_type)  # pylint: disable=W0212
TypeError: <lambda>() missing 1 required positional argument: 'scope_type'
```
### Configuration

```ini
# [mypy]
# strict = True
# ignore_missing_imports = True
# allow_subclassing_any = True
# warn_unused_configs = True

# [mypy-*.migrations.*]
# ignore_errors = True

[tool:pytest]
DJANGO_SETTINGS_MODULE = simple_history.settings.local

[mypy]
warn_no_return = True
warn_redundant_casts = True
warn_return_any = False
warn_unreachable = True
warn_unused_ignores = True
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "simple_history.settings.local"

[pylint.MASTER]
ignore = migrations

[pylint.MESSAGES CONTROL]
load-plugins = pylint_django
enable =
    useless-suppression,
    deprecated-pragma,
    use-symbolic-message-instead,
disable =
    line-too-long,
    import-outside-toplevel,
    missing-docstring,
    invalid-name,
    duplicate-code,
    fixme,
    no-member,
    protected-access,
    too-few-public-methods,
    unused-argument,
    too-many-lines,
    no-self-use,
    too-many-instance-attributes,
    too-many-arguments,
    unused-variable,
    arguments-differ,
    too-many-public-methods,
    no-name-in-module,
    broad-except,
    attribute-defined-outside-init,

[isort]
profile = black

[flake8]
max-line-length = 88
extend-ignore = E203,F401,CCE001
```

### Command used

```shell
pre-commit
```

### Pylint output

```shell
See above
```

### Expected behavior

No crash, worked fine before on 2.13

### Pylint version

```shell
pylint 2.14
```

### Additional dependencies

Latest versions of:

django
freezegun
django-stubs
pylint-django

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, are you using ``2.14.0.b1`` ? What is your version of pylint-django ?

**Comment by jacobtylerwalls** [comment]
Thanks for the report. `pylint-django` added compatibility for the changes to `ScopeConsumer` in 2.13 [here, in pylint-django 2.5.3](https://github.com/PyCQA/pylint-django/commit/417f7cfb294a3613c0c1fcc94f07cde1309c6d69). The code in your stack trace, however, shows that it's executing the code before that commit.

**Comment by TylerYep** [comment]
Upgrading `pylint-django` fixed the issue for me, thanks!
