### ISSUE TITLE
deprecation_checker example is not working

### ISSUE THREAD

**Issue by theCapypara** [PyCQA/pylint#6656]
### Bug description

Trying to implement an checker based on the `deprecation_checker` example gives the following error when loading the plugin:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<path to venv>/lib/python3.10/site-packages/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "<path to venv>/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "<path to venv>/lib/python3.10/site-packages/pylint/lint/run.py", line 280, in __init__
    linter.load_plugin_modules(self._plugins)
  File "<path to venv>/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 645, in load_plugin_modules
    module.register(self)
  File "<path to cwd>/pylint_deprecated_checker.py", line 36, in register
    linter.register_checker(DeprecationChecker(linter))
  File "<path to venv>/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 773, in register_checker
    self.msgs_store.register_messages_from_checker(checker)
  File "<path to venv>/lib/python3.10/site-packages/pylint/message/message_definition_store.py", line 39, in register_messages_from_checker
    checker.check_consistency()
  File "<path to venv>/lib/python3.10/site-packages/pylint/checkers/base_checker.py", line 133, in check_consistency
    raise InvalidMessageError(error_msg)
pylint.exceptions.InvalidMessageError: Inconsistent checker part in message id 'W1505' (expected 'x04xx' because we already had ['W0402']).
```

Checker code (placed in `pylint_deprecated_checker.py`; I removed comments and some test prints, so the lines won't match the above traceback):
```py
from typing import TYPE_CHECKING

from pylint.checkers import BaseChecker, DeprecatedMixin

if TYPE_CHECKING:
    from pylint.lint import PyLinter


class DeprecationChecker(DeprecatedMixin, BaseChecker):
    name = "deprecated-function-call"

    def deprecated_methods(self) -> set[str]:
        return set()

    def deprecated_arguments(self, method: str) -> tuple[tuple[int | None, str], ...]:
        return ()

def register(linter: 'PyLinter') -> None:
    linter.register_checker(DeprecationChecker(linter))
```

### Configuration

```ini
[MAIN]
ignore-patterns=.*?_test.py

disable=all

enable=
    deprecated-method

jobs=0
suggestion-mode=yes

fail-under=9.0
fail-on=deprecated-method
```

### Command used

```shell
PYTHONPATH="." python -m pylint path_to_code --load-plugins=pylint_deprecated_checker --rcfile=pylintrc
```

### Pylint output

```shell
See bug description.
```

### Expected behavior

I expected the checker to initialize correctly.

### Pylint version

```shell
pylint 2.13.9
astroid 2.11.5
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
```

### OS / Environment

Arch Linux

**Comment by theCapypara** [comment]
Additonally, the example needs to be updated to define the attribute `__implements__ = (IAstroidChecker,)`.

**Comment by Pierre-Sassoulas** [comment]
``__implements__ = (IAstroidChecker,).`` is based [on the very old rejected PEP245](https://peps.python.org/pep-0245/#rejection-notice), we removed that for inheritance #6393. The problem here is that the documentation is for 2.14.0 that is not yet released. Could you try using the beta ?

**Comment by mbyrnepr2** [comment]
There does seem to be a duplication of message IDs once the example `deprecation_checker.py` is copied to `/pylint/pylint/checkers/`

Adding this class variable to the `deprecation_checker.DeprecationChecker` class seems to solve it:
```python
msgs = {**{k: v for k, v in DeprecatedMixin.msgs.items() if k[1:3] == "15"}}
```

**Comment by jacobtylerwalls** [comment]
Right, 15XX is used by the current stdlib checker. I think most helpful would be to document the use of this script:
```python
% python3 script/get_unused_message_id_category.py 
Next free message id category is 31
Please use 3101 for the first message of the new checker
```
