### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'name'

### ISSUE THREAD

**Issue by PiotrBatko-BlockchainWares** [PyCQA/pylint#6709]
### Bug description

Minimal example causing crash:
```
class Item:
    def __init__(self, parent):
        self.__parent = parent
        self.__item = self.__parent.__item
```

Code more similar to my real use case, maybe it will add some context:
```
from __future__ import annotations

from typing import Optional


class Item:
    def __init__(self, parent: Optional[Item] = None):
        self.__parent = parent
        self.__item = self.__parent.__item if parent is not None else 'default'
```

### Command used

```shell
echo -e "class Item:\n    def __init__(self, parent):\n        self.__parent = parent\n        self.__item = self.__parent.__item" > reproduce_error.py
pylint reproduce_error.py
```

### Pylint output

```shell
************* Module reproduce_error
reproduce_error.py:1:0: C0114: Missing module docstring (missing-module-docstring)
reproduce_error.py:1:0: C0115: Missing class docstring (missing-class-docstring)
reproduce_error.py:4:22: W0212: Access to a protected member __item of a client class (protected-access)
Exception on node <ClassDef.Item l.1 at 0x7f3880eb0730> in file '/home/dev/Desktop/pylint-error/reproduce_error.py'
Traceback (most recent call last):
  File "/home/dev/Desktop/pylint-error/venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 78, in walk
    callback(astroid)
  File "/home/dev/Desktop/pylint-error/venv/lib/python3.8/site-packages/pylint/checkers/classes/class_checker.py", line 877, in leave_classdef
    self._check_unused_private_attributes(node)
  File "/home/dev/Desktop/pylint-error/venv/lib/python3.8/site-packages/pylint/checkers/classes/class_checker.py", line 996, in _check_unused_private_attributes
    and attribute.expr.name == "self"
AttributeError: 'Attribute' object has no attribute 'name'
reproduce_error.py:1:0: F0001: Fatal error while checking 'reproduce_error.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/dev/.cache/pylint/pylint-crash-2022-05-26-18.txt'. (fatal)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

No crash.

### Pylint version

```shell
pylint 2.13.9
astroid 2.11.5
Python 3.8.13 (default, Apr 19 2022, 00:53:22) 
[GCC 7.5.0]
```

### OS / Environment

Ubuntu 20.04.4 LTS

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, I can reproduce on the main branch .

**Comment by PiotrBatko-BlockchainWares** [comment]
I noticed that it stops to crash, when I change `self.__item` to be a public member.
```
class Item:
    def __init__(self, parent):
        self.__parent = parent
        self.item = self.__parent.item
```
