### ISSUE TITLE
crash with IndexError

### ISSUE THREAD

**Issue by libourel** [PyCQA/pylint#6711]
# Description
The simple piece of Python code below (a maximally stripped-down version of the original code) causes pylint(1) to error out with a stacktrace ending in an IndexError exception.
Changing almost any line of the code causes the crash to not happen.

# Input
```
class C:
  def f(self):
    s = ""
    if True:
      if True:
        s = ""
    elif True:
      if (s := self.g(s)):
        s = ""
    elif True:
      if True:
        s = ""
      else:
        s = ""
    else:
      pass
    print("%s%s" % (s, s))
```

# Reproduce
`pylint --rcfile=./pylint.rc test.py`

# Environment
```
$ pylint --version
pylint 2.7.2
astroid 2.5.1
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110]
```

# Output
```
test.py:1:0: C0103: Class name "C" doesn't conform to PascalCase naming style (invalid-name)
Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.7.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/usr/lib/python3/dist-packages/pylint/checkers/strings.py", line 390, in visit_binop
    arg_type = utils.safe_infer(arg)
  File "/usr/lib/python3/dist-packages/pylint/checkers/utils.py", line 1205, in safe_infer
    value = next(infer_gen)
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 366, in infer
    yield from self._infer(context, **kwargs)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 135, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/lib/python3/dist-packages/astroid/decorators.py", line 96, in wrapped
    generator = _func(node, context, **kwargs)
  File "/usr/lib/python3/dist-packages/astroid/inference.py", line 192, in infer_name
    frame, stmts = self.lookup(self.name)
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 1090, in lookup
    return self.scope().scope_lookup(self, name)
  File "/usr/lib/python3/dist-packages/astroid/scoped_nodes.py", line 1762, in scope_lookup
    return super().scope_lookup(node, name, offset)
  File "/usr/lib/python3/dist-packages/astroid/scoped_nodes.py", line 1275, in scope_lookup
    return frame._scope_lookup(node, name, offset)
  File "/usr/lib/python3/dist-packages/astroid/scoped_nodes.py", line 203, in _scope_lookup
    stmts = node._filter_stmts(self.locals[name], self, offset)
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 1217, in _filter_stmts
    if _stmts[pindex].assign_type().parent_of(assign_type):
IndexError: list index out of range
```

**Comment by DudeNr33** [comment]
Hi @libourel,
you are running an old version of `pylint` and `astroid`. The current version is `pylint` V2.13.9.

I could not reproduce the issue with this current version. Can you please upgrade your installation of `pylint` and check if this resolves the issue for you?

**Comment by Pierre-Sassoulas** [comment]
You might be using the debian packaged version of pylint, that is lagging a little behind. Pylint has been **very** active since 2.7.2 was packaged in debian. You can use pip to have the latest version see https://pylint.pycqa.org/en/latest/user_guide/installation/command_line_installation.html :)

**Comment by libourel** [comment]
I am indeed using a Debian-based distro. If this issue has been fixed in newer releases, please ignore this ticket and I will try using pylint again when Debian updates it.

**Comment by Pierre-Sassoulas** [comment]
You could also upgrade debian to bookworm that has pylint 2.12.2, it's still behind but less.
