### ISSUE TITLE
PyLint 2.14 throws error if user home can't be determined

### ISSUE THREAD

**Issue by yoerg** [PyCQA/pylint#6802]
### Bug description

Since #6067, pylint exits with `RuntimeError: Can't determine home directory` if the user home directory can't be determined, which was previously ignored.

### Command used

```shell
# Windows
set USERPROFILE=
set HOMEPATH=
set HOMEDRIVE=

pylint a.py

# On Linux, run pylint as a user without a home dir (just removing HOME isn't enough)
```

### Pylint output

```shell
Traceback (most recent call last):
  File "c:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\daten\tools\Python38\Scripts\pylint.exe\__main__.py", line 7, in <module>
  File "c:\python\python38\lib\site-packages\pylint\__init__.py", line 22, in run_pylint
    from pylint.lint import Run as PylintRun
  File "c:\python\python38\lib\site-packages\pylint\lint\__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "c:\python\python38\lib\site-packages\pylint\config\__init__.py", line 27, in <module>
    from pylint.config.environment_variable import PYLINTRC
  File "c:\python\python38\lib\site-packages\pylint\config\environment_variable.py", line 11, in <module>
    PYLINTRC = find_pylintrc()
  File "c:\python\python38\lib\site-packages\pylint\config\find_default_config_files.py", line 90, in find_pylintrc
    for config_file in find_default_config_files():
  File "c:\python\python38\lib\site-packages\pylint\config\find_default_config_files.py", line 66, in find_default_config_files
    user_home = Path.home()
  File "c:\python\python38\lib\pathlib.py", line 1103, in home
    return cls(cls()._flavour.gethomedir(None))
  File "c:\python\python38\lib\pathlib.py", line 266, in gethomedir
    raise RuntimeError("Can't determine home directory")
RuntimeError: Can't determine home directory
```

### Expected behavior

I'd expect pylint to not search for a _pylintrc_ file if the user has no home directory, i.e. silently ignore the error.

### Pylint version

```shell
pylint 2.14.0
astroid 2.11.5
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
```

### OS / Environment

Tested on Windows, probably occurs on every platform.

**Comment by Pierre-Sassoulas** [comment]
The error comes from pathlib. I suppose it make sense to use the default though.

**Comment by yoerg** [comment]
Thanks for the fix!
