### ISSUE TITLE
init-hook no longer supports multi-line hook

### ISSUE THREAD

**Issue by jgosmann** [PyCQA/pylint#6888]
### Bug description

Up to version 2.13.9 multi-line init-hook configurations like the following were supported:

```
init-hook=
    try: import pylint_venv
    except ImportError: pass
    else: pylint_venv.inithook()
```

From version 2.14.0 on this no longer works. The error looks like the lines are joined into a single line:

```
❯ pylint test.py
Traceback (most recent call last):
  File "/Users/jgosmann/Library/Python/3.8/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/__init__.py", line 25, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/lint/run.py", line 151, in __init__
    args = _config_initialization(
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/config/config_initialization.py", line 48, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
  File "<string>", line 1
    try: import pylint_venvexcept ImportError: passelse: pylint_venv.inithook()
                                  ^
SyntaxError: invalid syntax
```

### Configuration

```ini
init-hook=
    try: import pylint_venv
    except ImportError: pass
    else: pylint_venv.inithook()
```
```


### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/Users/jgosmann/Library/Python/3.8/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/__init__.py", line 25, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/lint/run.py", line 151, in __init__
    args = _config_initialization(
  File "/Users/jgosmann/Library/Python/3.8/lib/python/site-packages/pylint/config/config_initialization.py", line 48, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
  File "<string>", line 1
    try: import pylint_venvexcept ImportError: passelse: pylint_venv.inithook()
                                  ^
SyntaxError: invalid syntax
```

### Expected behavior

The init-hook runs without a syntax error.

### Pylint version

```shell
pylint 2.14.0 (and 2.14.1)
astroid 2.11.5
Python 3.8.13 (default, May 10 2022, 11:26:18)
[Clang 13.0.0 (clang-1300.0.29.3)]
```

### Additional dependencies

pylint-venv==2.2.0

**Comment by JonathanCasey** [comment]
I have also run into this in pylint 2.14.1.  The workaround I found is to add a semicolon to the end of each line.  This seems to allow it to still execute each statement after joining the lines into a single line.

**Comment by jgosmann** [comment]
This does not seem to work for try-except.
