### ISSUE TITLE
pylint installing issue

### ISSUE THREAD

**Issue by YouseefSaad** [PyCQA/pylint#7164]
### Question

it's my first time using pylint while I am trying to install it,always crashes at the end with many errors I don't understand.
I would be thankful if anyone would help me.

### Documentation for future user

pip install pylint
Collecting pylint
  Downloading pylint-2.14.4-py3-none-any.whl (488 kB)
     ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/488.4 kB ? eta -:--:--
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 291, in __init__
    super().__init__(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\network\download.py", line 146, in __call__
    for chunk in chunks:
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 509, in read
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

### Additional context

python version: 3.10

**Comment by Pierre-Sassoulas** [comment]
I'm going to close as it look like a connection issue from your end raised by pip (enterprise proxy ?)

**Comment by YouseefSaad** [comment]
I have successfully installed it. but while using it an issue showed up :
 pylint.exe C:\Users\Hp\source\repos\PythonApplication30C:\Users\Hp\source\repos\PythonApplication30
************* Module C:\Users\Hp\source\repos\PythonApplication30C:\Users\Hp\source\repos\PythonApplication30
C:\Users\Hp\source\repos\PythonApplication30C:\Users\Hp\source\repos\PythonApplication30:1:0: F0001: No module named C:\Users\Hp\source\repos\PythonApplication30C:\Users\Hp\source\repos\PythonApplication30 (fatal)

**Comment by Pierre-Sassoulas** [comment]
``pylint.exe C:\Users\Hp\source\repos\PythonApplication30C:\Users\Hp\source\repos\PythonApplication30`` is the same path duplicated, use ``pylint.exe C:\Users\Hp\source\repos\PythonApplication30`` instead.
