### ISSUE TITLE
Pylint crashes if base class's setter and getter are the wrong way round

### ISSUE THREAD

**Issue by omarandlorraine** [PyCQA/pylint#7174]
### Bug description

While I was working on filing #7172 I discovered a file that causes pylint to actually crash.

```
# pylint: disable=C0116,C0114,C0303,C0115,R0903
class Duff:
    def __init__(self):
        self._duff = None

    @duff.setter
    def duff(self, value):
        self._duff = value

    @property
    def duff(self):
        return self._duff

class DuffPlusOne(Duff):
    
    def __init__(self):
        super().__init__()
        self._duff = None

    @duff.setter
    def duff(self, value):
        self._duff = value + 1
```

The contents of the file is basically the same, but I reversed the order or the setter and getter.

### Command used

```shell
pylint duff.py
```

### Pylint output

```shell
************* Module duff
duff.py:11:4: E0102: method already defined line 7 (function-redefined)
Exception on node <FunctionDef.duff l.21 at 0x7fea1e6fbd30> in file '/home/sam/mcve/duff.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pylint-2.14.0.dev0-py3.9.egg/pylint/utils/ast_walker.py", line 82, in walk
    callback(astroid)
  File "/usr/local/lib/python3.9/dist-packages/pylint-2.14.0.dev0-py3.9.egg/pylint/checkers/classes/class_checker.py", line 1126, in visit_functiondef
    self._check_invalid_overridden_method(node, parent_function)
  File "/usr/local/lib/python3.9/dist-packages/pylint-2.14.0.dev0-py3.9.egg/pylint/checkers/classes/class_checker.py", line 1355, in _check_invalid_overridden_method
    or uninferable_final_decorators(parent_function_node.decorators
  File "/usr/local/lib/python3.9/dist-packages/pylint-2.14.0.dev0-py3.9.egg/pylint/checkers/utils.py", line 842, in uninferable_final_decorators
    import_node = decorator.expr.lookup(decorator.expr.name)[1][0]
IndexError: tuple index out of range
duff.py:1:0: F0001: Fatal error while checking 'duff.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/sam/.cache/pylint/pylint-crash-2022-07-12-14.txt'. (fatal)
```

### Expected behavior

Pylint should at least succeed in analyzing the file

### Pylint version

```shell
pylint 2.14.0-dev0
astroid 2.11.2
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
```

### OS / Environment

Debian Buster

**Comment by omarandlorraine** [comment]
Oh terrific, someone must already have found that bug and sorted it out somehow. Thanks for taking a look @Pierre-Sassoulas

**Comment by omarandlorraine** [comment]
Ooops, I closed it as "completed"; should it have a different close reason?
