### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by OldShaterhan** [PyCQA/pylint#7297]
### Bug description

When parsing the following file:

```python
"""Support for information about the HAFAS-based train systems."""
from __future__ import annotations

from pyhafas import HafasClient
from pyhafas.profile import DBProfile

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant

from .const import DOMAIN

ICON = "mdi:train"


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HAFAS from a config entry."""
    hass.data.setdefault(DOMAIN, {})
    hass.data[DOMAIN][entry.entry_id] = HafasClient(DBProfile(), debug=True)

    return

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1832, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1849, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

Issue title:
Crash ```` (if possible, be more specific about what made pylint crash)
Content:
When parsing the following file:

```python
"""Support for information about the HAFAS-based train systems."""
from __future__ import annotations

from pyhafas import HafasClient
from pyhafas.profile import DBProfile

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from .const import DOMAIN

ICON = "mdi:train"


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HAFAS from a config entry."""
    hass.data.setdefault(DOMAIN, {})
    hass.data[DOMAIN][entry.entry_id] = HafasClient(DBProfile(), debug=True)

    return

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1832, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1849, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

Issue title:
Crash ```` (if possible, be more specific about what made pylint crash)
Content:
When parsing the following file:

```python
"""Support for information about the HAFAS-based train systems."""
from __future__ import annotations

from pyhafas import HafasClient
from pyhafas.profile import DBProfile

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from .const import DOMAIN

ICON = "mdi:train"


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HAFAS from a config entry."""
    hass.data.setdefault(DOMAIN, {})
    hass.data[DOMAIN][entry.entry_id] = HafasClient(DBProfile(), debug=True)

    return True

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1832, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1849, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

Issue title:
Crash ```` (if possible, be more specific about what made pylint crash)
Content:
When parsing the following file:

```python
"""Support for information about the HAFAS-based train systems."""
from __future__ import annotations

from pyhafas import HafasClient
from pyhafas.profile import DBProfile

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from .const import DOMAIN

ICON = "mdi:train"


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HAFAS from a config entry."""
    hass.data.setdefault(DOMAIN, {})
    hass.data[DOMAIN][entry.entry_id] = HafasClient(DBProfile(), debug=True)

    return True

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1832, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1849, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
Pylint used via Home Assistant
```

### Pylint output

```shell
Exception on node <AsyncFunctionDef.async_setup_entry l.15 at 0x7f8ff9a2a7c0> in file '/workspaces/ha-core/homeassistant/components/hafas/sensor.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1832, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/ha-core/pylint/plugins/hass_enforce_type_hints.py", line 1849, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range
homeassistant/components/hafas/sensor.py:1:0: F0002: homeassistant/components/hafas/sensor.py: Fatal error while checking 'homeassistant/components/hafas/sensor.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/root/.cache/pylint/pylint-crash-2022-08-11-22.txt'. (astroid-error)
```

### Expected behavior

It should work

### Pylint version

```shell
pylint 2.14.4
astroid 2.11.7
Python 3.9.12 (main, Apr  7 2022, 04:19:52) 
[GCC 10.2.1 20210110]
```

**Comment by jacobtylerwalls** [comment]
Thanks for the report, but the traceback shows that the error is coming from a plugin: `hass_enforce_type_hints.py`. You should report it to its owner.
