### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'name'

### ISSUE THREAD

**Issue by itttgg** [PyCQA/pylint#7380]
### Bug description

Linting:
```python
lst = []
for _var in lst:
    del _var
```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 769, in _lint_file
    check_astroid_module(module)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1029, in check_astroid_module
    retval = self._check_astroid_module(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1079, in _check_astroid_module
    walker.walk(node)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 60, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 66, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 96, in _modified_iterating_check
    args=(iter_obj.name,),
AttributeError: 'Attribute' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 734, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 771, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

No crash.

### Pylint version

```shell
pylint-2.15.0
astroid-2.12.5
CPython 3.8.13
```

### OS / Environment

ubuntu-latest

**Comment by DanielNoord** [comment]
Note that the error in the OP doesn't actually reproduce. The post before the edit does provide the necessary info though.


@itttgg As I had to dive into your codebase to find the issue I had a look around. I noticed that you use `NoReturn` to annotate functions that don't return anything. This is unsolicited advice but you should use `-> None` for such functions. `NoReturn` implies that a function will always raise an exception, see https://docs.python.org/3/library/typing.html#typing.NoReturn.
An `__init__` does return, it just returns nothing, thus the `-> None`.

For the issue reported I have pushed a fix!

**Comment by itttgg** [comment]
> I noticed that you use `NoReturn` to annotate functions that don't return anything. This is unsolicited advice but you should use `-> None` for such functions. `NoReturn` implies that a function will always raise an exception, see https://docs.python.org/3/library/typing.html#typing.NoReturn. An `__init__` does return, it just returns nothing, thus the `-> None`.

I thought that `NoReturn == None`, but it's not. Sorry

**Comment by DanielNoord** [comment]
> I thought that `NoReturn == None`, but it's not. Sorry

No problem, just thought I'd let you know. A year ago I had never even heard of Python typing. We're all just learning about it 😄

**Comment by itttgg** [comment]
> No problem, just thought I'd let you know. A year ago I had never even heard of Python typing. We're all just learning about it 😄

I mean, is there a difference?

**Comment by DanielNoord** [comment]
Between `NoReturn` and `None`?

**Comment by itttgg** [comment]
> Between `NoReturn` and `None`?

Yes

**Comment by DanielNoord** [comment]
Yeah!

For example:
```python
def func(x: int) -> None:
    print(x)
    x = x + 1
    print(x)

def func_two(x: int) -> NoReturn:
    print(x)
    raise ValueError

func()
func_two()
```

With the following code, `func_two` will execute after `func` and then the program exists with a `ValueError`.
If you switch them around `func` will never be executed as the program already stops at the `ValueError` raised by `func_two`. That's why `NoReturn` is helpful. It shows that without some mitigation calling a certain function will create an error that will terminate the program.

**Comment by itttgg** [comment]
> With the following code, `func_two` will execute after `func` and then the program exists with a `ValueError`. If you switch them around `func` will never be executed as the program already stops at the `ValueError` raised by `func_two`. That's why `NoReturn` is helpful. It shows that without some mitigation calling a certain function will create an error that will terminate the program.

Ok i'm fix this error in my code

**Comment by jacobtylerwalls** [comment]
> Note that the error in the OP doesn't actually reproduce. The post before the edit does provide the necessary info though.

Sorry @DanielNoord, I was the one who did the edit. I was trying to bisect the file to get to the minimum reproducer, and I guess I made a mistake somewhere.
