### ISSUE TITLE
pylint crashes when linting python-daemon

### ISSUE THREAD

**Issue by eaufavor** [PyCQA/pylint#740]
pylint2 crashes when linting the following simple file
```
import daemon
a = daemon.DaemonContext()
```
Output:
```
Traceback (most recent call last):
  File "/usr/bin/pylint2", line 9, in <module>
    load_entry_point('pylint==1.5.1', 'console_scripts', 'pylint')()
  File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 945, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/usr/lib/python2.7/site-packages/pylint/checkers/base.py", line 1946, in visit_assign
    if var_type == astroid.YES or var_type.as_string() == 'None':
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 611, in as_string
    return to_code(self)
  File "/usr/lib/python2.7/site-packages/astroid/as_string.py", line 79, in __call__
    return node.accept(self)
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 395, in accept
    return func(self)
  File "/usr/lib/python2.7/site-packages/astroid/as_string.py", line 163, in visit_classdef
    self._stmt_list(node.body))
  File "/usr/lib/python2.7/site-packages/astroid/as_string.py", line 83, in _stmt_list
    stmts = '\n'.join([nstr for nstr in [n.accept(self) for n in stmts] if nstr])
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 395, in accept
    return func(self)
  File "/usr/lib/python2.7/site-packages/astroid/as_string.py", line 296, in visit_functiondef
    body=self._stmt_list(node.body))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 774: ordinal not in range(128)
```

It happens only when DaemonContext is called.  The rest functions of daemon seem fine. 

The package is here
https://pypi.python.org/pypi/python-daemon/

**Comment by PCManticore** [comment]
This seems fixed by https://github.com/PyCQA/astroid/commit/900747213bfb106eacf650e09ef821b3289df2ac. Could you give it a try and see if it solves your problem? I'll try to do a new bug fix release, but I can't promise when, since I have a pretty hectic schedule this week.

**Comment by eaufavor** [comment]
@PCManticore Yes, that fixed this issue. Good work! 

The archlinux package I'm using, python2-astroid 1.4.1, was created Nov 30 from the astroid bitbucket repo. This patch was not there until Dec 1. Hence the problem. I will talk to the package maintainers.
