### ISSUE TITLE
Crash with .AstroidError when parsing a dict with a lambda as the key

### ISSUE THREAD

**Issue by Tomalak** [PyCQA/pylint#7453]
### Bug description

pylint crashes over this code

test.py

```python
a = {
    (lambda x: print(x)): 'foo'
}
```

### Command used

```shell
> pylint C:\test.py
```

### Pylint output

```shell
************* Module test
test.py:3:0: C0304: Final newline missing (missing-final-newline)
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Exception on node <Dict.dict l.1 at 0x1e448164df0> in file 'C:\test.py'
Traceback (most recent call last):
  File "C:\Python310\site-packages\pylint\utils\ast_walker.py", line 90, in walk
    callback(astroid)
  File "C:\Python310\site-packages\pylint\checkers\typecheck.py", line 2036, in visit_dict
    if not is_hashable(k):
  File "C:\Python310\site-packages\pylint\checkers\utils.py", line 1945, in is_hashable
    hash_fn = next(inferred.igetattr("__hash__"))
AttributeError: 'Lambda' object has no attribute 'igetattr'
test.py:1:0: F0002: test.py: Fatal error while checking 'test.py'. Please open an issue in our bug tracker so we address this [...]. (astroid-error)

-8<--------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Python310\site-packages\pylint\lint\pylinter.py", line 782, in _lint_file
    check_astroid_module(module)
  File "C:\Python310\site-packages\pylint\lint\pylinter.py", line 1049, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Python310\site-packages\pylint\lint\pylinter.py", line 1099, in _check_astroid_module
    walker.walk(node)
  File "C:\Python310\site-packages\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Python310\site-packages\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Python310\site-packages\pylint\utils\ast_walker.py", line 90, in walk
    callback(astroid)
  File "C:\Python310\site-packages\pylint\checkers\typecheck.py", line 2036, in visit_dict
    if not is_hashable(k):
  File "C:\Python310\site-packages\pylint\checkers\utils.py", line 1945, in is_hashable
    hash_fn = next(inferred.igetattr("__hash__"))
AttributeError: 'Lambda' object has no attribute 'igetattr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\site-packages\pylint\lint\pylinter.py", line 747, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "C:\Python310\site-packages\pylint\lint\pylinter.py", line 784, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

No crash. :)

### Pylint version

```shell
pylint 2.15.2
astroid 2.12.9
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
```

### OS / Environment

Windows 10

**Comment by jacobtylerwalls** [comment]
Thanks for the report, regression in 1e2094d1e9192befedef7984b0b59d9234c6a7dd.
