### ISSUE TITLE
pylint -j2 with stdout redirect fails with RecursionError

### ISSUE THREAD

**Issue by tulinski** [PyCQA/pylint#7516]
### Bug description

When pylint is run with multiple processes (-j flag) and stdout is redirected to a file it throws RecursionError-s infinitely.
The same command without stdout redirection runs properly.

### Command used

```shell
# a.py is some minimal python module file

pylint -j2 a.py 1>pylint.out 2>pylint.err

# the above command without redirections works
```

### Pylint output

```shell
####### pylint.err #######

Process ForkPoolWorker-1:
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/tulinski/.local/lib/python3.8/site-packages/pylint/lint/parallel.py", line 44, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/tulinski/.local/lib/python3.8/site-packages/pylint/lint/parallel.py", line 44, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded
Process ForkPoolWorker-3:
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/tulinski/.local/lib/python3.8/site-packages/pylint/lint/parallel.py", line 44, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/tulinski/.local/lib/python3.8/site-packages/pylint/lint/parallel.py", line 44, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded

####### KEEPS THROWING THE SAME KIND OF EXCEPTION ... #######
```

### Expected behavior

Pylint works correctly with and without stdout redirection.

### Pylint version

```shell
pylint 2.15.3
astroid 2.12.10
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
```

### OS / Environment

Ubuntu 20.04.5 LTS

**Comment by DanielNoord** [comment]
You need to update your local version of `colorama` I think. It seems like you're using a version we no longer support.

**Comment by tulinski** [comment]
Thank you @DanielNoord for a prompt response. Why pylint does not require colorama>=0.4.5 then?

**Comment by DanielNoord** [comment]
We do! You can check our `pyproject.toml`.

**Comment by DanielNoord** [comment]
Although we don't do so on Linux. I didn't know `colorama` was used on Linux... Isn't it a Windows tool?

**Comment by tulinski** [comment]
Why for sys_platform=='win32' then? :)

**Comment by tulinski** [comment]
I'm not sure. It is somehow in my stack trace, though. ;)

**Comment by DanielNoord** [comment]
The problem is that I don't think we can set dependencies based on the environment.
We don't want users to have to install `colorama` on Linux or Mac as it is unnecessary. But we can't say: if you're on Linux don't install `colorama` but if you do, install this and that version.

I'll have a look at our code to see if I can put the `colorama` behind a platform check but I think it already is.

**Comment by tulinski** [comment]
@DanielNoord, thanks for clarifying.
FYI, I checked and in our case depencencies are: optuna -> cliff -> cmd2 -> colorama.

**Comment by DanielNoord** [comment]
I'm on mobile right now so I can't check, but it might be worth checking if `cmd2` also shouldn't make their dependency platform dependent. Based on the documentation of `colorama` it seems to provide a Windows solution to things that Linux and Mac have out of the box.

**Comment by tulinski** [comment]
From 2.3.0 `cmd2` does not depend on `colorama`. We will bump up some of our dependencies to get rid of `colorama`. Thank you for your help!

**Comment by DanielNoord** [comment]
No worries!

**Comment by DanielNoord** [comment]
For future me, I did check how we use `colorama` but it is behind a `sys.platform == "win32"` check so I don't really know how it is being imported on Linux. But since the fix for this is relatively simple (`colorama` doesn't break backwards compatible support in most of its releases) I don't think this requires any further action from us.
