### ISSUE TITLE
regression: modified_iterating_checker exception

### ISSUE THREAD

**Issue by belm0** [PyCQA/pylint#7528]
### Bug description

modified_iterating_checker exception on code that passes fine with earlier pylint versions

```python
from enum import Enum

class MyEnum(Enum):
    FOO = 1
    BAR = 2

class MyClass:
    ENUM_SET = {MyEnum.FOO, MyEnum.BAR}

    def useless(self):
        other_set = set(self.ENUM_SET)
        for item in self.ENUM_SET:
            other_set.remove(item)
```

### Command used

```shell
pylint
```

### Pylint output

```shell
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/.../lib/python3.8/site-pac
kages/pylint/lint/pylinter.py", line 782, in _lint_file
    check_astroid_module(module)
  File "/.../lib/python3.8/site-pac
kages/pylint/lint/pylinter.py", line 1049, in check_astroid_module
    retval = self._check_astroid_module(
  File "/.../lib/python3.8/site-pac
kages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(node)
  File "/.../lib/python3.8/site-pac
kages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/.../lib/python3.8/site-pac
kages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/.../lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/.../lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 60, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 68, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 66, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 90, in _modified_iterating_check
    elif self._modified_iterating_set_cond(node, iter_obj):
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 177, in _modified_iterating_set_cond
    self._common_cond_list_set(node, iter_obj, infer_val)
  File "/.../lib/python3.8/site-packages/pylint/checkers/modified_iterating_checker.py", line 120, in _common_cond_list_set
    node.value.func.expr.name == iter_obj.name
AttributeError: 'Attribute' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../lib/python3.8/site-packages/pylint/lint/pylinter.py", line 747, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/.../lib/python3.8/site-packages/pylint/lint/pylinter.py", line 784, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

no error

### Pylint version

```shell
pylint 2.15.3
astroid 2.12.10
Python 3.8.12 (default, Sep 23 2021, 08:42:37)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by belm0** [comment]
@Pierre-Sassoulas I'd updated the original report with a reproduction, please take another look.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue and the reproducer, this fail on main.

**Comment by DanielNoord** [comment]
@orSolocate Do you want to take a look at this?

**Comment by clavedeluna** [comment]
Tested in the following versions of pylint

2.13.0 (can repro same error as issue)
2.14.0 (can't repro) 
2.15.0 (can't repro) 
2.15.2, 2.15.3 (can repro same error as issue)

So issue was there in the original implementation of the modified iterating checker, fixed in a couple minor versions, then came back up again. If I have more time today I can continue to look into this.

**Comment by clavedeluna** [comment]
Git bisect suggests [this commit](https://github.com/PyCQA/pylint/commit/bcd4ca3052411e8c0823712d38cb970e354713f6) brought the issue back in pylint v2.15.2

I can continue with the fix later today.

**Comment by orSolocate** [comment]
@clavedeluna  thanks for the fix man!
