### ISSUE TITLE
Crash with `-j 2` when linting empty file

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#7635]
### Bug description

Noticed this crash while linting an empty file with `-j 2`. It might be OS dependent as so far I can only reproduce it on MacOS. Linux seems fine.

Bisected the issue to https://github.com/PyCQA/pylint/pull/7284.
In particular this line:
https://github.com/PyCQA/pylint/blob/77e8ae4f3902697babb186482f577a2c8b1a3725/pylint/lint/pylinter.py#L379

/CC: @daogilvie, @DanielNoord

### Command used

```shell
pylint -j 2 test.py
```

### Pylint output

```shell
(venv-310) $ pylint -j 2 test.py 
Traceback (most recent call last):
  File "/.../pylint/venv-310/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint', 'console_scripts', 'pylint')())
  File "/.../pylint/pylint/__init__.py", line 35, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/.../pylint/pylint/lint/run.py", line 207, in __init__
    linter.check(args)
  File "/.../pylint/pylint/lint/pylinter.py", line 668, in check
    check_parallel(
  File "/.../pylint/pylint/lint/parallel.py", line 141, in check_parallel
    jobs, initializer=initializer, initargs=[dill.dumps(linter)]
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 687, in save_reduce
    save(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/.../pylint/venv-310/lib/python3.10/site-packages/dill/_dill.py", line 1439, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 1076, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class 'astroid.util.Uninferable'>: it's not the same object as astroid.util.Uninferable
```

### Expected behavior

_No crash_

### Pylint version

```shell
pylint 2.16.0-dev
astroid 2.13.0-dev0
Python 3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]
```

### OS / Environment

MacOS

**Comment by daogilvie** [comment]
Ah, that's a shame — I did not explicitly think to check if the module object could be pickled to synch across processes/threads. I think I know what might be worth trying though — I'll look into this shortly.

**Comment by daogilvie** [comment]
Right, my immediate feeling is the core issue is that the contents of the `_dynamic_plugins` dictionary is not pickleable, hence the `dill.dumps` call in `check_parallel` crashes: https://github.com/PyCQA/pylint/blob/77e8ae4f3902697babb186482f577a2c8b1a3725/pylint/lint/parallel.py#L136-L141
I think it would be appropriate to zero-out the `self._dynamic_plugins` dictionary before the call to `dill.dumps`, as I **think** that by this point the custom modules have already been registered and had their configuration loaded. 
I propose one of two things:
1. Zero out the dictionary at the end of [load_plugin_configuration](https://github.com/PyCQA/pylint/blob/77e8ae4f3902697babb186482f577a2c8b1a3725/pylint/lint/pylinter.py#L383-L405), where everything has been done and the contents are no longer needed. OR
2. Add an explicit method+call in `check_parallel` (as above) to zero out the dictionary before the Pool is set up.

If we don't want to zero the dictionary, we have to add extra complexity to the plugin loader itself. I don't know what would be involved to have entirely pickle-able values — this would also exclude the ModuleNotFoundError I think, as it might contains a traceback or frame.

I'll trial option 1 in a branch now, see if that tanks some tests.

**Comment by daogilvie** [comment]
Ok, linked PR #7640 addresses this issue. The failing tests were failing before the commit, and running `pylint -j 2 test.py` on an empty file no longer crashes.
Happily today was mostly a series of all-hands broadcast meetings at work, so I was able to jump in and fix the mess I made here in the quiet moments 😄
Let me know if this is something that seems suitable as a fix.
