### ISSUE TITLE
Crash: `ClassDef` has no attribute `is_abstract`

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/pylint#7742]
### Bug description

Code:
```python
class Foo:
    __init__ = 42


class Bar(Foo):
    def __init__(self):
        pass
```

### Command used

```shell
pylint asd.py
```

### Pylint output

```shell
************* Module asd
asd.py:8:0: C0305: Trailing newlines (trailing-newlines)
asd.py:1:0: C0114: Missing module docstring (missing-module-docstring)
asd.py:1:0: C0115: Missing class docstring (missing-class-docstring)
asd.py:1:0: R0903: Too few public methods (0/2) (too-few-public-methods)
asd.py:5:0: C0115: Missing class docstring (missing-class-docstring)
Exception on node <FunctionDef.__init__ l.6 at 0x102b8b130> in file '/Users/tusharsadhwani/code/marvin-python/asd.py'
Traceback (most recent call last):
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/classes/class_checker.py", line 1169, in visit_functiondef
    self._check_init(node, klass)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/classes/class_checker.py", line 2037, in _check_init
    to_call = _ancestors_to_call(klass_node)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/classes/class_checker.py", line 2236, in _ancestors_to_call
    if init_node.is_abstract():
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 2009, in __getattr__
    return super().__getattr__(name)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/astroid/bases.py", line 134, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'ClassDef' object has no attribute 'is_abstract'
asd.py:1:0: F0002: asd.py: Fatal error while checking 'asd.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/tusharsadhwani/Library/Caches/pylint/pylint-crash-2022-11-10-16-02-44.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

No crash

### Pylint version

```shell
pylint 2.15.5
astroid 2.12.12
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
```

**Comment by tushar-deepsource** [comment]
imo, if it shows up in Pylint, it should stay in Pylint.
It should be closed when pylint makes a release with the new astroid version.
