### ISSUE TITLE
Crash to AstroidError when using an imported class in place of a TypeVar for a generic dataclass

### ISSUE THREAD

**Issue by jphells** [PyCQA/pylint#7768]
### Bug description

I have the following two files in the same directory:

foo.py

```python
from __future__ import annotations
from dataclasses import dataclass
from typing import Generic, TypeVar

from .bar import Bar

_T = TypeVar("_T")

class Foo(Generic[_T]): ...

@dataclass
class Baz(Foo[Bar]): ...
```

bar.py
```python
class Bar: ...
```

When linting `foo.py`, pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "c:\Users\user\example\venv\lib\site-packages\pylint\lint\pylinter.py", line 769, in _lint_file
    check_astroid_module(module)
  File "c:\Users\user\example\venv\lib\site-packages\pylint\lint\pylinter.py", line 1029, in check_astroid_module
    retval = self._check_astroid_module(
  File "c:\Users\user\example\venv\lib\site-packages\pylint\lint\pylinter.py", line 1075, in _check_astroid_module
    raw_checker.process_module(node)
  File "c:\Users\user\example\venv\lib\site-packages\pylint\checkers\similar.py", line 839, in process_module
    self.append_stream(self.linter.current_name, stream, node.file_encoding)  # type: ignore[arg-type]
  File "c:\Users\user\example\venv\lib\site-packages\pylint\checkers\similar.py", line 378, in append_stream
    LineSet(
  File "c:\Users\user\example\venv\lib\site-packages\pylint\checkers\similar.py", line 683, in __init__
    self._stripped_lines = stripped_lines(
  File "c:\Users\user\example\venv\lib\site-packages\pylint\checkers\similar.py", line 579, in stripped_lines
    tree = astroid.parse("".join(lines))
  File "c:\Users\user\example\venv\lib\site-packages\astroid\builder.py", line 282, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\builder.py", line 141, in string_build
    return self._post_build(module, builder, "utf-8")
  File "c:\Users\user\example\venv\lib\site-packages\astroid\builder.py", line 161, in _post_build
    module = self._manager.visit_transforms(module)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\manager.py", line 94, in visit_transforms
    return self._transform.visit(node)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 89, in visit
    return self._visit(module)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 54, in _visit
    visited = self._visit_generic(value)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 61, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 61, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 67, in _visit_generic
    return self._visit(node)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 57, in _visit
    return self._transform(node)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\transforms.py", line 39, in _transform
    ret = transform_func(node)
  File "c:\Users\user\example\venv\lib\site-packages\astroid\brain\brain_dataclasses.py", line 97, in dataclass_transform
    init_str = _generate_dataclass_init(
  File "c:\Users\user\example\venv\lib\site-packages\astroid\brain\brain_dataclasses.py", line 235, in _generate_dataclass_init
    base_init: FunctionDef | None = base.locals["__init__"][0]
TypeError: 'Uninferable' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\user\example\venv\lib\site-packages\pylint\lint\pylinter.py", line 734, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "c:\Users\user\example\venv\lib\site-packages\pylint\lint\pylinter.py", line 771, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

Playing with the code, I noticed pylint does not crash like this if:
- foo.py:Baz is not a dataclass OR,
- bar.py:Bar is moved to foo.py instead of importing

### Command used

```shell
pylint foo.py
```

### Pylint output

```shell
foo.py:1:0: F0002: foo.py: Fatal error while checking 'foo.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\user\AppData\Local\pylint\pylint\Cache\pylint-crash-2022-11-14-14-05-33.txt'. (astroid-error)
```

### Expected behavior

Pylint does not crash and shows its linting messages (if any) for foo.py

### Pylint version

```shell
pylint 2.15.0
astroid 2.12.6
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
```

### OS / Environment

Windows 11

**Comment by DanielNoord** [comment]
I can no longer reproduce this with the latest version. Closing until we get confirmation that this is still reproducible on later versions.
