### ISSUE TITLE
ImportError for implicit namespace (pyproject, setuptools)

### ISSUE THREAD

**Issue by b-kamphorst** [PyCQA/pylint#7875]
### Bug description

Hi all,

I try to run `pylint` on an implicit namespace that is build from a `pyproject.toml` with `setuptools` as backend. However, `pylint` is not able to deduce the namespace and throws an `ImportError`.

Project lay-out:
```
|-- pyproject.toml
|-- src
     |-- foo
     |-- bar
          |-- __init__.py
          |-- fun.py
```

`pyproject.toml`
```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "foo.bar"
version = "0.0.1"
```

`fun.py`
```py
def foo() -> None:
    pass
```

### Command used

```shell
pylint foo.bar
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/home/bart/git/pylint-tester/.venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/__init__.py", line 35, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/run.py", line 207, in __init__
    linter.check(args)
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 696, in check
    ast_per_fileitem = self._get_asts(fileitems, data)
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 707, in _get_asts
    for fileitem in fileitems:
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 874, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules).values():
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 881, in _expand_files
    result, errors = expand_modules(
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/expand_modules.py", line 149, in expand_modules
    modpath = _modpath_from_file(
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/pylint/lint/expand_modules.py", line 21, in _modpath_from_file
    return modutils.modpath_from_file_with_callback(
  File "/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/astroid/modutils.py", line 303, in modpath_from_file_with_callback
    raise ImportError(
ImportError: Unable to find module for /home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages/foo/bar/fun.py in /home/bart/git/pylint-tester, 
/home/bart/git/mpclab/pylint-tester/.venv/bin, 
/home/bart/.pyenv/versions/3.10.8/lib/python310.zip, 
/home/bart/.pyenv/versions/3.10.8/lib/python3.10, 
/home/bart/.pyenv/versions/3.10.8/lib/python3.10/lib-dynload, 
/home/bart/git/pylint-tester/.venv/lib/python3.10/site-packages
```

### Expected behavior

`pylint` analysis of the module, similar to the following output (achieved by putting `fun.py` in `foo` and updating the package name):

```bash
************* Module foo
.venv/lib/python3.10/site-packages/foo/__init__.py:1:0: C0104: Disallowed name "foo" (disallowed-name)
************* Module foo.fun
.venv/lib/python3.10/site-packages/foo/fun.py:1:0: C0114: Missing module docstring (missing-module-docstring)
.venv/lib/python3.10/site-packages/foo/fun.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
.venv/lib/python3.10/site-packages/foo/fun.py:1:0: C0104: Disallowed name "foo" (disallowed-name)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Pylint version

```shell
pylint 2.15.7
astroid 2.12.13
Python 3.10.8 (main, Nov 30 2022, 11:20:47) [GCC 9.4.0]
```

### OS / Environment

Ubuntu 20.04.5 LTS (in WSL 2 on Windows 10)

**Comment by b-kamphorst** [comment]
I expect that the issue is somewhere in `astroid`, specifically in `astroid.interpreter._import.util.py:is_namespace`, but that code is quite involved. Looking forward to your thoughts!

**Comment by b-kamphorst** [comment]
Hi all (special to @jacobtylerwalls)! I know these are busy times, but I feel that this is quite a fundamental issue. I may be making a mistake -- I hope so and please do help me to sort it out! If not, however, you may want to triage this and get a discussion going.

I appreciate your efforts :)

**Comment by DanielNoord** [comment]
Which version of setuptools are you using?

**Comment by b-kamphorst** [comment]
I've tested this setup (and repreduced the issue) with versions `63.2.0`, `65.5.1`, and `65.6.3` (latest). I just ensured that `pip` is also the latest version (`22.3.1`).

**Comment by DanielNoord** [comment]
Could you try with `setuptools` 60? We have seen issues with recent versions of `setuptools`.

**Comment by b-kamphorst** [comment]
I got the same results with versions `54.2.0`, `59.8.0`, `60.0.0` and `60.10.0`.

**Comment by DanielNoord** [comment]
I really want to look into this, but haven't found the time. Sorry! Trying to do so in the coming weeks.

**Comment by b-kamphorst** [comment]
@DanielNoord thank you for the heads up -- I appreciate the notification.

I've tried some minor things that did not help (but might we worth noting). 
- [observation] In contrast to my previous configuration with `setup.py`, this configuration does not create `namespace_packages.txt` in the bdist / sdist. 
- [experiment] Adding a section `[tool.setuptools]` and defining `namespace_packages = ["foo"]` did create the `namespace_packages.txt`, but it did not seem to matter.
- [experiment] Finally, I duplicated the project and updated the configuration so that it provides a package `foo.bar_2`. Installing that package additionally (so that the `foo` namespace is populated by multiple projects) did not seem to matter (as is expected).

So.. no luck thus far. I look forward to your analysis. Until that time though, let's enjoy the last bit of 2022 and we'll be in touch next year!

**Comment by jacobtylerwalls** [comment]
Thanks for your patience. I just found some time to have a look. This looks like a consequence of PyCQA/astroid#1756.

The following two diffs (one for astroid, one for pylint) is horribly unreadable in its current state, but it's a quick hack to pass your test case. The trouble is we have two different `is_namespace` utilities floating around.

```diff
diff --git a/astroid/interpreter/_import/util.py b/astroid/interpreter/_import/util.py
index 6cc15b5d..08022645 100644
--- a/astroid/interpreter/_import/util.py
+++ b/astroid/interpreter/_import/util.py
@@ -98,7 +98,7 @@ def is_namespace(modname: str) -> bool:
                 any(location.startswith(lib_dir) for lib_dir in STD_AND_EXT_LIB_DIRS)
                 for location in found_spec.submodule_search_locations
             ):
-                return False
+                return 0  # make this a sentinel...
             last_submodule_search_locations = found_spec.submodule_search_locations
 
     return (
```

```diff
diff --git a/pylint/lint/expand_modules.py b/pylint/lint/expand_modules.py
index e43208dea..fe8c3e59e 100644
--- a/pylint/lint/expand_modules.py
+++ b/pylint/lint/expand_modules.py
@@ -10,6 +10,7 @@ from collections.abc import Sequence
 from re import Pattern
 
 from astroid import modutils
+from astroid.interpreter._import.util import is_namespace as other_namespace_test
 
 from pylint.typing import ErrorDescriptionDict, ModuleDescriptionDict
 
@@ -116,8 +117,10 @@ def expand_modules(
             # Might not be acceptable, don't crash.
             is_namespace = False
             is_directory = os.path.isdir(something)
+            other_is_namespace = False
         else:
             is_namespace = modutils.is_namespace(spec)
+            other_is_namespace = is_namespace or other_namespace_test(something) == 0
             is_directory = modutils.is_directory(spec)
         if not is_namespace:
             if filepath in result:
@@ -147,7 +150,7 @@ def expand_modules(
                     continue
 
                 modpath = _modpath_from_file(
-                    subfilepath, is_namespace, path=additional_search_path
+                    subfilepath, other_is_namespace, path=additional_search_path
                 )
                 submodname = ".".join(modpath)
                 # Preserve arg flag if module is also explicitly given.
```
***
Would I be able to interest you in putting together a pair of PRs that improves these diffs (and adds a test?)
***
For now, as a workaround, you could lint `src.foo.bar`, but that may not be acceptable for the same reasons as the OP in #7365.

**Comment by jacobtylerwalls** [comment]
Actually, looking closer, all the diff really does is revert PyCQA/astroid#1756. I'm not yet sure of the correct behavior.

**Comment by b-kamphorst** [comment]
@jacobtylerwalls thank you for joining the discussion and providing suggestions!

I'm somewhat surprised by [the comment](https://github.com/jacobtylerwalls/astroid/blob/e84f61311a9a99d487637e53c2a56e06e4823cee/astroid/interpreter/_import/util.py#L95)

> But immediately return False if we can detect we are in stdlib or external lib (e.g site-packages)

that was introduced in https://github.com/PyCQA/astroid/pull/1756. In both my local development environment (using `venv` as displayed in OP) as well as in the gitlab ci (path `/usr/local/lib/python3.10/site-packages/foo/...`), `site-packages` is part of the path. Actually my main reason for migrating to a `src`-layout is to get rid of the confusion between source files and the installed version of a package (I regularly have `mypy` issues in a `flat`-layout). But I then might just be confused as I am new to introspection logic.

**Comment by jacobtylerwalls** [comment]
You have a nice test case here. Something should be done to improve the situation. Unfortunately this has been missing from pylint for forever (doesn't look to be recently caused in astroid*). Some of the variations on the failure were also referenced in #1361 before we closed it.

**1.** `pylint foo`: silent failure

**2.** `pylint foo.bar`: uncaught ImportError

**3.** `pylint foo.bar.fun`: resolves to site-packages, violating the principle of #7365, if that's even the correct behavior

(* in astroid 2.12.4, **2.** briefly behaved like **3.**, but we got several bug reports and reverted it in PyCQA/astroid#1756 in 2.12.5) 

Workaround is to use `pylint src.foo.bar` like flake8. Sorry we don't have a solution at the moment!

**Comment by b-kamphorst** [comment]
@jacobtylerwalls could you point me to some of these issues to better understand the issue with resolving to site-packages? I don't quite understand what happens in #7365 -- that case seems weird also just because the pylint output states the module prepended with `site-packages`. I wonder, if both cases have their uses, whether it might be nice to allow both `pytest foo` and `pytest .foo` or something to indicate `site-packages` versus CWD should be leading (absolute vs relative import), or have some kind of flag to allow / prevent either from being used.

I only specified my use case partially. Ultimately, I want to be able to install several namespace packages, all of them part of the same namespace, and then run pylint on the package as a whole (so not just `foo.bar`, but also `foo.bar_2`, `foo.bar_3`, etc. I don't think a `pylint src.foo.bar`-like solution can do this for me?

**Comment by jacobtylerwalls** [comment]
Sure thing.

> (* in astroid 2.12.0, 2. briefly behaved like 3., but we got several bug reports and reverted it in https://github.com/PyCQA/astroid/pull/1756 in 2.12.5)

In addition to #7365 we also got a bug report after the fact in https://github.com/PyCQA/pylint-plugin-utils/issues/27#issuecomment-1231517114.

I agree that the handling of namespace packages needs improving. The code paths through this part of astroid and pylint are terribly tangled. We would just like to find incremental improvements that don't create breaking changes (unless we do  really need to advertise breaking changes in a 3.0 version.) Any analysis or draft patches are much appreciated.

**Comment by hmc-cs-mdrissi** [comment]
I'd expect a solution to this [issue](https://github.com/PyCQA/pylint/issues/5226) to likely give a way of handling this one as well. I did make a pr for it in past and mostly stalled out on writing tests for it/whether that option was worth it. Maybe now I should revive that pr as still feels like any solution that involves guessing sys.path/reverse engineering import system is likely to be tricky. The original pr was this [one](https://github.com/PyCQA/pylint/pull/5235).

Most of complexity/bugs with namespace packages comes from pylint trying to be smart and guessing what to add to sys.path if packages are uninstalled. This smartness is convenient for simple projects and allowing users to not need to install there own code, but becomes tricky for more complex packages (mostly namespace weirdness). If pylint expected (with an opt-in flag) that all packages must be installed already and doesn't alter sys.path at all, the complexity disappears.
