### ISSUE TITLE
ModuleNotFoundError: No module named 'wrapt' 

### ISSUE THREAD

**Issue by joegasewicz** [PyCQA/pylint#7889]
### Bug description

Installing the latest version - `2.15.7` via github action's CI here:

https://github.com/joegasewicz/bobtail/actions/runs/3602033332/jobs/6068561757

### Configuration

```ini
Python 3.11
```

### Command used

```shell
pipenv run pylint bobtail
```

### Pylint output

```shell
Run # stop the build if there are Python syntax errors or undefined names
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/__init__.py", line 32, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/lint/__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/config/__init__.py", line 25, in <module>
    from pylint.config.arguments_provider import UnsupportedAction
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/config/arguments_provider.py", line 15, in <module>
    from pylint.config.arguments_manager import _ArgumentsManager
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/config/arguments_manager.py", line 25, in <module>
    from pylint import utils
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/utils/__init__.py", line 9, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 13, in <module>
    from astroid import nodes
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/astroid/__init__.py", line 42, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/astroid/nodes/__init__.py", line 17, in <module>
    from astroid.nodes._base_nodes import Statement
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/astroid/nodes/_base_nodes.py", line 17, in <module>
    from astroid import decorators
  File "/home/runner/.local/share/virtualenvs/bobtail-Cbs4m0rL/lib/python3.11/site-packages/astroid/decorators.py", line 16, in <module>
    import wrapt
ModuleNotFoundError: No module named 'wrapt'
Error: Process completed with exit code 1.
```

### Expected behavior

Should be working

### Pylint version

```shell
2.15.7
```

### OS / Environment

ubuntu-latest

**Comment by joegasewicz** [comment]
regressed to version `2.15.6` and is working

**Comment by DanielNoord** [comment]
This feels like a `pipenv` issue as I don't have this issue in my own new `venvs`. Are you sure `pipenv` is working correctly?

**Comment by joegasewicz** [comment]
> This feels like a `pipenv` issue as I don't have this issue in my own new `venvs`. Are you sure `pipenv` is working correctly?

I can run the previous version of pylint in github action's CI successfully but when i run the latest  version of pylint in the CI it fails & this is with the same version of pipenv...

**Comment by DanielNoord** [comment]
I have no idea how `pipenv` works, but could it be that your `Pipfile.lock` is out of date?

**Comment by joegasewicz** [comment]
> I have no idea how `pipenv` works, but could it be that your `Pipfile.lock` is out of date?

That's a good point, sounds valid. I'll check this out, thank you

**Comment by clavedeluna** [comment]
@joegasewicz any updates here? If it worked for you we could close this issue :)

**Comment by joegasewicz** [comment]
I deleted my Pipefile.lock file , recreated a new pipenv environment & reinstalled the dependencies & all
works locally. For some strange reason though it still fails in github CI with Python 3.10 but not Python 3.11... here: https://github.com/joegasewicz/bobtail/actions/runs/3648598891/jobs/6162206355. 

I will close this issue now as I'm happy to role back to a version that works in github CI & seems to be an issue with an image that github's CI is using. Thanks
