### ISSUE TITLE
Maximum recursion depth exceeded in comparison when importing from panda3d

### ISSUE THREAD

**Issue by fraca7** [PyCQA/pylint#7894]
### Bug description

When parsing the following file (pandatest.py):

```python
#!/usr/bin/env python3

from panda3d import core

```

pylint crashed with a ``AstroidError``

### Configuration

```ini
[MAIN]
extension-pkg-whitelist=panda3d
disable=C0114
```

### Command used

```shell
pylint pandatest.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    check_astroid_module(module)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1060, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1110, in _check_astroid_module
    walker.walk(node)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/checkers/variables.py", line 1731, in visit_importfrom
    self._check_module_attrs(node, module, name.split("."))
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/checkers/variables.py", line 2695, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 409, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 522, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/manager.py", line 184, in ast_from_module_name
    return self.ast_from_module(module, modname)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/manager.py", line 286, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/builder.py", line 92, in module_build
    node = self.inspect_build(module, modname=modname, path=path)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/raw_building.py", line 373, in inspect_build
    self.object_build(node, module)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/raw_building.py", line 416, in object_build
    self.object_build(class_node, member)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/raw_building.py", line 424, in object_build
    attach_const_node(node, name, member)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/raw_building.py", line 82, in attach_const_node
    _attach_local_node(node, nodes.const_factory(value), name)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 5531, in const_factory
    instance.postinit(_create_dict_items(value, instance))
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 5505, in _create_dict_items
    value_node = const_factory(value)

# [snip]

  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 5531, in const_factory
    instance.postinit(_create_dict_items(value, instance))
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 5503, in _create_dict_items
    key_node = const_factory(key)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 5525, in const_factory
    if issubclass(initializer_cls, (List, Set, Tuple)):
  File "/usr/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 755, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/jerome/dev/woodwork2/venv/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 792, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```


### Expected behavior

No crash.

### Pylint version

```shell
pylint 2.15.7
astroid 2.12.13
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
```

### OS / Environment

Ubuntu 20.04.5 LTS

### Additional dependencies

astroid==2.12.13
dill==0.3.6
isort==5.10.1
lazy-object-proxy==1.8.0
mccabe==0.7.0
panda3d==1.10.12
platformdirs==2.5.4
pylint==2.15.7
tomli==2.0.1
tomlkit==0.11.6
typing-extensions==4.4.0
wrapt==1.14.1

**Comment by sam-s** [comment]
just got 
```python
Traceback (most recent call last):
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/checkers/imports.py", line 1012, in _get_imported_module
    return importnode.do_import_module(modname)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/_base_nodes.py", line 168, in do_import_module
    return mymodule.import_module(
           ~~~~~~~~~~~~~~~~~~~~~~^
        modname,
        ^^^^^^^^
    ...<2 lines>...
        use_cache=use_cache,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 462, in import_module
    return AstroidManager().ast_from_module_name(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        absmodname, use_cache=use_cache
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/manager.py", line 276, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/manager.py", line 166, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/builder.py", line 166, in _post_build
    self.add_from_names_to_locals(from_node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/builder.py", line 225, in add_from_names_to_locals
    imported = node.do_import_module()
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/_base_nodes.py", line 168, in do_import_module
    return mymodule.import_module(
           ~~~~~~~~~~~~~~~~~~~~~~^
        modname,
        ^^^^^^^^
    ...<2 lines>...
        use_cache=use_cache,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 462, in import_module
    return AstroidManager().ast_from_module_name(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        absmodname, use_cache=use_cache
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/manager.py", line 251, in ast_from_module_name
    return self.ast_from_module(named_module, modname)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/manager.py", line 356, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/builder.py", line 101, in module_build
    node = self.inspect_build(module, modname=modname, path=path)
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 467, in inspect_build
    self.object_build(node, module)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 527, in object_build
    self.object_build(module, member)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 527, in object_build
    self.object_build(module, member)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 527, in object_build
    self.object_build(module, member)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 518, in object_build
    attach_const_node(node, name, member)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/raw_building.py", line 77, in attach_const_node
    _attach_local_node(node, nodes.const_factory(value), name)
                             ~~~~~~~~~~~~~~~~~~~^^^^^^^
<snip>
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 5550, in const_factory
    instance.postinit(_create_dict_items(value, instance))
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 5507, in _create_dict_items
    value_node = const_factory(value)
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 5550, in const_factory
    instance.postinit(_create_dict_items(value, instance))
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 5505, in _create_dict_items
    key_node = const_factory(key)
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 5552, in const_factory
    return Const(value)
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 2070, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        lineno=lineno,
        ^^^^^^^^^^^^^^
    ...<3 lines>...
        parent=parent,
        ^^^^^^^^^^^^^^
    )
    ^
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1020, in check_astroid_module
    retval = self._check_astroid_module(
        ast_node, walker, rawcheckers, tokencheckers
    )
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1072, in _check_astroid_module
    walker.walk(node)
    ~~~~~~~~~~~^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    self.walk(child)
    ~~~~~~~~~^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 87, in walk
    callback(astroid)
    ~~~~~~~~^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/checkers/imports.py", line 540, in visit_import
    imported_module = self._get_imported_module(node, name)
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/checkers/imports.py", line 1037, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sds/.virtualenvs/myself/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

```
pylint 3.3.8
astroid 3.3.11
Python 3.13.3 (main, Aug 14 2025, 11:53:40) [GCC 14.2.0]
```
