### ISSUE TITLE
Crash in R1736

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/pylint#7900]
### Bug description

```python
for i, el in enumerate(l, start=1 + 1):
    ...
```

### Command used

```shell
pylint asd.py --disable=all --enable=R1736
```

### Pylint output

```shell
pylint asd.py --disable=all --enable=R1736
Exception on node <For l.2 at 0x1027e73a0> in file '/Users/tusharsadhwani/code/marvin-python/asd.py'
Traceback (most recent call last):
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 682, in visit_for
    self._check_unnecessary_list_index_lookup(node)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2118, in _check_unnecessary_list_index_lookup
    has_start_arg, confidence = self._enumerate_with_start(node)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2243, in _enumerate_with_start
    start_val, confidence = self._get_start_value(keyword.value)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2260, in _get_start_value
    start_val = node.value
AttributeError: 'BinOp' object has no attribute 'value'

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

### Expected behavior

No crash

### Pylint version

```shell
pylint 2.15.7
astroid 2.12.13
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
```

**Comment by tushar-deepsource** [comment]
Fixed by https://github.com/PyCQA/pylint/pull/7824

**Comment by Pierre-Sassoulas** [comment]
Not released in a patch version because it's too hard to cherry-pick.

**Comment by tushar-deepsource** [comment]
@Pierre-Sassoulas so will it come out in 2.16.0?

**Comment by Pierre-Sassoulas** [comment]
Yes, unless someone manage to backport https://github.com/PyCQA/pylint/pull/7824 on maintenance/2.15.x.
