### ISSUE TITLE
error while installing pylint 2.11.1 

### ISSUE THREAD

**Issue by tjay27** [PyCQA/pylint#7999]
### Bug description

on doing pip install gives an error in a subprocess

pip version = 21.1.1
python version = 3.8.15

### Command used

```shell
pip install pylint==2.11.1
```

### Pylint output

```shell
Collecting pylint==2.11.1
  Using cached pylint-2.11.1-py3-none-any.whl (392 kB)
Collecting mccabe<0.7,>=0.6
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: typing-extensions>=3.10.0 in ./.direnv/python-3.8.15/lib/python3.8/site-packages (from pylint==2.11.1) (4.0.1)
Collecting platformdirs>=2.2.0
  Using cached platformdirs-2.6.0-py3-none-any.whl (14 kB)
Collecting toml>=0.7.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting astroid<2.9,>=2.8.0
  Using cached astroid-2.8.6-py3-none-any.whl (248 kB)
Requirement already satisfied: isort<6,>=4.2.5 in ./.direnv/python-3.8.15/lib/python3.8/site-packages (from pylint==2.11.1) (5.10.1)
Requirement already satisfied: setuptools>=20.0 in ./.direnv/python-3.8.15/lib/python3.8/site-packages (from astroid<2.9,>=2.8.0->pylint==2.11.1) (65.6.3)
Collecting wrapt<1.14,>=1.11
  Using cached wrapt-1.13.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (84 kB)
Collecting lazy-object-proxy>=1.4.0
  Using cached lazy-object-proxy-1.8.0.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info
      writing /tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/SOURCES.txt'
      listing git files failed - pretending there aren't any
      reading manifest file '/tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      adding license file 'AUTHORS.rst'
      writing manifest file '/tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-pdh3rmz6/lazy_object_proxy-1.8.0.dist-info'
      Traceback (most recent call last):
        File "/home/tjay27/oppia/oppia/.direnv/python-3.8.15/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/tjay27/oppia/oppia/.direnv/python-3.8.15/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/tjay27/oppia/oppia/.direnv/python-3.8.15/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 72, in <module>
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 953, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/home/tjay27/.pyenv/versions/3.8.15/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 843, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-4fviygy2/overlay/lib/python3.8/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/home/tjay27/.pyenv/versions/3.8.15/lib/python3.8/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
```


### Expected behavior

successful installation of pylint

### Pylint version

```shell
pylint 2.11.1
```

### OS / Environment

Ubuntu 20.04 on WSL2

**Comment by DanielNoord** [comment]
This is an issue with `lazy-object-proxy`. However, this version of `pylint` is very out of date and no longer supported. Sadly, we can't be of much help here and we suggest updating to a newer version.
