### ISSUE TITLE
Pyreverse cannot handle unpacking attributes in the __init__() method of a class

### ISSUE THREAD

**Issue by JukMR** [PyCQA/pylint#8047]
### Bug description

Pyreverse crashes when doing unpacking of class attributes inside a \_\_init\_\_() method. Here is a simple example to reproduce the error:

Script.py

```python

class GoodClass():
    """
    This way works
    """

    def __init__(self) -> None:
        result = (1, 'a')
        self.number = result[0]
        self.letter = result[1]


class BadClass():
    """
    This way doesn't work
    """

    def __init__(self) -> None:
        self.number, self.letter = (2, 'b')


def main():

    good_class = GoodClass()
    print(good_class.number, good_class.letter)

    bad_class = BadClass()
    print(bad_class.number, bad_class.letter)


if __name__ == "__main__":
    main()
```

When runnning pyreverse it crashes if BadClass is not commented.  

### Command used

```shell
pyreverse script.py
```

### Pylint output

```shell
➜ pyreverse script.py
parsing script.py...
Traceback (most recent call last):
  File "/home/user/.local/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/user/.local/lib/python3.10/site-packages/pylint/__init__.py", line 74, in run_pyreverse
    PyreverseRun(argv or sys.argv[1:])
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 228, in __init__
    sys.exit(self.run(args))
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 243, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/diadefslib.py", line 227, in get_diadefs
    diagrams = DefaultDiadefGenerator(linker, self).visit(project)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/utils.py", line 165, in visit
    self.visit(local_node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/utils.py", line 165, in visit
    self.visit(local_node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/utils.py", line 162, in visit
    methods[0](node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/diadefslib.py", line 171, in visit_classdef
    self.extract_classes(node, anc_level, association_level)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/diadefslib.py", line 113, in extract_classes
    self.add_class(klass_node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/diadefslib.py", line 77, in add_class
    self.linker.visit(node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/utils.py", line 162, in visit
    methods[0](node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/inspector.py", line 195, in visit_classdef
    self.associations_handler.handle(assignattr, node)
  File "/home/user/.local/lib/python3.10/site-packages/pylint/pyreverse/inspector.py", line 368, in handle
    if isinstance(node.parent.value, astroid.node_classes.Name):
  File "/home/user/.local/lib/python3.10/site-packages/astroid/bases.py", line 134, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'ClassDef' object has no attribute 'value'. Did you mean: 'values'?
```

### Expected behavior

Pyreverse shouldn't crash.

### Pylint version

```shell
pylint 2.16.0-dev
astroid 2.12.13
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
```

### OS / Environment

**OS**: Manjaro Linux x86_64 
**Kernel**:  Linux 5.15.85-1-MANJARO
**Terminal**: kitty
**Shell**: zsh 5.9

**Comment by JukMR** [comment]
CC: @dgutson @qequ

**Comment by DudeNr33** [comment]
Could you try updating your main branch? I submitted a PR for this a few days ago that was already merged. If this bug still exists I have to dig a bit deeper.

**Comment by JukMR** [comment]
Yes, with the last version of the main branch now it's working. I was using the main version from January 3rd and forgot to pull the main branch again. 
Closing this now, thanks for the help and sorry for the noise!
