### ISSUE TITLE
Inference crash: `Slice has no attribute 'qname'`

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/pylint#8067]
### Bug description

```python
x = slice(42)
x()
```

### Command used

```shell
pylint asd.py
```

### Pylint output

```shell
************* Module asd
asd.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Exception on node <Call l.2 at 0x1040c31f0> in file '/private/tmp/asd.py'
Traceback (most recent call last):
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/method_args.py", line 72, in visit_call
    and inferred.qname() in self.linter.config.timeout_methods
AttributeError: 'Slice' object has no attribute 'qname'
asd.py:1:0: F0002: asd.py: Fatal error while checking 'asd.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/tusharsadhwani/Library/Caches/pylint/pylint-crash-2023-01-17-14-57-43.txt'. (astroid-error)
```

### Expected behavior

No crash.

### Pylint version

```shell
pylint 2.15.10
astroid 2.13.2
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
```

### OS / Environment

MacOS Monterey

**Comment by tushar-deepsource** [comment]
Also reproduced it on master.

**Comment by tushar-deepsource** [comment]
Also, weirdly enough a similar crash also happens in `RefactoringChecker` if I tweak the code a little bit:

### Code
```python
class Foo:
    def __init__(self, foo=slice(42)):
        self.foo = foo


def bar():
    i = Foo()
    i.foo()
    return 100
```

### Output

```console
$ pylint /tmp/asd.py
************* Module asd
/tmp/asd.py:1:0: C0114: Missing module docstring (missing-module-docstring)
/tmp/asd.py:1:0: C0115: Missing class docstring (missing-class-docstring)
/tmp/asd.py:3:8: C0104: Disallowed name "foo" (disallowed-name)
/tmp/asd.py:2:23: C0104: Disallowed name "foo" (disallowed-name)
/tmp/asd.py:1:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/tmp/asd.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
/tmp/asd.py:6:0: C0104: Disallowed name "bar" (disallowed-name)
Exception on node <FunctionDef.bar l.6 at 0x1025149a0> in file '/tmp/asd.py'
Traceback (most recent call last):
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 95, in walk
    callback(astroid)
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 977, in leave_functiondef
    self._check_consistent_returns(node)
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1859, in _check_consistent_returns
    ) and self._is_node_return_ended(node):
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1971, in _is_node_return_ended
    return any(self._is_node_return_ended(_child) for _child in node.get_children())
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1971, in <genexpr>
    return any(self._is_node_return_ended(_child) for _child in node.get_children())
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1971, in _is_node_return_ended
    return any(self._is_node_return_ended(_child) for _child in node.get_children())
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1971, in <genexpr>
    return any(self._is_node_return_ended(_child) for _child in node.get_children())
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1941, in _is_node_return_ended
    if self._is_function_def_never_returning(funcdef_node):
  File "/private/tmp/venv3/lib/python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2000, in _is_function_def_never_returning
    return node.qname() in self._never_returning_functions
AttributeError: 'Slice' object has no attribute 'qname'
/tmp/asd.py:1:0: F0002: /tmp/asd.py: Fatal error while checking '/tmp/asd.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/tusharsadhwani/Library/Caches/pylint/pylint-crash-2023-01-17-15-02-58.txt'. (astroid-error)
```

**Comment by jacobtylerwalls** [comment]
I feel like we need a `topic-qname` label 🤣
