### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'statement'

### ISSUE THREAD

**Issue by PandaWill** [PyCQA/pylint#814]
We have some code in our codebase which crashes Pylint with an Attribute Error.

Versions in use:
pylint 1.5.4, 
astroid 1.4.4
Python 2.7.6 

Here is the minimum code to cause the problem:
```
def no_op(*args):
	pass

def foo(*args):
	def inner(*more_args):
		all_args = args + more_args
		return no_op(*all_args)
	return inner
```
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python2.7/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1313, in __init__
    linter.check(args)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 945, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/typecheck.py", line 509, in visit_call
    no_context_variadic = self._no_context_variadic(node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/checkers/typecheck.py", line 494, in _no_context_variadic
    if not length and isinstance(inferred.statement(), astroid.FunctionDef):
  File "/usr/local/lib/python2.7/dist-packages/astroid/bases.py", line 433, in statement
    return self.parent.statement()
AttributeError: 'NoneType' object has no attribute 'statement'

```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by PCManticore** [comment]
This is fixed in astroid, in all branches (https://github.com/PyCQA/astroid/commit/ce80c835a492ccdf05b9786f0e0960327a51826e 1.4.0 for instance). I'll try to do a new bug fix release in the next couple of days.
