### ISSUE TITLE
Specifying confidence level on command line doesn't work at all

### ISSUE THREAD

**Issue by anlutro** [PyCQA/pylint#819]
Using Python 3.4 in a virtualenv with the latest version of pylint (1.5.4 at the time of writing, astroid 1.4.4):

```
% pylint --confidence=HIGH,INFERENCE,INFERENCE_FAILURE
Traceback (most recent call last):
  File "/home/andreas/dev/prove/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/andreas/dev/prove/lib/python3.4/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/home/andreas/dev/prove/lib/python3.4/site-packages/pylint/lint.py", line 1288, in __init__
    args = linter.load_command_line_configuration(args)
  File "/home/andreas/dev/prove/lib/python3.4/site-packages/pylint/config.py", line 664, in load_command_line_configuration
    (options, args) = self.cmdline_parser.parse_args(args=args)
  File "/usr/lib/python3.4/optparse.py", line 1386, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python3.4/optparse.py", line 1426, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.4/optparse.py", line 1500, in _process_long_opt
    option.process(opt, value, values, self)
  File "/home/andreas/dev/prove/lib/python3.4/site-packages/pylint/config.py", line 292, in process
    value = self.convert_value(opt, value)
  File "/usr/lib/python3.4/optparse.py", line 770, in convert_value
    return self.check_value(opt, value)
  File "/usr/lib/python3.4/optparse.py", line 765, in check_value
    return checker(self, opt, value)
  File "/home/andreas/dev/prove/lib/python3.4/site-packages/pylint/config.py", line 149, in _multiple_choice_validator
    choices = optdict['choices']
TypeError: 'Option' object is not subscriptable
```

I've been able to "fix" this by locking pylint at v1.4.4 and astroid at 1.3.8, but that's obviously not ideal.

**Comment by ikanobori** [comment]
Confirming this doesn't work in 2.7.11 either:

`λ aether test → pylint --confidence=HIGH
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/home/ikanobori/source/test/env/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/home/ikanobori/source/test/env/lib/python2.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/home/ikanobori/source/test/env/lib/python2.7/site-packages/pylint/lint.py", line 1288, in __init__
    args = linter.load_command_line_configuration(args)
  File "/usr/home/ikanobori/source/test/env/lib/python2.7/site-packages/pylint/config.py", line 655, in load_command_line_configuration
    (options, args) = self.cmdline_parser.parse_args(args=args)
  File "/usr/local/lib/python2.7/optparse.py", line 1400, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/local/lib/python2.7/optparse.py", line 1440, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/local/lib/python2.7/optparse.py", line 1515, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/home/ikanobori/source/test/env/lib/python2.7/site-packages/pylint/config.py", line 283, in process
    value = self.convert_value(opt, value)
  File "/usr/local/lib/python2.7/optparse.py", line 775, in convert_value
    return self.check_value(opt, value)
  File "/usr/local/lib/python2.7/optparse.py", line 770, in check_value
    return checker(self, opt, value)
  File "/usr/home/ikanobori/source/test/env/lib/python2.7/site-packages/pylint/config.py", line 145, in _multiple_choice_validator
    choices = optdict['choices']
AttributeError: Option instance has no attribute '__getitem__'
λ aether test → python -V
Python 2.7.11
`

**Comment by PCManticore** [comment]
Yeah, the current master is the next Pylint 2.0, which for now depends on master@astroid (this will change again when astroid 2.0 gets stable). We won't develop another minor release (1.6.0 for instance), jumping straight from 1.5.X to 2.0, except only minor bug fix releases in 1.5.X branch.

Regarding the actual issue, would you want to send a PR with a fix for 1.5.0 branch? I'm actually thinking on phasing out confidence levels for Pylint 2.0, since they'll get replaced by pattern tiers and builtin management of the confidence, as per discussions from #746.

**Comment by anlutro** [comment]
If you can give some hint as to what the fix might be, I can try making a
pull request. I had a brief look before submitting the issue and couldn't
figure out what the root cause was.

**Comment by ikanobori** [comment]
The root cause seems to be a missing conversion of the Option type. This seems to only go wrong when the option is actually passed into parse_args which hints at the idea that the conversion from Option to dict is not actually being executed by optparse (its conversion isn't registered or such).

A workaround for this would be to implement __getitem__ on the Option value, I tested that against master/1.5.0 on Py2.7 and Py3.4 and it gets rid of the error itself making --confidence usable. That change of course doesn't help with the root cause. 

Since optparse itself is deprecated and PCManticore hints at a full removal of the option in 2.x it might be a good choice 'for now'.

**Comment by PCManticore** [comment]
Closed through https://github.com/PyCQA/pylint/commit/66d104b70b08ae109bc73e98c3dfc3609c5d89a9

**Comment by anlutro** [comment]
Thanks @PCManticore! Are there any plans for a 1.5 release soon?
