### ISSUE TITLE
exception in astroid when using try/except ImportError

### ISSUE THREAD

**Issue by dcbaker** [PyCQA/pylint#849]
pylint: 1.5.4
astroid: 1.5.0-git (7278409ee6e578c1)
python: 3.3.6

The following snippet will produce the error:
```python
try:
    import a_made_up_module
except ImportError:
    pass
```

The traceback:
```txt
Process ChildLinter-2:
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.3.6/lib/python3.3/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/lint.py", line 211, in run
    result = self._run_linter(file_or_module[0])
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/lint.py", line 240, in _run_linter
    linter.check(file_or_module)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/lint.py", line 945, in check_astroid_module
    walker.walk(ast_node)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/checkers/imports.py", line 324, in visit_import
    importedmodnode = self.get_imported_module(node, name)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/pylint/checkers/imports.py", line 503, in get_imported_module
    return importnode.do_import_module(modname)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/astroid/mixins.py", line 129, in do_import_module
    relative_only=level and level >= 1)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/astroid/scoped_nodes.py", line 437, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/astroid/manager.py", line 149, in ast_from_module_name
    raise e
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/astroid/manager.py", line 119, in ast_from_module_name
    filepath, mp_type = self.file_from_module_name(modname, context_file)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/astroid/manager.py", line 192, in file_from_module_name
    value, traceback)
  File "/home/user/.pyenv/versions/piglit-3.3-noaccel/lib/python3.3/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
astroid.exceptions.AstroidImportError: Failed to import module a_made_up_module with error:
No module named a_made_up_module.
```

**Comment by PCManticore** [comment]
Try pairing astroid 1.5.0 with pylint's master, it does not work with pylint 1.5.X.

**Comment by dcbaker** [comment]
It works with pylint from git as well, sorry for the noise.
