### ISSUE TITLE
Unicode BOM in pylintrc causes errors.

### ISSUE THREAD

**Issue by demoneaux** [PyCQA/pylint#864]
PyLint errors when the config file has the Unicode BOM preceding any configuration. Could it be stripped?

```sh
$ pylint ..
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pylint\__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "c:\python27\lib\site-packages\pylint\lint.py", line 1269, in __init__
    linter.read_config_file()
  File "c:\python27\lib\site-packages\pylint\config.py", line 619, in read_config_file
    parser.read([config_file])
  File "c:\python27\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "c:\python27\lib\ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: C:\Users\haxx\Documents\GitHub\vsavevents\.pylintrc, line: 1
'\xff\xfe[\x00M\x00A\x00S\x00T\x00E\x00R\x00]\x00\r\x00\n'
```

**Comment by demoneaux** [comment]
Thanks for the quick fix!
