### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BaseInstance'

### ISSUE THREAD

**Issue by moylop260** [PyCQA/pylint#930]
I don't know if this issue is of astroid or pylint but today I have the following traceback (I don't saw what is the exactly sha with the problem)

```bash
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 75, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
  File "pylint/lint.py", line 1309, in __init__
    linter.check(args)
  File "pylint/lint.py", line 729, in check
    self._do_check(files_or_modules)
  File "pylint/lint.py", line 860, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "pylint/lint.py", line 939, in check_astroid_module
    walker.walk(ast_node)
  File "pylint/utils.py", line 937, in walk
    self.walk(child)
  File "pylint/utils.py", line 937, in walk
    self.walk(child)
  File "pylint/utils.py", line 937, in walk
    self.walk(child)
  File "pylint/utils.py", line 934, in walk
    cb(astroid)
  File "pylint/checkers/typecheck.py", line 984, in visit_for
    self._check_iterable(node.iter)
  File "pylint/checkers/typecheck.py", line 964, in _check_iterable
    if not is_iterable(infered):
  File "pylint/checkers/utils.py", line 690, in is_iterable
    return _supports_protocol(value, _supports_iteration_protocol)
  File "pylint/checkers/utils.py", line 681, in _supports_protocol
    if isinstance(value, astroid.BaseInstance):
AttributeError: 'module' object has no attribute 'BaseInstance'
```

**Comment by moylop260** [comment]
@PCManticore 
Do you make sense?

**Comment by PCManticore** [comment]
I probably don't make sense, but I can't reproduce the issue. You have to install astroid from the master branch for working with Pylint from the master branch. I presume this is not the case in your example.

**Comment by moylop260** [comment]
Ok I got it
Thank you!
