### ISSUE TITLE
hmac imported from cwd

### ISSUE THREAD

**Issue by jwilk** [PyCQA/pylint#959]
### Current behavior

If you use the `-j` option, a module named `hmac` from the current working directory may be imported:

```
$ echo 'raise RuntimeError("BAD PYLINT!")' > hmac.py
$ touch test.py
$ pylint -j2 test.py
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.5/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1316, in __init__
    linter.generate_reports()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1136, in fix_import_path
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 124, in _patch_sysmodules
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 807, in _parallel_check
    for result in self._parallel_task(files_or_modules):
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 763, in _parallel_task
    tasks_queue = manager.Queue()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 628, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 520, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 730, in answer_challenge
    import hmac
  File "/home/jwilk/badpylint/hmac.py", line 1, in <module>
    raise RuntimeError("BAD PYLINT!")
RuntimeError: BAD PYLINT!
```
### Expected behavior

pylint should not let any modules be imported from cwd (unless it was asked to do so).
### pylint --version output

```
No config file found, using default configuration
pylint 1.5.6,
astroid 1.4.6
Python 3.5.2rc1 (default, Jun 13 2016, 09:33:26)
[GCC 5.4.0 20160609]
```

**Comment by PCManticore** [comment]
This is not a problem of pylint. It is triggered in -j mode, because the standard library module ``multiprocessing`` imports hmac itself, which in turn, will point to the local file, instead of the stdlib's module. You can also test this with ``python -c "import hmac"`` and you will get the same result. I can only suggest you to rename it to something that does not shadow a stdlib's module or run pylint on the parent directory instead.

**Comment by jwilk** [comment]
> You can also test this with ``python -c "import hmac"`` and you will get the same result

When you use `-c`, the Python interpreter adds cwd to `sys.path`. This is not the case when you run a Python script. So no, you can't blame the interpreter.

> I can only suggest you to rename it to something that does not shadow a stdlib's module

I want to run pylint against untrusted code, so this is not an option for me.

> or run pylint on the parent directory instead

Actually, chdir'ing to a trusted directory doesn't help:
```
$ cd / && pylint -j2 /home/jwilk/badpylint/test.py
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.5/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1316, in __init__
    linter.generate_reports()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1136, in fix_import_path
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 124, in _patch_sysmodules
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 807, in _parallel_check
    for result in self._parallel_task(files_or_modules):
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 763, in _parallel_task
    tasks_queue = manager.Queue()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 628, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 520, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 730, in answer_challenge
    import hmac
  File "/home/jwilk/badpylint/hmac.py", line 1, in <module>
    raise RuntimeError("BAD PYLINT!")
RuntimeError: BAD PYLINT!
```

The bug title turned out to be inaccurate. Sorry about that.

**Comment by PCManticore** [comment]
Actually even if it is a script, it behaves the same way. Given

```
   $ cat a.py
    import multiprocessing.connection as mc
    mc.answer_challenge(1, 2)
   $ python a.py
    Traceback (most recent call last):
      File "a.py", line 2, in <module>
        mc.answer_challenge(1, 2)
      File "C:\Users\Claudiu\AppData\Local\Programs\Python\Python35-32\lib\multiprocessing\connection.py", line 730, in answer_challenge
        import hmac
      File "D:\Projects\repos\tests\hmac.py", line 1, in <module>
        raise RuntimeError("BAD PYLINT!")
    RuntimeError: BAD PYLINT!

```

I am not sure how pylint can help in this situation, given the fact that even the interpreter has the same issue when you have files named after standard library modules. This can only be handled at your application level, by renaming your files.

**Comment by The-Compiler** [comment]
I first noticed the same, but then I noticed it doesn't happen if `a.py` is in another directory (say, `../a.py`) - so I'm unsure why it'd not happen there but with pylint?

**Comment by jwilk** [comment]
What you're seeing is that Python adds the directory where the script resides to `sys.path`.
In my case the script was in a trusted directory (`/usr/local/bin`), as it should be, so this is red herring.

**Comment by PCManticore** [comment]
@The-Compiler can you give me an example? You tried something as this?

```
    $ mkdir other
    $ echo "1/0" > other/hmac.py
    $ echo "import multiprocessing.connection as mc;mc.answer_challenge(1,2)" > other/a.py
    $ python other/a.py # fails
    $ python -m pylint other/a.py -j4 # works
```

**Comment by The-Compiler** [comment]
```
[florian@ginny issue959]$ echo 'import hmac' > ../not_pylint.py
[florian@ginny issue959]$ echo '1/0' > hmac.py
```

```
[florian@ginny issue959]$ python3 ../not_pylint.py  # If pylint fails, why does this work?
[florian@ginny issue959]$ python2 ../not_pylint.py 
```

```
[florian@ginny issue959]$ pylint hmac.py -rn
No config file found, using default configuration
************* Module hmac
C:  1, 0: Missing module docstring (missing-docstring)
W:  1, 0: Statement seems to have no effect (pointless-statement)
```

```
[florian@ginny issue959]$ pylint hmac.py -rn -j2
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/bin/pylint", line 9, in <module>
    load_entry_point('pylint==1.6.1', 'console_scripts', 'pylint')()
  File "/usr/lib/python3.5/site-packages/pylint/__init__.py", line 11, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/pylint/lint.py", line 1308, in __init__
    linter.check(args)
  File "/usr/lib/python3.5/site-packages/pylint/lint.py", line 733, in check
    self._parallel_check(files_or_modules)
  File "/usr/lib/python3.5/site-packages/pylint/lint.py", line 801, in _parallel_check
    for result in self._parallel_task(files_or_modules):
  File "/usr/lib/python3.5/site-packages/pylint/lint.py", line 757, in _parallel_task
    tasks_queue = manager.Queue()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 628, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 520, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 730, in answer_challenge
    import hmac
  File "/home/florian/tmp/issue959/hmac.py", line 1, in <module>
    1/0
ZeroDivisionError: division by zero
```

**Comment by jwilk** [comment]
To debug this, I added some code at top of `/usr/local/bin/pylint` to trace `sys.path` changes:
```python
from __future__ import print_function

import itertools
import difflib
import sys

def lformat(lst):
    return '[\n{0}]'.format(''.join('  {0!r},\n'.format(item) for item in lst))

orig_sys_path = list(sys.path)
print('Initial sys.path = ' + lformat(sys.path))
def trace_sys_path(frame, event, arg):
    global orig_sys_path
    try:
        sys_path = sys.path
    except AttributeError:
        # could happend during interpreter cleanup
        return
    if sys_path is None:
        # could happend during interpreter cleanup
        return
    if sys_path != orig_sys_path:
        print('sys.path changed at {f.f_code.co_filename}:{f.f_lineno}:'.format(f=frame), end='')
        orig_sys_path_f = lformat(orig_sys_path).splitlines()
        sys_path_f = lformat(sys_path).splitlines()
        diff = difflib.unified_diff(orig_sys_path_f, sys_path_f, n=9999)
        for line in itertools.islice(diff, 3, None):
            print(line)
    orig_sys_path = list(sys_path)
    return trace_sys_path

sys.settrace(trace_sys_path)
```
I also modified `/home/jwilk/badpylint/hmac.py` to stop tracing once it's imported:
```python
import sys
sys.settrace(None)
raise RuntimeError("BAD PYLINT!")
```

It is now evident that it is pylint itself that messes with `sys.path`:
```
$ cd / && pylint -j2 /home/jwilk/badpylint/test.py 
Initial sys.path = [
  '/usr/local/bin',
  '/usr/lib/python35.zip',
  '/usr/lib/python3.5',
  '/usr/lib/python3.5/plat-x86_64-linux-gnu',
  '/usr/lib/python3.5/lib-dynload',
  '/usr/local/lib/python3.5/dist-packages',
  '/usr/lib/python3/dist-packages',
]
sys.path changed at /usr/local/lib/python3.5/dist-packages/astroid/__init__.py:134: [
   '/usr/local/bin',
   '/usr/lib/python35.zip',
   '/usr/lib/python3.5',
   '/usr/lib/python3.5/plat-x86_64-linux-gnu',
   '/usr/lib/python3.5/lib-dynload',
   '/usr/local/lib/python3.5/dist-packages',
   '/usr/lib/python3/dist-packages',
+  '/usr/local/lib/python3.5/dist-packages/astroid/brain',
 ]
No config file found, using default configuration
sys.path changed at /usr/local/lib/python3.5/dist-packages/pylint/lint.py:1135: [
+  '/home/jwilk/badpylint',
   '/usr/local/bin',
   '/usr/lib/python35.zip',
   '/usr/lib/python3.5',
   '/usr/lib/python3.5/plat-x86_64-linux-gnu',
   '/usr/lib/python3.5/lib-dynload',
   '/usr/local/lib/python3.5/dist-packages',
   '/usr/lib/python3/dist-packages',
   '/usr/local/lib/python3.5/dist-packages/astroid/brain',
 ]
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 45, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.5/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1136, in fix_import_path
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 124, in _patch_sysmodules
    yield
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 739, in check
    self._parallel_check(files_or_modules)
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 807, in _parallel_check
    for result in self._parallel_task(files_or_modules):
  File "/usr/local/lib/python3.5/dist-packages/pylint/lint.py", line 763, in _parallel_task
    tasks_queue = manager.Queue()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 628, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 520, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 730, in answer_challenge
    import hmac
  File "/home/jwilk/badpylint/hmac.py", line 2, in <module>
    sys.settrace(None)
RuntimeError: BAD PYLINT!
```

So `/home/jwilk/badpylint` was added to `sys.path` at `pylint/lint.py:1134`, which is in the `fix_import_path()` function.

**Comment by The-Compiler** [comment]
FWIW there's even a [comment](https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L1277-L1281) where `fix_import_path` is used:

```python
        # insert current working directory to the python path to have a correct
        # behaviour
        with fix_import_path(args):
            linter.check(args)
            linter.generate_reports()
```

**Comment by PCManticore** [comment]
@jwilk Great debugging, thanks. I don't remember why do we need to add the analyzed directory into sys.path.

**Comment by PCManticore** [comment]
Reopening for investigation.

**Comment by opoplawski** [comment]
Any progress here?  There are open CVE bugs for this in Fedora.

**Comment by PCManticore** [comment]
No, there is no progress, no one got around to do that. What CVE bugs?

**Comment by opoplawski** [comment]
Mainly this - https://bugzilla.redhat.com/show_bug.cgi?id=1356022
