### ISSUE TITLE
pylint leaks open files

### ISSUE THREAD

**Issue by glyph** [PyCQA/pylint#964]
When using https://github.com/twisted/twistedchecker/, which uses pylint internally, under PyPy, I receive this traceback:

```
Traceback (most recent call last):
  File "/Users/glyph/.local/bin/twistedchecker", line 9, in <module>
  File "/Users/glyph/Projects/TwistedChecker/twistedchecker/core/runner.py", line 439, in main
  File "/Users/glyph/Projects/TwistedChecker/twistedchecker/core/runner.py", line 317, in run
  File "/Users/glyph/.local/venvs/twistedchecker/site-packages/pylint/lint.py", line 542, in check
  File "/Users/glyph/.local/venvs/twistedchecker/site-packages/pylint/lint.py", line 605, in check_astng_module
  File "/Users/glyph/.local/venvs/twistedchecker/site-packages/pylint/checkers/__init__.py", line 123, in process_module
  File "/Users/glyph/.local/venvs/twistedchecker/site-packages/logilab/astng/scoped_nodes.py", line 249, in file_stream
IOError: [Errno 24] Too many open files: '/Users/glyph/Projects/Twisted/twisted/internet/_glibbase.py'
```

This is because `pylint.checkers.BaseRawChecker.process_module` really ought to be using a context manager to close `file_stream` when it's done with it.

This is a pity because running twistedchecker on the full twisted codebase is really slow (>100 seconds) and it would be really nice to be able to use pypy to optimize it!

### pylint --version output

```
No config file found, using default configuration
pylint 0.26.0, 
astng 0.24.3, common 0.62.0
Python 2.7.10 (c09c19272c990a0611b17569a0085ad1ab00c8ff, Jun 13 2016, 03:59:08)
[PyPy 5.3.0 with GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

**Comment by PCManticore** [comment]
Thanks for reporting this issue.

But this version is really, really old! Can you try with the latest release, e.g. pylint 1.5.6 and astroid 1.4.5? We even have PyPy in our CI and the leaked files problem was the first one to be solved.

Regarding the speed, maybe twistedchecker can benefit from using ``pylint --jobs`` internally, it usually speeds up the analysis quite a lot.

**Comment by glyph** [comment]
@PCManticore Thanks for your reply!  You're right, the version is quite old.  Luckily @hawkowl has already done some work to upgrade us to 1.5.6, so hopefully that will land soon and I can check that out.

Given that you have addressed this issue in the past, I'm going to close it on the assumption that it's a duplicate of #89 .
